<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	require_once APPLICATION_PATH.'/../'.PUBLICFOLDER.'/mpdf/mpdf.php';
	
	$reportsdash = $this->baseUrl('client/view/id/'.encode($client->getID()).'/tab/report');
	if(isEmptyString($request->section)){
		$request->setParam('section', 'dashboard');
		$section = 'dashboard';
	}
	
?>
<div class="row-fluid">
	<?php if($section == 'dashboard'){ ?>
		<?php if ($acl->checkPermission('Billable Hours Report', ACTION_VIEW)) { ?>	
            <div class="col-md-12 paddingleft0">
                <div class="statbox widget box box-shadow">
                    <div class="widget-content">
                        <a href="<?php echo $reportsdash.'/section/billablehours'; ?>" class="nodecoration">
                            <div class="visual cyan"><i class="glyphicon glyphicon-signal" style="font-size:32px;"></i></div>
                            <div class="title">Billable Hours Reports</div>
                            <div class="value"></div>
                        </a>
                        <div class="divider5"></div>
                        <a href="<?php echo $reportsdash.'/section/billablehours'; ?>" class="more">View Reports <i class="pull-right icon-angle-right"></i></a>
                    </div>
                </div>
            </div>
        <?php } ?>
        <?php if ($acl->checkPermission('Activity Report', ACTION_VIEW)) { ?>	
            <div class="col-md-12 paddingleft0">
                <div class="statbox widget box box-shadow">
                    <div class="widget-content">
                        <a href="<?php echo $reportsdash.'/section/activity'; ?>" class="nodecoration">
                            <div class="visual green"><i class="glyphicon glyphicon-signal" style="font-size:32px;"></i></div>
                            <div class="title">Activity Assessment Reports</div>
                            <div class="value"></div>
                        </a>
                        <div class="divider5"></div>
                        <a href="<?php echo $reportsdash.'/section/activity'; ?>" class="more">View Reports <i class="pull-right icon-angle-right"></i></a>
                    </div>
                </div>
            </div>
        <?php } ?>
	<?php } ?>
    <?php if($section == 'billablehours'){ ?>
   		<?php require APPLICATION_PATH."/views/scripts/report/billablehours.phtml"; ?>
    <?php } ?>   
    <?php if($section == 'activity'){ ?>
   		<?php require APPLICATION_PATH."/views/scripts/report/activitylog.phtml"; ?>
    <?php } ?>     
</div>