<?php
	require_once APPLICATION_PATH.'/includes/header.php';

	# load the latest Market report
	$sql = "SELECT id FROM marketanalysisreport order by id desc limit 1 ";
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchOne($sql);
	
	$marketanalysisreport = new MarketAnalysisReport();
	$marketanalysisreport->populate($result); // debugMessage($marketanalysisreport->toArray());
	$reportname = "Latest Weekly Market Report - Vol.".$marketanalysisreport->getVolume().", No.".$marketanalysisreport->getNumber()." ".changeMySQLDateToPageFormat(
	$marketanalysisreport->getReportDate());
	$highlights = $marketanalysisreport->getHighlights();
	$reportpath = $this->serverUrl($this->baseUrl('uploads/marketanalysisreport/'.$marketanalysisreport->getFileName()));	
	
	$title = $this->translate("report_pagetitle_dashboard"); 
	$this->headTitle($title.$browserappend);
?>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('plugins/custom/pdfobject.js')); ?>"></script>
<script>
$(document).ready(function() {
	// breadcrumb config
	$("#levelone_icon").addClass('icon-bar-chart');
	$("#levelone_link").attr('href', '<?php echo $this->baseUrl('report/dashboard'); ?>').html('<?php echo $title; ?>');
	$("#leveltwo_link").attr('href', '').html('Agmis Reports');
	
}); 
</script>
<script type="text/javascript">
window.onload = function (){
	var success = new PDFObject({ url: "<?php echo $reportpath; ?>" }).embed("pdf");
};
</script>
<style>
#pdf {
	width: 100%;
	min-height:600px;
	height: auto;
	margin: 0;
	border: 1px solid green;
}
#pdf p {
   padding: 1em;
}
#pdf object {
   display: block;
   border: solid 1px #666;
}
.statbox .visual {
	margin-bottom:8px;
}
</style>
<!--=== Page Header ===-->
<div class="page-header makerelative">
    <div class="page-title">
        <h3><?php echo $title; ?></h3>
    </div>
</div>
<div class="row-fluid">
    <div id="dashboard-left" class="span12 dashboard">
        <div class="row row-bg margin0 padding0" style="padding-left:10px;">
        	<div class="divider10"></div>
			<?php if ($acl->checkPermission('Market Analysis Report', ACTION_VIEW)) { ?>	
                <div class="col-sm-4 col-md-3">
                    <div class="statbox widget box box-shadow">
                        <div class="widget-content">
                            <a href="<?php echo $this->baseUrl('marketanalysisreport/list'); ?>" class="nodecoration">
                                <div class="visual cyan"><i class="icon-bar-chart" style="font-size:24px;"></i></div>
                                <div class="title">Weekly Market Reports</span></div>
                                <div class="value"></div>
                            </a>
                            <a href="<?php echo $this->baseUrl('marketanalysisreport/list'); ?>" class="more">View Report <i class="pull-right icon-angle-right"></i></a>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <?php if ($acl->checkPermission('Approved Market Prices Report', ACTION_VIEW)) { ?>
                <div class="col-sm-4 col-md-3">
                    <div class="statbox widget box box-shadow">
                        <div class="widget-content">
                            <a href="<?php echo $this->baseUrl('report/approvedmarketprices'); ?>" class="nodecoration">
                                <div class="visual yellow"><i class="icon-bar-chart" style="font-size:24px;"></i></div>
                                <div class="title">Approved Prices Report</span></div>
                                <div class="value"></div>
                            </a>
                            <a href="<?php echo $this->baseUrl('report/approvedmarketprices'); ?>" class="more">View Report <i class="pull-right icon-angle-right"></i></a>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <?php if ($acl->checkPermission('AMIA Submissions Report', ACTION_VIEW)) { ?>
                <div class="col-sm-4 col-md-3">
                    <div class="statbox widget box box-shadow">
                        <div class="widget-content">
                            <a href="<?php echo $this->baseUrl('report/submissions'); ?>" class="nodecoration">
                                <div class="visual green"><i class="icon-bar-chart" style="font-size:24px;"></i></div>
                                <div class="title">AMIA Submissions Report</div>
                                <div class="value"></div>
                            </a>
                            <a href="<?php echo $this->baseUrl('report/submissions'); ?>" class="more">View Report <i class="pull-right icon-angle-right"></i></a>
                        </div>
                    </div>
                </div>
            <?php } ?>   
            <?php if ($acl->checkPermission('Current Market Prices Report', ACTION_VIEW)) { ?>
                <div class="col-sm-4 col-md-3">
                    <div class="statbox widget box box-shadow">
                        <div class="widget-content">
                            <a href="<?php echo $this->baseUrl('report/latestmarketprices'); ?>" class="nodecoration">
                                <div class="visual blue"><i class="icon-bar-chart" style="font-size:24px;"></i></div>
                                <div class="title">Current Market Prices Report</div>
                                <div class="value"></div>
                            </a>
                            <a href="<?php echo $this->baseUrl('report/latestmarketprices'); ?>" class="more">View Report <i class="pull-right icon-angle-right"></i></a>
                        </div>
                    </div>
                </div>
            <?php } ?>  
            <?php if ($acl->checkPermission('Current Fuel Prices Report', ACTION_VIEW)) { ?>
                <div class="col-sm-4 col-md-3">
                    <div class="statbox widget box box-shadow">
                        <div class="widget-content">
                            <a href="<?php echo $this->baseUrl('report/latestfuelprices'); ?>" class="nodecoration">
                                <div class="visual cyan"><i class="icon-bar-chart" style="font-size:24px;"></i></div>
                                <div class="title">Current Fuel Prices Report</div>
                                <div class="value"></div>
                            </a>
                            <a href="<?php echo $this->baseUrl('report/latestfuelprices'); ?>" class="more">View Report <i class="pull-right icon-angle-right"></i></a>
                        </div>
                    </div>
                </div>
            <?php } ?> 
            <?php if ($acl->checkPermission('Price Trends Report', ACTION_VIEW)) { ?>
                <div class="col-sm-4 col-md-3">
                    <div class="statbox widget box box-shadow">
                        <div class="widget-content">
                            <a href="<?php echo $this->baseUrl('report/pricetrends'); ?>" class="nodecoration">
                                <div class="visual yellow"><i class="icon-bar-chart" style="font-size:24px;"></i></div>
                                <div class="title">Price Trends Report</div>
                                <div class="value"></div>
                            </a>
                            <a href="<?php echo $this->baseUrl('report/pricetrends'); ?>" class="more">View Report <i class="pull-right icon-angle-right"></i></a>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <?php if ($acl->checkPermission('Price Comparison Report', ACTION_VIEW)) { ?>
                <div class="col-sm-4 col-md-3">
                    <div class="statbox widget box box-shadow">
                        <div class="widget-content">
                            <a href="<?php echo $this->baseUrl('report/pricecomparison'); ?>" class="nodecoration">
                                <div class="visual green"><i class="icon-bar-chart" style="font-size:24px;"></i></div>
                                <div class="title">Price Comparison Report</div>
                                <div class="value"></div>
                            </a>
                            <a href="<?php echo $this->baseUrl('report/pricecomparison'); ?>" class="more">View Report <i class="pull-right icon-angle-right"></i></a>
                        </div>
                    </div>
                </div>
            <?php } ?> 
           	<?php if ($acl->checkPermission('Subscriber Report', ACTION_VIEW)) { ?>
                <div class="col-sm-4 col-md-3">
                    <div class="statbox widget box box-shadow">
                        <div class="widget-content">
                            <a href="<?php echo $this->baseUrl('report/subscriber'); ?>" class="nodecoration">
                                <div class="visual blue"><i class="icon-bar-chart" style="font-size:24px;"></i></div>
                                <div class="title">Subscriber Report</div>
                                <div class="value"></div>
                            </a>
                            <a href="<?php echo $this->baseUrl('report/subscriber'); ?>" class="more">View Report <i class="pull-right icon-angle-right"></i></a>
                        </div>
                    </div>
                </div>
			<?php } ?>
        </div>
	</div>
    <div id="dashboard-below" class="span12 report padding0 margin0" style="margin:0;">        
        <div class="row row-bg" style="background-color:#fff; padding-left:10px; padding-top:5px;"> <!-- .row-bg -->
            <div class="col-md-6">
                <h4 style="font-size:18px;"><?php echo $marketanalysisreport->getLink($reportname); ?></h4>
                <div class="col-md-12 padding0"><?php echo snippet(nl2br($highlights), 800, '...'); ?>
                	<div class="divider10"></div>
					<?php if ($acl->checkPermission('Market Analysis Report', ACTION_EXPORT)) { ?>
                        <a href="<?php echo $this->serverUrl($this->baseUrl('download/marketanalysisreport/filename/'.$marketanalysisreport->getFileName())); ?>" target="_blank" class="btn btn-xs btn-info" title="Download"> <i class="icon-arrow-down"></i> Download</a>
                    <?php } ?>
                </div>
            </div>
            <div class="divider10"></div>
            <div class="col-md-12" style="height:auto;">
             	<div id="pdf"><div class="alert alert-info margin10">It appears you don't have Adobe Reader or PDF support in this web browser. <a href="<?php echo $reportpath; ?>">Click here to download the PDF</a></div></div>
            </div>
        </div>
    </div>
</div><!--row-fluid-->
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
