<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$userid = $session->getVar("userid"); // debugMessage($userid);
	$pageid = $request->id;
	$module = $request->module;
	$user = new UserAccount();
	$user->populate($userid);
	
?>
<ul id="mainNav">
    <li class="nav-header" style="height:30px; background: none repeat scroll 0 0 #DDDDDD; border-bottom: 1px solid #CCCCCC; height: 32px;"></li>
    <li id="navDashboard" class="nav">
        <a style="font-weight:bold;"><span class="glyphicon glyphicon-indent-left"></span> Quicklinks</a>				
    </li>
    <?php if ($acl->checkPermission('Client', ACTION_LIST)) { ?>	
        <li class="nav dropdown <?php echo $controller == 'client' ? 'active' : ''; ?>">
            <a class="gonowhere"><span class="glyphicon glyphicon-user"></span> Manage Clients</a>
            <ul class="subNav client" <?php echo $controller == 'client' ? 'style="display:block;"' : ''; ?>>
                <li><a href="<?php echo $this->baseUrl('client/list'); ?>" class="block">Clients</a></li>
                <?php if ($acl->checkPermission('Client', ACTION_CREATE)) { ?>	
                	<li><a href="<?php echo $this->baseUrl('client'); ?>" class="block">New Client</a></li>
                <?php } ?>
            </ul>						
        </li>
    <?php } ?>
    <?php if ($acl->checkPermission('Application Settings', ACTION_LIST)) { ?>
    	<li class="nav dropdown <?php echo $controller == 'config' ? 'active' : ''; ?>">
            <a class="gonowhere"><span class="glyphicon glyphicon-cog"></span> Variable Maintenance </a>
            <ul class="subNav" <?php echo $controller == 'config' ? 'style="display:block;"' : ''; ?>>
            	<li <?php echo $request->type == 41 ? 'class="active"' : ''; ?>><a href="<?php echo $this->baseUrl('config/variables/type/41'); ?>">Programs</a></li>
                <li <?php echo $request->type == 42 ? 'class="active"' : ''; ?>><a href="<?php echo $this->baseUrl('config/variables/type/42'); ?>">Voucher Service Types</a></li>
                <li <?php echo $request->type == 44 ? 'class="active"' : ''; ?>><a href="<?php echo $this->baseUrl('config/variables/type/44'); ?>">F/A Service Types</a></li>
                <li <?php echo $request->type == 15 ? 'class="active"' : ''; ?>><a href="<?php echo $this->baseUrl('config/variables/type/15'); ?>">Disability Codes</a></li>
                <li <?php echo $request->type == 16 ? 'class="active"' : ''; ?>><a href="<?php echo $this->baseUrl('config/variables/type/16'); ?>">Disability Cause Codes</a></li>
                <li <?php echo $request->type == 43 ? 'class="active"' : ''; ?>><a href="<?php echo $this->baseUrl('config/variables/type/43'); ?>">Funders</a></li>
                <li <?php echo $request->type == 45 ? 'class="active"' : ''; ?>><a href="<?php echo $this->baseUrl('config/variables/type/45'); ?>">Employers</a></li>
                <li><a href="<?php echo $this->baseUrl('config/variables'); ?>">All Variables</a></li>
            </ul>
        </li>
    <?php } ?>
    <?php if ($acl->checkPermission('Application Settings', ACTION_LIST)) { ?>
        <li class="nav dropdown <?php echo $controller == 'profile' ? 'active' : ''; ?>">
            <a class="gonowhere"><span class="glyphicon glyphicon-cog"></span> System </a>
            <ul class="subNav" <?php echo $controller == 'profile' ? 'style="display:block;"' : ''; ?>>
                <?php if ($acl->checkPermission('User Account', ACTION_CREATE)) { ?>	
                    <li><a href="<?php echo $this->baseUrl('profile'); ?>">New User</a></li>
                <?php } ?>
                <?php if ($acl->checkPermission('User Account', ACTION_LIST)) { ?>
                	<li><a href="<?php echo $this->baseUrl('profile/list'); ?>">User Profiles</a></li>
                <?php } ?>
                <?php if ($acl->checkPermission('Role', ACTION_LIST)) { ?>
                	<li><a href="<?php echo $this->baseUrl('role/list'); ?>">User Roles</a></li>
                <?php } ?>
                <li><a href="<?php echo $this->baseUrl('config/variables'); ?>">System Variables</a></li>
                <li><a href="<?php echo $this->baseUrl('config/global'); ?>">Global Configuration</a></li>
            </ul>	
        </li>
    <?php } ?>
</ul>