<table style="width:800px; margin:0; position:relative;">	
    <tr>
    	<td style="padding:10px 15px; margin:0; background-color:#82CA39;"><span style="color: #3E5D78; font-size: 25px; font-weight: bold; height:65px; padding:5px 30px; background-color:#fff; display:inline-block; width:auto;"><img src="<?php echo $this->logourl; ?>" /></span></td>
    </tr>
</table>
<table style="width:800px; margin:0; padding:25px 25px 25px 15px; background-color:#FAFAFA; font-family: Arial, Helvetica, Tahoma, sans-serif; font-size:15px; line-height: 1.2em;">    
    <tr>
    	<td>