<div class="divider10"></div>
<fieldset class="fieldsetcontainer">
    <legend>Maintenance</legend>	
    <div class="row-fluid margin0">
        <div class="col-md-12">
            <div class="divider15"></div>
            <p class="floatleft">
                <?php if($acl->checkPermission('Client', ACTION_EDIT)){ ?>
                    <a class="btn btn-default btn-xs <?php echo !$client->isActive() ? 'btn-alert alert-dialog' : ''; ?>" href="<?php echo $this->baseUrl('client/picture/id/'.encode($client->getID())); ?>" message="<?php echo !$client->isActive() ? 'This Account is closed and updates are disabled' : ''; ?>"><i class="glyphicon glyphicon-upload"></i> Upload Photo</a>
                <?php } ?>
                <?php if($acl->checkPermission('Client', ACTION_DELETE)){ ?>
                    <button type="button" class="btn btn-danger btn-xs <?php echo !$client->isActive() ? 'btn-alert alert-dialog' : 'confirm-dialog'; ?>" message="<?php echo !$client->isActive() ? 'This Account is closed and updates are disabled' : 'Are you sure you want to Delete this Account? Please note that erasing this entry will also wipe out all data related to it!'; ?>" action="<?php echo $this->baseUrl('client/delete/id/'.encode($client->getID())."/entityname/Client/successurl/".encode($listurl)); ?>"><i class="glyphicon glyphicon-remove"></i> Delete Account</button>
                <?php } ?>
            </p>
        </div>
    </div>
    <div class="divider5"></div>
</fieldset>