<?php if(isEmptyString($request->pgc)){ ?>
<!--Fields for the client bio data both update and new-->
<script>
$(document).ready(function() {
	// custom date picker options
	var dateofbirthOpts = datepickerOpts;
	dateofbirthOpts.yearRange = "-<?php echo date('Y')-1900; ?>:-0"; 
	dateofbirthOpts.minDate = "-<?php echo '1900'; ?>Y";
	datepickerOpts.maxDate = new Date("Dec 31, <?php echo date('Y'); ?>");
	$("#dateofbirth").datepicker(dateofbirthOpts);
	
	$(".birth").change(function(){
		var day = $("#birthday").val();
		var month = trim($("#birthmonth option:selected").text());
		var year = $("#birthyear").val();
		var thedate = '';
		if(!isEmptyString(day) && !isEmptyString(month) && !isEmptyString(year)){
			thedate = month+' '+day+', '+year; // alert(thedate);
			$("#dateofbirth").val(thedate).change();
		}
	});
	
	$("#dateofbirth").change(function(){
		var birth = $(this).val(); // alert(birth);				
		var birthobj = new Date(birth); //alert(birthobj.getFullYear());		
		var now = new Date(); // alert(now.getFullYear());
		var yeardiff = now.getFullYear() - birthobj.getFullYear();
		// alert(yeardiff);
		if(isEmptyString(yeardiff) || isNaN(yeardiff)){
			$("#agediff").html('--');
		} else {
			$("#agediff").html(yeardiff);
		}
	});
	
	<?php if($request->getActionName() == 'view' && $step == 'view'){ ?>
		$("#agediff").html('<?php echo $client->getAge(); ?>');		
	<?php } ?>
	
	$("#dateofbirth").change();
	$("#datecontainer img.ui-datepicker-trigger").hide();
	
	$.validator.addMethod("validbirth", function(value, element, params) { 
		var day = $("#birthday").val();
		var month = $("#birthmonth").val();
		var year = value;
		if (
			(!isEmptyString(year) && (isEmptyString(day) || !isEmptyString(month))) ||
			(!isEmptyString(day) && (isEmptyString(year) || !isEmptyString(month))) ||
			(!isEmptyString(month) && (isEmptyString(year) || !isEmptyString(day)))  
		) {
			return false; 
		}
		return true;        
	}, "Please select full Date of Birth");
	
	$.validator.addMethod("phonecount_validate", function(value, element) {	
		k=0;
		$('.isphone').each(function(i, e) {
			phonum = trim($(e).val());
			if(!isEmptyString(phonum)){
				k++;
			}
		});		
		if(k > 0){
			return true;
		}
		return false;
	}, "<?php echo $this->translate("client_phone_count_error"); ?>");
	
	// show message for invalid emails but allow user to save the form
	$(".reminderfield").change(function(){
		var fieldid = $(this).attr('id');
		var value = $(this).val();
		if(!isEmptyString(value) && !isValidEmailAddress(value)){
			$('#'+fieldid+'_error').html('<div class="divider5"></div><div class="alert alert-danger" style="margin-bottom:0;">Please enter a valid email</div>');
		} else {
			$('#'+fieldid+'_error').html('');
		}
	});
	$(".reminderfield").change();
	
});
</script>
<?php } ?>
<style>
.birth {
	padding-left:2px;
	font-size:10px;
}
</style>
<fieldset class="fieldsetcontainer">
    <legend>About</legend>
    <div class="panel-body well-sm">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="col-sm-4 control-label" for="firstname"><?php echo $this->translate("client_firstname_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                <div class="col-sm-8">
                    <p class="form-control-static nullifempty view"><?php echo $client->getFirstName(); ?></p>
                    <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                    <div class="edit">
                        <input type="text" class="form-control input-sm" id="firstname" name="firstname" value="<?php echo $client->getFirstName(); ?>" />
                        <div id="firstname_error"></div>
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label"><?php echo $this->translate("client_initial_label"); ?>: </label>
                <div class="col-sm-8">
                    <p class="form-control-static nullifempty view"><?php echo $client->getInitial(); ?></p>
                    <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                    <div class="edit"><input type="text" class="form-control input-sm width75" id="initial" name="initial" value="<?php echo $client->getInitial(); ?>" />
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label"><?php echo $this->translate("client_lastname_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                <div class="col-sm-8">
                    <p class="form-control-static nullifempty view"><?php echo $client->getLastName(); ?></p>
                    <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                    <div class="edit">
                        <input type="text" class="form-control input-sm" id="lastname" name="lastname" value="<?php echo $client->getLastName(); ?>" />
                        <div id="lastname_error"></div>
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label"><?php echo $this->translate("client_middlename_label"); ?>:</label>
                <div class="col-sm-8">
                    <p class="form-control-static nullifempty view"><?php echo $client->getmiddlename(); ?></p>
                    <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                    <div class="edit">
                        <input type="text" class="form-control input-sm" id="middlename" name="middlename" value="<?php echo $client->getmiddlename(); ?>" />
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label"><?php echo $this->translate("client_nickname_label"); ?>:</label>
                <div class="col-sm-8">
                    <p class="form-control-static nullifempty view"><?php echo $client->getnickname(); ?></p>
                    <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                    <div class="edit">
                        <input type="text" class="form-control input-sm" id="nickname" name="nickname" value="<?php echo $client->getnickname(); ?>" />
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label"><?php echo $this->translate("client_gender_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                <div class="col-sm-8" style="padding-right:0;">
                    <p class="form-control-static nullifempty view"><?php echo $client->getGenderText(); ?></p>
                    <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                    <div class="edit" style="font-size:10px;">
                      <label class="radio-inline"><input type="radio" name="gender" id="male" value="1" class="xform-control radiobutton <?php echo $client->getGender() == '1'? 1 : 0; ?>"> Male</label>
                      <label class="radio-inline"><input type="radio" name="gender" id="female" value="2" class="xform-control radiobutton <?php echo $client->getGender() == '2'? 1 : 0; ?>"> Female</label>
                      <label class="radio-inline"><input type="radio" name="gender" id="transgender" value="3" class="xform-control radiobutton <?php echo $client->getGender() == '3'? 1 : 0; ?>"> Transgender</label>
                      <input type="hidden" name="gender_old" id="gender_old" value="<?php echo $client->getGender(); ?>" />
                      <div id="gender_error"></div>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="col-sm-4 control-label"><?php echo $this->translate("client_ssn_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                <div class="col-sm-8">
                    <p class="form-control-static nullifempty view"><?php echo $client->getSSN(); ?></p>
                    <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                    <div class="edit">
                        <input type="text" class="form-control input-sm" id="ssn" name="ssn" value="<?php echo $client->getSSN(); ?>" />
                        <div id="ssn_error"></div>
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label"><?php echo $this->translate("client_dob_label"); ?>:</label>
                <div class="col-sm-8" style="padding-right:0;">
                	<?php 
						$yeardiff = '';
						if(!isEmptyString($client->getDateofBirth())){
							$now = date('Y');
							$birthyr = date('Y', strtotime($client->getDateofBirth()));
							$yeardiff = intval($now) - intval($birthyr);
						}
						$datestyle = 'width:65px; display:inline; font-size:10px; padding-left:2px;';
						if(isEmptyString($client->getID())){
							$datestyle = 'width:85px; display:inline; font-size:12px; padding-left:4px;';
						}
						
					?>
                    <p class="form-control-static nullifempty view"><?php echo changeMySQLDateToPageFormat($client->getDateofBirth()); ?><!-- <b style="margin-left:20px;">Age:</b> &nbsp;<span id="phpyeardiff" class="lineblocked"><?php //echo $yeardiff; ?></span>--></p>
                    <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                        <div class="edit" id="datecontainer"><div class="divider5"></div>
                            <?php
								$daydp = new Zend_Form_Element_Select('birthday',
													array(
														'multiOptions' => array_merge_maintain_keys(array('' => 'Day'), getMonthDays()),	
														'view' => new Zend_View(),
														'decorators' => array('ViewHelper'),
														'class' => array('birth form-control input-sm'),
														'style' => $datestyle		
													)
												);
								$daydp->setValue($birthday); 
								echo $daydp->render(); 
							?> 
							<?php
								$monthdp = new Zend_Form_Element_Select('birthmonth',
													array(
														'multiOptions' => array_merge_maintain_keys(array('' => 'Month'), getAllMonthsAsShortNames()),	
														'view' => new Zend_View(),
														'decorators' => array('ViewHelper'),
														'class' => array('birth form-control input-sm'),
														'style' => $datestyle		
													)
												);
								$monthdp->setValue($birthmonth); 
								echo $monthdp->render(); 
							?> 
							<?php
								$years = getSubscribeBirthYears();
								$yeardp = new Zend_Form_Element_Select('birthyear',
													array(
														'multiOptions' => array_merge_maintain_keys(array('' => 'Year'), $years),	
														'view' => new Zend_View(),
														'decorators' => array('ViewHelper'),
														'class' => array('birth'),
														'class' => array('birth form-control input-sm'),
														'style' => $datestyle		
													)
												);
								$yeardp->setValue($birthyear); 
								echo $yeardp->render(); 
							?>
                            <input type="hidden" class="form-control input-sm xdatefield readonly width100" name="dateofbirth" id="dateofbirth" value="<?php echo changeMySQLDateToPageFormat($client->getDateofBirth()); ?>" />
                            <div id="birthyear_error"></div>
                        </div>
                    <?php } ?>                                                           
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label">Age:</label>       
                <div class="col-sm-8" style="padding-left:8px;">&nbsp; 
                    <span id="agediff" class="lineblocked">--</span>
                </div>
            </div>                                 
            <div class="form-group">
                <label class="col-sm-4 control-label"><?php echo $this->translate("client_maritalstatus_label"); ?>:</label>
                <div class="col-sm-8">
                    <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($client->getMaritalStatus(), $maritalstatuses) ? '': $maritalstatuses[$client->getMaritalStatus()]; ?></p>
                    <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                        <div class="edit">
                            <?php
                                $dropdown = new Zend_Form_Element_Select('maritalstatus',
                                                    array(
                                                        'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $maritalstatuses, array('0'=>$this->translate("global_addvariable_label"))),
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('form-control','input-sm','configvariable'),
                                                        'lookupid' => 11,
                                                        'fieldid' => 'maritalstatus',
                                                        'fieldlabel' => $this->translate("client_maritalstatus_label")
                                                    )
                                );  
                                $dropdown->setValue($client->getMaritalStatus()); 
                                echo $dropdown->render();
                            ?>
                            <input type="hidden" class="form-control" name="maritalstatus_old" id="maritalstatus_old" value="<?php echo $client->getMaritalStatus(); ?>" />
                        </div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label"><?php echo $this->translate("client_race_label"); ?>:</label>
                <div class="col-sm-8">
                    <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($client->getRace(), $races) ? '': $races[$client->getRace()]; ?></p>
                    <div class="edit">
                    <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                        <?php
                            $dropdown = new Zend_Form_Element_Select('race',
                                                array(
                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $races, array('0'=>$this->translate("global_addvariable_label"))),
                                                    'view' => new Zend_View(),
                                                    'decorators' => array('ViewHelper'),
                                                    'class' => array('form-control','input-sm','configvariable'),
													'lookupid' => 13,
													'fieldid' => 'race',
													'fieldlabel' => $this->translate("client_race_label")
                                                )
                            );  
                            $dropdown->setValue($client->getRace()); 
                            echo $dropdown->render();
                        ?>
                        <input type="hidden" class="form-control" name="race_old" id="race_old" value="<?php echo $client->getRace(); ?>" />
                    <?php } ?>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label"><?php echo $this->translate("client_language_label"); ?>:</label>
                <div class="col-sm-8">
                    <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($client->getLanguage(), $languages) ? '': $languages[$client->getLanguage()]; ?></p>
                    <div class="edit">
						<?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                            <?php
                                $dropdown = new Zend_Form_Element_Select('language',
                                                    array(
                                                        'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $languages, array('0'=>$this->translate("global_addvariable_label"))),
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('form-control','input-sm','configvariable'),
                                                        'lookupid' => 47,
                                                        'fieldid' => 'language',
                                                        'fieldlabel' => $this->translate("client_language_label")
                                                    )
                                );  
                                $dropdown->setValue($client->getLanguage()); 
                                echo $dropdown->render();
                            ?>
                            <input type="hidden" class="form-control" name="language_old" id="languagee_old" value="<?php echo $client->getLanguage(); ?>" />
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</fieldset>
<?php if(isEmptyString($request->pgc)){ ?>  
<div class="divider10"></div>
<?php } ?>
<div class="row-fluid margin0">
    <div class="col-sm-6 paddingleft0">
        <fieldset class="fieldsetcontainer" id="location" style="min-height:300px;">
            <legend>Address</legend>
            <div class="panel-body well-sm">
                <div class="col-sm-12">
                    <div id="xxx"></div>
                    <input type="text" class="form-control" name="xxx" id="xxx" value="" style="border:none; border:#fff hidden; height:2px; box-shadow:none;" />
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo $this->translate("global_addressline1_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-sm-8">
                            <p class="form-control-static nullifempty view"><?php echo $client->getAddressline1(); ?></p>
                            <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                            <div class="edit">
                                <input type="text" class="form-control input-sm" id="addressline1" name="addressline1" value="<?php echo $client->getAddressline1(); ?>" />
                                <div id="addressline1_error"></div>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo $this->translate("global_addressline2_label"); ?>:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static nullifempty view"><?php echo $client->getAddressline2(); ?></p>
                            <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                            <div class="edit">
                                <input type="text" class="form-control input-sm" id="addressline2" name="addressline2" value="<?php echo $client->getAddressline2(); ?>" />
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo $this->translate("global_city_label"); ?>/<?php echo $this->translate("global_town_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-sm-8">
                            <p class="form-control-static nullifempty view"><?php echo $client->getCity(); ?></p>
                            <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                            <div class="edit">
                                <input type="text" class="form-control input-sm" id="city" name="city" value="<?php echo $client->getCity(); ?>" />
                                <div id="city_error"></div>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo $this->translate("global_state_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-sm-8">
                            <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($client->getState(), $states) ? '': $states[$client->getState()]; ?></p> 
                            <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                            <div class="edit">
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('state',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $states),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm')
                                                        )
                                    );  
                                    $dropdown->setValue($client->getState()); 
                                    echo $dropdown->render();
                                ?>
                                <div id="state_error"></div>
                                <!--<input type="hidden" class="form-control" name="state" id="state" value="<?php //echo $client->getState(); ?>" />-->
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo $this->translate("global_zipcode_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-sm-8">
                            <p class="form-control-static nullifempty view"><?php echo $client->getZipCode(); ?></p>
                            <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                            <div class="edit">
                                <input type="text" class="form-control input-sm width100" id="zipcode" name="zipcode" value="<?php echo $client->getZipCode(); ?>" />
                                <div id="zipcode_error"></div>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo $this->translate("global_county_label"); ?>:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($client->getCounty(), $counties) ? '': $counties[$client->getCounty()]; ?></p>  
                            <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                            <div class="edit">
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('county',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $counties, array('0'=>$this->translate("global_addvariable_label"))),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm','configvariable'),
															'lookupid' => 10,
															'fieldid' => 'county',
															'fieldlabel' => $this->translate("global_county_label")
                                                        )
                                    );  
                                    $dropdown->setValue($client->getCounty()); 
                                    echo $dropdown->render();
                                ?><input type="hidden" class="form-control" name="county_old" id="county_old" value="<?php echo $client->getCounty(); ?>" />
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">&nbsp;</label>
                        <div class="col-sm-8" style="height:42px;">&nbsp;</div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
    <div class="col-sm-6 padding0">
        <fieldset class="fieldsetcontainer" id="contact" style="min-height:300px;">
            <legend>Contact</legend>
            <div class="panel-body well-sm">
                <div class="col-sm-12">
                	<div id="phonecount_error"></div>
                    <input type="text" class="form-control" name="phonecount" id="phonecount" value="" style="border:none; border:#fff hidden; height:2px; box-shadow:none;" />
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo $this->translate("client_homephone_label"); ?>:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static nullifempty view"><?php echo $client->getHome(); ?></p>
                            <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                            <div class="edit">
                                <input type="text" class="form-control input-sm isphone" id="home" name="home" value="<?php echo $client->getHome(); ?>" />
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo $this->translate("client_cellphone_label"); ?>:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static nullifempty view"><?php echo $client->getCell(); ?></p>
                            <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                            <div class="edit">
                                <input type="text" class="form-control input-sm isphone" id="cell" name="cell" value="<?php echo $client->getCell(); ?>" />
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo $this->translate("client_workphone_label"); ?>:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static nullifempty view"><?php echo $client->getWork(); ?></p>
                            <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                            <div class="edit">
                                <input type="text" class="form-control input-sm isphone" id="work" name="work" value="<?php echo $client->getWork(); ?>" />
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo $this->translate("client_workext_label"); ?>:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static nullifempty view"><?php echo $client->getExt(); ?></p> 
                            <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                            <div class="edit">
                                <input type="text" class="form-control input-sm" id="ext" name="ext" value="<?php echo $client->getExt(); ?>" />
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo 'Personal '.$this->translate("client_email_label"); ?>:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static nullifempty view"><?php echo $client->getEmail(); ?></p> 
                            <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                            <div class="edit">
                                <input type="text" class="form-control input-sm reminderfield" id="email" name="email" value="<?php echo $client->getEmail(); ?>" />
                                <div id="email_error"></div>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo 'Alternative / Business '.$this->translate("client_email_label"); ?>:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static nullifempty view"><?php echo $client->getEmail2(); ?></p> 
                            <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                            <div class="edit">
                                <input type="text" class="form-control input-sm reminderfield" id="email2" name="email2" value="<?php echo $client->getEmail2(); ?>" />
                                <div id="email2_error"></div>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo $this->translate("client_emailpassword_label"); ?>:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static nullifempty view"><?php echo $client->getEmailPassword(); ?></p> 
                            <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                            <div class="edit">
                                <input type="text" class="form-control input-sm" id="emailpassword" name="emailpassword" value="<?php echo $client->getEmailPassword(); ?>" />
                                <div id="emailpassword_error"></div>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<?php if(isEmptyString($request->pgc)){ ?> 
<div class="divider10"></div>
<?php } ?>
<div class="divider5"></div>
<fieldset class="fieldsetcontainer">
    <legend>Income Sources</legend>
    <div class="panel-body well-sm">
        <div class="col-sm-12">
            <div class="form-group">
            	<?php if(isEmptyString($client->getID())){ ?>
	            	<label class="col-sm-4 control-label">Current Income Sources:</label>
                <?php } ?>
            	<div class="col-sm-12">
                    <p class="form-control-static nullifempty view"><?php echo count($client->getIncomeSourcesArray())  == 0 ? '': $client->getListofIncomeSources(); ?></p>
                    <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                        <div class="edit">
                        	<?php echo $this->translate('global_checkall_label'); ?>
                            <div id="container_incomesourcesids">
                                <?php 
                                    $existing_values = $client->getIncomeSourcesArray();
                                    foreach($incomesources as $key => $value){
                                ?>
                                    <label class="checkbox notbolded col-sm-3">
                                      <input type="checkbox" id="incomesources_<?php echo $key; ?>" name="incomesourcesids[]" class="disableoutsidesection" value="<?php echo $key; ?>" <?php echo in_array($key, $existing_values) ? 'checked data-waschecked="true"' : ''; ?>><?php echo $value; ?>
                                    </label>
                                <?php } ?>
                             </div>
                            <div class="divider5"></div>
                            <a class="gonowhere checkothertrigger" fieldid="incomesourcesids" lookupid="26" fieldlabel="Client Employment Income Sources" fieldtype="checkbox" checkclasses="checkbox notbolded col-sm-3" checkname="incomesourcesids[]" checkid="incomesources_"><?php echo $this->translate("global_addoption_label"); ?></a>
                        </div>
                    <?php } ?>
                </div>
            </div>
     	</div>
        <div class="col-sm-12">
            <div class="form-group">
                <div class="col-sm-6 padding0">
                    <label class="col-sm-8 control-label"><?php echo $this->translate("client_totalmonthlyincome_label"); ?>:</label>
                    <div class="col-sm-4">
                        <p class="form-control-static nullifempty view"><?php echo $client->gettotalmonthlyincome(); ?></p>
                        <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                        <div class="edit">
                            <input type="text" class="form-control input-sm" id="totalmonthlyincome" name="totalmonthlyincome" value="<?php echo $client->gettotalmonthlyincome(); ?>" />
                            <input type="hidden" name="providedwithbenefitinfo_old" id="providedwithbenefitinfo_old" value="<?php echo $client->gettotalmonthlyincome(); ?>" />
                        </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="form-group">
                <label class="col-sm-12 control-label"><?php echo $this->translate("client_reduceincomebenefit_label"); ?>:</label>
                <div class="col-sm-12">
                    <p class="form-control-static nullifempty view"><?php echo $client->getreduceincomebenefit_text(); ?></p>
                    <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                    <div class="edit">
                        <label class="radio-inline">
                          <input type="radio" id="reduceincomebenefit_1" name="reduceincomebenefit" class="radiobutton disableoutsidesection" value="1" <?php echo $client->getreduceincomebenefit() == 1 && !isEmptyString($client->getreduceincomebenefit()) ? 'checked data-waschecked="true"' : ''; ?>>Yes
                        </label>
                        <label class="radio-inline">
                          <input type="radio" id="reduceincomebenefit_0" name="reduceincomebenefit" class="radiobutton disableoutsidesection" value="0" <?php echo $client->getreduceincomebenefit() == 0 && !isEmptyString($client->getreduceincomebenefit()) ? 'checked data-waschecked="true"' : ''; ?>>No
                        </label>
                        <input type="hidden" name="reduceincomebenefit_old" id="reduceincomebenefit_old" value="<?php echo $client->getreduceincomebenefit(); ?>" />
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="form-group">
                <label class="col-sm-12 control-label"><?php echo $this->translate("client_providedwithbenefitinfo_label"); ?>:</label>
                <div class="col-sm-12">
                    <p class="form-control-static nullifempty view"><?php echo $client->getprovidedwithbenefitinfotext(); ?></p>
                    <?php if(($step == 'edit' && $section == 'bio' || $step == 'new')){ ?>
                    <div class="edit">
                        <label class="radio-inline">
                          <input type="radio" id="providedwithbenefitinfo_1" name="providedwithbenefitinfo" class="radiobutton disableoutsidesection" value="1" <?php echo $client->getprovidedwithbenefitinfo() == 1 && !isEmptyString($client->getprovidedwithbenefitinfo()) ? 'checked data-waschecked="true"' : ''; ?>>Yes
                        </label>
                        <label class="radio-inline">
                          <input type="radio" id="providedwithbenefitinfo_0" name="providedwithbenefitinfo" class="radiobutton disableoutsidesection" value="0" <?php echo $client->getprovidedwithbenefitinfo() == 0 && !isEmptyString($client->getprovidedwithbenefitinfo()) ? 'checked data-waschecked="true"' : ''; ?>>No
                        </label>
                        <label class="radio-inline">
                          <input type="radio" id="providedwithbenefitinfo_2" name="providedwithbenefitinfo" class="radiobutton disableoutsidesection" value="2" <?php echo $client->getprovidedwithbenefitinfo() == 2 && !isEmptyString($client->getprovidedwithbenefitinfo()) ? 'checked data-waschecked="true"' : ''; ?>>Consumer declined offer of information
                        </label>
                        <input type="hidden" name="providedwithbenefitinfo_old" id="providedwithbenefitinfo_old" value="<?php echo $client->getprovidedwithbenefitinfo(); ?>" />
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
  	</div>
</fieldset>
