
<fieldset class="fieldsetcontainer">
    <legend>Primary Contact</legend>
    <div class="panel-body well-sm">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="col-sm-5 control-label"><?php echo $this->translate("client_contactperson_label"); ?>:</label>
                <div class="col-sm-7">
                    <p class="form-control-static nullifempty view"><?php echo $client->getContactPerson(); ?></p>
                    <?php if(($step == 'edit' && $section == 'emergency' || $step == 'new')){ ?>
                    <div class="edit">
                        <input type="text" class="form-control input-sm" id="contactperson" name="contactperson" value="<?php echo $client->getContactPerson(); ?>" />
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-5 control-label"><?php echo $this->translate("client_relationship_label"); ?>:</label>
                <div class="col-sm-7">
                    <p class="form-control-static nullifempty view"><?php echo $client->getRelationshipText(); ?></p>
                    <?php if(($step == 'edit' && $section == 'emergency' || $step == 'new')){ ?>
                    <div class="edit">
                        <?php
                            $dropdown = new Zend_Form_Element_Select('relationship',
                                                array(
                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $rships, array('0'=>$this->translate("global_addvariable_label"))),
                                                    'view' => new Zend_View(),
                                                    'decorators' => array('ViewHelper'),
                                                    'class' => array('form-control','input-sm','configvariable'),
													'lookupid' => 25,
													'fieldid' => 'relationship',
													'fieldlabel' => 'Relationship Options',
													'doubleappendid' => 'relationship2'
                                                )
                            );  
                            $dropdown->setValue($client->getRace()); 
                            echo $dropdown->render();
                        ?>
                        <input type="hidden" class="form-control" name="relationship_old" id="relationship_old" value="<?php echo $client->getrelationship(); ?>" />
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-5 control-label"><?php echo $this->translate("client_phone_label"); ?>:</label>
                <div class="col-sm-7">
                    <p class="form-control-static nullifempty view"><?php echo $client->getContactPhone(); ?></p>
                    <?php if(($step == 'edit' && $section == 'emergency' || $step == 'new')){ ?>
                    <div class="edit">
                        <input type="text" class="form-control input-sm" id="contactphone" name="contactphone" value="<?php echo $client->getContactPhone(); ?>" />
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-5 control-label"><?php echo $this->translate("client_email_label"); ?>:</label>
                <div class="col-sm-7">
                    <p class="form-control-static nullifempty view"><?php echo $client->getContactEmail(); ?></p> 
                    <?php if(($step == 'edit' && $section == 'emergency' || $step == 'new')){ ?>
                    <div class="edit">
                        <input type="text" class="form-control input-sm isvalidemail" id="contactemail" name="contactemail" value="<?php echo $client->getContactEmail(); ?>" />
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</fieldset>
<fieldset class="fieldsetcontainer">
    <legend>Secondary Contact</legend>
    <div class="panel-body well-sm">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="col-sm-5 control-label"><?php echo $this->translate("client_contactperson_label"); ?>:</label>
                <div class="col-sm-7">
                    <p class="form-control-static nullifempty view"><?php echo $client->getContactPerson2(); ?></p>
                    <?php if(($step == 'edit' && $section == 'emergency' || $step == 'new')){ ?>
                    <div class="edit">
                        <input type="text" class="form-control input-sm" id="contactperson2" name="contactperson2" value="<?php echo $client->getContactPerson2(); ?>" />
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-5 control-label"><?php echo $this->translate("client_relationship_label"); ?>:</label>
                <div class="col-sm-7">
                    <p class="form-control-static nullifempty view"><?php echo $client->getRelationship2Text(); ?></p>
                    <?php if(($step == 'edit' && $section == 'emergency' || $step == 'new')){ ?>
                    <div class="edit">
                    	<?php
                            $dropdown = new Zend_Form_Element_Select('relationship2',
                                                array(
                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $rships, array('0'=>$this->translate("global_addvariable_label"))),
                                                    'view' => new Zend_View(),
                                                    'decorators' => array('ViewHelper'),
                                                    'class' => array('form-control','input-sm','configvariable'),
													'lookupid' => 25,
													'fieldid' => 'relationship2',
													'fieldlabel' => 'Relationship Options',
													'doubleappendid' => 'relationship'
                                                )
                            );  
                            $dropdown->setValue($client->getRace()); 
                            echo $dropdown->render();
                        ?>
                        <input type="hidden" class="form-control" name="relationship2_old" id="relationship2_old" value="<?php echo $client->getrelationship2(); ?>" />
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-5 control-label"><?php echo $this->translate("client_phone_label"); ?>:</label>
                <div class="col-sm-7">
                    <p class="form-control-static nullifempty view"><?php echo $client->getContactPhone2(); ?></p>
                    <?php if(($step == 'edit' && $section == 'emergency' || $step == 'new')){ ?>
                    <div class="edit">
                        <input type="text" class="form-control input-sm" id="contactphone2" name="contactphone2" value="<?php echo $client->getContactPhone2(); ?>" />
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-5 control-label"><?php echo $this->translate("client_email_label"); ?>:</label>
                <div class="col-sm-7">
                    <p class="form-control-static nullifempty view"><?php echo $client->getContactEmail2(); ?></p> 
                    <?php if(($step == 'edit' && $section == 'emergency' || $step == 'new')){ ?>
                    <div class="edit">
                        <input type="text" class="form-control input-sm isvalidemail" id="contactemail2" name="contactemail2" value="<?php echo $client->getContactEmail2(); ?>" />
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</fieldset>
