 <?php
 	$baseview = $this->baseUrl('client/view/id/'.encode($client->getID()).'/tab/employment');
	if($step == 'view'){
		$jobs = $client->getClientJobs(); // debugMessage($job->toArray());
		$job_count = $jobs->count();
	}
	if($step == 'edit' ){
		$job_count = '';
		$job = new Job();
		$job->populate(decode($request->jobid)); // debugMessage($job->toArray());
	}
	if($step == 'new' ){
		$job_count = '';
		$job = new Job(); // debugMessage($job->toArray());
	}
	$ratetypes = getRateTypes();
	$medicaltypes = getMedicalTypes();
	$transportmodes = getTransportationModes();
	$jobstatuses = getJobStatuses();
	$terminationtypes = getTerminationTypes();
?>
<script>
	$(document).ready(function() {
		<?php if($step == 'edit' || $step == 'new'){ ?>
			// validation 
			$("#form-employment").validate({		
				// define the validation rules one field at a time
				rules: {
					jobtitle: "required",
					hoursperweek: {
						required: true
					},
					startdate: {
						required: true,
					},
					enddate: {
						required: false,
						ontermination:true,
						enddateafterstartdate: true
					},
					rate: {
						required: true
					},
					ratetype: "required",
					startdate: "required",
					status: "required",
					companyname: "required",
					contactperson: "required",
					phone: "required",
					county: "required", 
					city: "required", 
					zipcode: "required",  
					addressline1: "required",
					terminationtype: "required",
					terminationreason: "required"
				}, 
				// the messages for each of the fields being validated
				messages: {		
					jobtitle: "<?php echo $this->translate("job_jobtitle_error"); ?>",
					hoursperweek: {
						required: "<?php echo $this->translate("job_hoursperweek_error"); ?>"
					}, 
					startdate: {
						required: "<?php echo $this->translate("job_startdate_error"); ?>"
					},
					rate: {
						required: "<?php echo $this->translate("job_rate_error"); ?>"
					},
					ratetype: "<?php echo $this->translate("job_ratetype_error"); ?>",
					startdate: "<?php echo $this->translate("job_startdate_error"); ?>",
					status: "<?php echo $this->translate("job_status_error"); ?>",
					companyname: "<?php echo $this->translate("company_name_error"); ?>",
					contactperson: "<?php echo $this->translate("company_contactperson_error"); ?>",
					phone: "<?php echo $this->translate("company_phone_error"); ?>",
					county: "<?php echo $this->translate("company_county_error"); ?>", 
					city: "<?php echo $this->translate("company_city_error"); ?>", 
					zipcode: "<?php echo $this->translate("company_zipcode_error"); ?>",  
					addressline1: "<?php echo $this->translate("company_addressline1_error"); ?>",
					terminationtype: "<?php echo $this->translate("job_terminationtype_error"); ?>",
					terminationreason: "<?php echo $this->translate("job_terminationreason_error"); ?>"
				},
				// custom error positions
				errorPlacement: function(error, element) {
					switch(element.attr("name")){					
						default:
							if(element.hasClass("useid_error")){
								error.appendTo("#"+element.attr("id")+"_error");
							} else {
								error.appendTo("#"+element.attr("name")+"_error");
							}
							break;
					}			
				}
			});
			
			$.validator.addMethod("ontermination", function(value, element) {				
				if($("#status").val() == '0' && isEmptyString(value)){
					return false;
				}
				return true;
			}, "<?php echo $this->translate("job_enddate_error"); ?>");
			
			$('.edit, .requiredmark, .save_trigger, .cancel_trigger').removeClass('hidden');
			$('.form-control-static.view, .update_trigger').addClass('hidden');
			
			// on status change, if terminating job, open up fields for reason and termination type
			$("#status").change(function(){
				var status = $(this).val();
				if(status == 0){
					$(".complete").removeClass('hidden');
				}
				if(status == 1){
					$("#enddate, #terminationreason, #terminationreason").val('');
					$(".complete").addClass('hidden');										
				}
			});
			$("#status").trigger('change');
			
			$(".save_trigger, .save").click(function(e){
				e.preventDefault();
				var status = $("#status").val();
				if ($("#form-employment").valid()) {
					if(status == 1){
						$.blockUI({ message: '<?php echo $blockcontent; ?>' }); 
						$("#form-employment").submit();
					}
					if(status == 0){
						// if attempting to terminate the job
						var message = '<label class="small centeralign blocked">Are you sure you want to mark this Job as completed. <br /><br /> Click <b>OK</b> to continue or <b>Cancel</b> to ignore</label>';
						bootbox.confirm(message, function(confirmed) {
							if(confirmed){
								$.blockUI({ message: '<?php echo $blockcontent; ?>' }); 
								$("#form-employment").submit();
							} else {
								bootbox.hideAll();
								return false;
							}
						});
					}
				}
			});
		<?php } ?>
	}); 
</script>		
		<?php if($tab == 'employment' && $step == 'view'){ ?>
			$(".complete").addClass('hidden');
		<?php } ?>
<form id="form-employment" class="form-horizontal employment" role="form" action="<?php echo $this->baseUrl("job/create"); ?>" method="post">
	<?php if($step == 'view'){ ?>
        <p class="margin0 lineblocked makeabsolute" style="right:30px; top:5px;">
        	<?php if($acl->checkPermission('Job', ACTION_CREATE)){ ?>	
            	<a class="btn btn-sm btn-primary" href="<?php echo $baseview.'/step/new'; ?>"><i class="glyphicon glyphicon-plus"></i> Add Job</a>
            <?php } ?>
            <?php if($job_count > 1 && !isEmptyString($request->jobid)){ ?>
                <a class="btn btn-sm btn-default" href="<?php echo $baseview.'/step/view'; ?>"><i class="glyphicon glyphicon-list"></i> All Jobs</a>
            <?php } ?>
        </p>
    <?php } ?>
    <?php if($step == 'edit' || $step == 'new'){ ?>
        <input type="hidden" id="entityname" name="entityname" value="Job" />
        <input type="hidden" id="id" name="id" value="<?php echo encode($job->getID()); ?>" />
        <input type="hidden" id="clientid" name="clientid" value="<?php echo $client->getID(); ?>" />
        <input type="hidden" id="employerid" name="employerid" value="<?php echo $job->getemployerid(); ?>" />
        <input type="hidden" class="successurl" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($baseview); ?>" />
        <input type="hidden" class="failureurl" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($this->viewurl); ?>" />
        <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $successmessage; ?>" />
        <input type="hidden" id="nosuccessid" name="nosuccessid" value="1" />
    <?php } ?>
    <div class="panel-body padding0">
    	<div class="divider10"></div>
		<?php if($step == 'new'){ ?>
            <h5 class="inline margin0 bolded">Add new Job</h5>
        <?php } ?>
        <?php if($step == 'edit'){ ?>
            <h5 class="inline margin0 bolded">Update Job</h5>
        <?php } ?>
        <div class="row-fluid margin0">
            <div class="col-md-12 padding0 pull-right rightalign">
                <?php if($step == 'edit' || $step == 'new'){ ?>
                    <p class="margin0 lineblocked">
                        <button type="submit" class="btn btn-success btn-sm button-submit save_trigger save" name="save"><i class="glyphicon glyphicon-ok"></i> <?php echo $step == 'new' ? $this->translate('global_button_save') : $this->translate('global_button_save_changes'); ?></button>
                    </p>
                    <p class="margin0 lineblocked">
                        <a class="btn btn-default btn-sm cancel cancel_trigger"><i class="glyphicon glyphicon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                    </p>
                <?php } ?>
            </div>
        </div>
       	<?php if($job_count == 0 && $step == 'view'){ ?>
        	<div class="divider15"></div>
            <div style="clear:both;" class="alert alert-warning margin5">There are currently no Jobs for <strong><?php echo $client->getName(); ?></strong></div>
        <?php } ?>
       
		<?php if($job_count > 1 && $step == 'view' && isEmptyString($request->jobid)) { ?>
            <div class="pagedescription">Viewing details for <strong><?php echo $job_count; ?> Jobs</strong></div>
        <?php } ?>
       
		<?php if($job_count == 1 || !isEmptyString($request->jobid) || $step == 'new') { 
            if($job_count == 1){
                $job = $jobs->get(0);
            }
            if(!isEmptyString($request->jobid)){
                $job = new Job();
                $job->populate(decode($request->jobid));
            }
			if($step == 'new'){
                $job = new Job();
				if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
					$formvalues = $session->getVar(FORM_VALUES);
					$job->processPost($formvalues);
				}
            }
        ?>
            <fieldset class="fieldsetcontainer">
            <legend>Job Details</legend>
            <div class="panel-body well-sm makerelative">
                <?php if($step == 'view'){ ?>
                    <p class="margin0 lineblocked makeabsolute" style="right:5px; top:-5px;">
                        <?php if($acl->checkPermission('Job', ACTION_EDIT)){ ?>	
                            <a class="btn btn-default btn-xs <?php echo !$client->isActive() ? 'btn-alert alert-dialog' : 'update_trigger'; ?>" message="This Account is closed and updates are disabled." href="<?php echo $baseview.'/step/edit/jobid/'.encode($job->getID()); ?>" title="Update"><i class="glyphicon glyphicon-pencil"></i> Update</a>
                        <?php } ?>
                        <?php if($acl->checkPermission('Job', ACTION_DELETE)){ ?>
                            <button type="button" class="btn btn-default btn-xs confirm-dialog noimgbuttonsmall" title="Delete" message="Are you sure you want to delete this entry?" action="<?php echo $this->baseUrl('job/delete/id/'.encode($job->getID())."/entityname/Job/successurl/".encode($baseview)); ?>"><i class="glyphicon glyphicon-remove"></i></button>
                        <?php } ?>
                    </p>
                <?php } ?>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-md-4 control-label"><?php echo $this->translate("job_jobtitle_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-md-8">
                            <p class="form-control-static nullifempty view"><?php echo $job->getJobTitle(); ?></p>
                            <div class="edit">
                                <input type="text" class="form-control input-sm" id="jobtitle" name="jobtitle" value="<?php echo $job->getJobTitle(); ?>" />
                                <div id="jobtitle_error"></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 control-label"><?php echo $this->translate("job_hoursperweek_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-md-8">
                            <p class="form-control-static nullifempty view"><?php echo $job->gethoursperweek(); ?></p>
                            <div class="edit">
                                <input type="text" class="form-control input-sm width100 isdecimal" id="hoursperweek" name="hoursperweek" value="<?php echo $job->gethoursperweek(); ?>" />
                                <div id="hoursperweek_error"></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 control-label"><?php echo $this->translate("job_wage_label"); ?> <small>($)</small>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-md-8">
                            <p class="form-control-static nullifempty view"><?php echo '$'.$job->getRate().' '.getRateTypes($job->getRateType()); ?></p>
                            <div class="edit">
                                <input type="text" class="form-control input-sm width80 inline isdecimal" id="rate" name="rate" value="<?php echo $job->getRate(); ?>" />
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('ratetype',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $ratetypes),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm','width100','inline')
                                                        )
                                    );  
                                    $dropdown->setValue($job->getRateType()); 
                                    echo $dropdown->render();
                                ?><input type="hidden" class="form-control" name="ratetype_old" id="ratetype_old" value="<?php echo $job->getRateType(); ?>" />
                                <div id="rate_error"></div><div id="ratetype_error"></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 control-label"><?php echo $this->translate("job_startdate_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-md-8">
                            <p class="form-control-static nullifempty view"><?php echo formatDateAndTime($job->getStartDate(), false); ?></p>
                            <div class="edit">
                                <input type="text" class="form-control input-sm datefield startdate readonly width100" name="startdate" id="startdate" value="<?php echo changeMySQLDateToPageFormat($job->getStartDate()); ?>" /><div id="startdate_error"></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 control-label"><?php echo $this->translate("job_status_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-md-8">
                            <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($job->getStatus(), $jobstatuses) ? '' : $jobstatuses[$job->getStatus()]; ?></p>
                            <div class="edit">
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('status',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $jobstatuses),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm')
                                                        )
                                    );  
                                    $dropdown->setValue($job->getStatus()); 
                                    echo $dropdown->render();
                                ?><div id="status_error"></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 control-label"><?php echo $this->translate("job_enddate_label"); ?>:</label>
                        <div class="col-md-8">
                            <p class="form-control-static nullifempty view"><?php echo formatDateAndTime($job->getenddate(), false); ?></p>
                            <div class="edit">
                                <input type="text" class="form-control input-sm datefield readonly width100" name="enddate" id="enddate" value="<?php echo changeMySQLDateToPageFormat($job->getenddate()); ?>" /><input type="hidden" class="form-control" name="enddate_old" id="enddate_old" value="<?php echo $job->getenddate(); ?>" />
                                <div id="enddate_error"></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group complete">
                        <label class="col-md-4 control-label"><?php echo $this->translate("job_terminationtype_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-md-8">
                            <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($job->getTerminationType(), $terminationtypes) ? '': $terminationtypes[$job->getTerminationType()]; ?></p>
                            <div class="edit">
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('terminationtype',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $terminationtypes),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm')
                                                        )
                                    );  
                                    $dropdown->setValue($job->getTerminationType()); 
                                    echo $dropdown->render();
                                ?>
                                <input type="hidden" class="form-control" name="terminationtype_old" id="terminationtype_old" value="<?php echo $job->getterminationtype(); ?>" /><div id="terminationtype_error"></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group complete">
                        <label class="col-md-4 control-label"><?php echo $this->translate("job_terminationreason_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-md-8">
                            <p class="form-control-static nullifempty view"><?php echo $job->getTerminationReason(); ?></p>
                            <div class="edit">
                                <textarea class="form-control expanding" id="terminationreason" name="terminationreason"><?php echo $job->getTerminationReason(); ?></textarea>
                                <div id="terminationreason_error"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-md-4 control-label">Medical Type<?php //echo $this->translate("job_medicaltype_label"); ?>:</label>
                        <div class="col-md-6">
                            <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($job->getmedicaltype(), $medicaltypes) ? '' : $medicaltypes[$job->getmedicaltype()]; ?></p>
                            <div class="edit">
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('medicaltype',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $medicaltypes),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm')
                                                        )
                                    );  
                                    $dropdown->setValue($job->getmedicaltype()); 
                                    echo $dropdown->render();
                                ?><input type="hidden" class="form-control" name="medicaltype_old" id="medicaltype_old" value="<?php echo $job->getmedicaltype(); ?>" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 control-label"><?php echo $this->translate("job_medicalstartdate_label"); ?>:</label>
                        <div class="col-md-8">
                            <p class="form-control-static nullifempty view"><?php echo formatDateAndTime($job->getmedicalstartdate(), false); ?></p>
                            <div class="edit">
                                <input type="text" class="form-control input-sm datefield readonly width100" name="medicalstartdate" id="medicalstartdate" value="<?php echo changeMySQLDateToPageFormat($job->getmedicalstartdate()); ?>" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 control-label"><?php echo $this->translate("job_transport_label"); ?>:</label>
                        <div class="col-md-8">
                            <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($job->gettransportation(), $transportmodes) ? '' : $transportmodes[$job->gettransportation()]; ?></p>
                            <div class="edit">
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('transportation',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $transportmodes),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm')
                                                        )
                                    );  
                                    $dropdown->setValue($job->gettransportation()); 
                                    echo $dropdown->render();
                                ?><input type="hidden" class="form-control" name="transportation_old" id="transportation_old" value="<?php echo $job->gettransportation(); ?>" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 control-label"><?php echo $this->translate("job_workschedule_label"); ?>:</label>
                        <div class="col-md-8">
                            <p class="form-control-static nullifempty view"><?php echo $job->getworkschedule(); ?></p>
                            <div class="edit">
                                <input type="text" class="form-control input-sm" id="workschedule" name="workschedule" value="<?php echo $job->getworkschedule(); ?>" />
                                <div id="workschedule_error"></div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </fieldset>
            <!--<div class="divider10"></div>-->
            <fieldset class="fieldsetcontainer">
                <legend>Employer Details</legend>
                <div class="panel-body well-sm">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("job_company_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo $job->getEmployer()->getName(); ?></p>
                                <div class="edit">
                                    <input type="text" class="form-control input-sm" id="companyname" name="companyname" value="<?php echo $job->getEmployer()->getName(); ?>" />
                                    <div id="companyname_error"></div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("job_contactperson_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo $job->getEmployer()->getContactPerson(); ?></p>
                                <div class="edit">
                                    <input type="text" class="form-control input-sm" id="contactperson" name="contactperson" value="<?php echo $job->getEmployer()->getContactPerson(); ?>" />
                                    <div id="contactperson_error"></div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("job_contactphone_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo $job->getEmployer()->getPhone(); ?></p>
                                <div class="edit">
                                    <input type="text" class="form-control input-sm" id="phone" name="phone" value="<?php echo $job->getEmployer()->getPhone(); ?>" />
                                    <div id="phone_error"></div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("job_contactemail_label"); ?>:</label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo $job->getEmployer()->getEmail(); ?></p>
                                <div class="edit">
                                    <input type="text" class="form-control input-sm" id="email" name="email" value="<?php echo $job->getEmployer()->getEmail(); ?>" />
                                    <div id="email_error"></div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("job_supervisorname_label"); ?>:</label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo $job->getsupervisorname(); ?></p>
                                <div class="edit">
                                    <input type="text" class="form-control input-sm" id="supervisorname" name="supervisorname" value="<?php echo $job->getsupervisorname(); ?>" />
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("job_supervisorphone_label"); ?>:</label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo $job->getsupervisorphone(); ?></p>
                                <div class="edit">
                                    <input type="text" class="form-control input-sm" id="supervisorphone" name="supervisorphone" value="<?php echo $job->getsupervisorphone(); ?>" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                         <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("client_state_label"); ?>:</label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($job->getEmployer()->getState(), $states) ? '': $states[$job->getEmployer()->getState()]; ?></p>  
                                <div class="edit">
                                    <?php
                                        $dropdown = new Zend_Form_Element_Select('state',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $states),
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('form-control','input-sm','disabledfield')
                                                            )
                                        );  
                                        $dropdown->setValue($job->getEmployer()->getState()); 
                                        echo $dropdown->render();
                                    ?>
                                    <input type="hidden" class="form-control" name="state" id="state" value="<?php echo $job->getEmployer()->getState(); ?>" />
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("client_county_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($job->getEmployer()->getCounty(), $counties) ? '': $counties[$job->getEmployer()->getCounty()]; ?></p>  
                                <div class="edit">
                                    <?php
                                        $dropdown = new Zend_Form_Element_Select('county',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $counties),
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('form-control','input-sm',)
                                                            )
                                        );  
                                        $dropdown->setValue($job->getEmployer()->getCounty()); 
                                        echo $dropdown->render();
                                    ?><input type="hidden" class="form-control" name="county_old" id="county_old" value="<?php echo $job->getEmployer()->getCounty(); ?>" />
                                    <div id="county_error"></div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("client_city_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo $job->getEmployer()->getCity(); ?></p>
                                <div class="edit">
                                    <input type="text" class="form-control input-sm" id="city" name="city" value="<?php echo $job->getEmployer()->getCity(); ?>" />
                                    <div id="city_error"></div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("client_zipcode_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo $job->getEmployer()->getZipCode(); ?></p>
                                <div class="edit">
                                    <input type="text" class="form-control input-sm width100" id="zipcode" name="zipcode" value="<?php echo $job->getEmployer()->getZipCode(); ?>" />
                                    <div id="zipcode_error"></div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("client_addressline1_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo $job->getEmployer()->getAddressline1(); ?></p>
                                <div class="edit">
                                    <input type="text" class="form-control input-sm" id="addressline1" name="addressline1" value="<?php echo $job->getEmployer()->getAddressline1(); ?>" />
                                    <div id="addressline1_error"></div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("client_addressline2_label"); ?>:</label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo $job->getEmployer()->getAddressline2(); ?></p>
                                <div class="edit">
                                    <input type="text" class="form-control input-sm" id="addressline2" name="addressline2" value="<?php echo $job->getEmployer()->getAddressline2(); ?>" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
            <div class="row-fluid margin0">
                <div class="col-md-12 padding0 pull-right rightalign">
                    <?php if($step == 'edit' || $step == 'new'){ ?>
                        <p class="margin0 lineblocked">
                            <button type="submit" class="btn btn-success btn-sm button-submit save_trigger save" name="save"><i class="glyphicon glyphicon-ok"></i> <?php echo $step == 'new' ? $this->translate('global_button_save') : $this->translate('global_button_save_changes'); ?></button>
                        </p>
                        <p class="margin0 lineblocked">
                            <a class="btn btn-default btn-sm cancel cancel_trigger"><i class="glyphicon glyphicon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                        </p>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
        <?php if($job_count > 1 && isEmptyString($request->jobid)) { ?>
            <div class="divider5"></div>
            <div class="col-md-12 padding0">
                <table class="table table-condensed table-striped table-responsive viewtable">
                    <thead>
                        <tr>
                            <th class="centeralign" style="width:15px;">#</th>
                            <th>Job Title</th>
                            <th>Employer</th>
                            <th style="width:20%;">Duration</th>
                            <th style="width:15%;">Status</th>
                            <th style="width:15%;">Wage</th>
                        </tr>
                    </thead>
                    <tbody>
                       <?php 
                            $counter = 1;
                            foreach($jobs as $job){ 
                        ?>
                            <tr>
                                <td class="centeralign"><?php echo $counter; ?></td>
                                <td><a href="<?php echo $baseview.'/step/view/jobid/'.encode($job->getID()); ?>"><?php echo $job->getjobtitle(); ?></a></td>
                                <td><?php echo $job->getEmployer()->getName(); ?></td>
                                <td><?php echo $job->getDuration(); ?></td>
                                <td><?php echo isArrayKeyAnEmptyString($job->getStatus(), $jobstatuses) ? '' : $jobstatuses[$job->getStatus()]; ?></td>
                                <td><?php echo '$'.$job->getRate().' '.getRateTypes($job->getRateType()); ?></td>
                            </tr>
                        <?php $counter++; } ?>
                    </tbody>
                </table>
            </div>
        <?php } ?>
        	
    </div>
</form>