<div class="panel-body well-sm">
    <div class="form-group">
        <div class="col-md-12">
            <label class="col-md-12 control-label"><?php echo $this->translate('client_qualityoflife_label'); ?></label>
            <div class="col-md-12">
                <?php $lifequalities = getAllLifeQualityOptions(); ?>
                <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($client->getqualityoflife(), $lifequalities) ? '': $lifequalities[$client->getqualityoflife()]; ?></p>
                <?php if(($step == 'edit' && $section == 'assessment') || $step == 'new'){ ?>
                <div class="edit">
                   <?php 
                        foreach($lifequalities as $key => $value){
                    ?>
                        <label class="radio-inline notbolded">
                          <input type="radio" id="qualityoflife_<?php echo $key; ?>" name="qualityoflife" class="radiobutton disableoutsidesection" value="<?php echo $key; ?>" <?php echo $client->getqualityoflife() == $key && !isEmptyString($client->getqualityoflife()) ? 'checked data-waschecked="true"' : ''; ?>> <?php echo $value; ?>
                        </label>
                    <?php } ?>
                    <input type="hidden" name="qualityoflife_old" id="qualityoflife_old" value="<?php echo $client->getqualityoflife(); ?>" />
                </div>
                <?php } ?>
            </div> 
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-12">
            <label class="col-md-12 control-label"><?php echo $this->translate('client_oncallhousesupport_label'); ?>:</label>
            <div class="col-md-12">
                <p class="form-control-static nullifempty view"><?php echo $client->getoncallhousesupport_text(); ?></p>
                <?php if(($step == 'edit' && $section == 'assessment') || $step == 'new'){ ?>
                <div class="edit">
                    <label class="radio-inline">
                      <input type="radio" id="oncallhousesupport_1" name="oncallhousesupport" class="radiobutton disableoutsidesection" value="1" <?php echo $client->getoncallhousesupport() == 1 && !isEmptyString($client->getoncallhousesupport()) ? 'checked data-waschecked="true"' : ''; ?>>Yes
                    </label>
                    <label class="radio-inline">
                      <input type="radio" id="oncallhousesupport_0" name="oncallhousesupport" class="radiobutton disableoutsidesection" value="0" <?php echo $client->getoncallhousesupport() == 0 && !isEmptyString($client->getoncallhousesupport()) ? 'checked data-waschecked="true"' : ''; ?>>No
                    </label>
                    <input type="hidden" name="oncallhousesupport_old" id="oncallhousesupport_old" value="<?php echo $client->getoncallhousesupport(); ?>" />
                </div>
                <?php } ?>
            </div> 
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-6">
            <label class="col-md-12 control-label"><?php echo $this->translate('client_housing_label'); ?>:</label>
            <div class="col-md-12">
                <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($client->getHousing(), $housingtypes) ? '': $housingtypes[$client->getHousing()]; ?></p>
                <?php if(($step == 'edit' && $section == 'assessment') || $step == 'new'){ ?>
                <div class="edit">
                    <?php
                        $dropdown = new Zend_Form_Element_Select('housing',
                                            array(
                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $housingtypes, array('0'=>$this->translate("global_addvariable_label"))),
                                                'view' => new Zend_View(),
                                                'decorators' => array('ViewHelper'),
                                                'class' => array('form-control','input-sm','configvariable'),
												'lookupid' => 17,
												'fieldid' => 'housing',
												'fieldlabel' => $this->translate("client_housing_label")
                                            )
                        );  
                        $dropdown->setValue($client->getHousing()); 
                        echo $dropdown->render();
                    ?><input type="hidden" name="housing_old" id="housing_old" class="form-control" value="<?php echo $client->getHousing(); ?>" />
                </div>
                <?php } ?>
            </div>
        </div>
        <div class="col-md-6">
            <label class="col-md-12 control-label"><?php echo $this->translate('client_householdcount_label'); ?>:</label>
            <div class="col-md-12">
                <p class="form-control-static nullifempty view"><?php echo $client->gethouseholdcount(); ?></p>
                <?php if(($step == 'edit' && $section == 'assessment') || $step == 'new'){ ?>
                <div class="edit">
                    <input type="text" name="householdcount" id="householdcount" class="form-control width100" value="<?php echo $client->gethouseholdcount(); ?>" />
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-6">
            <label class="col-md-12 control-label"><?php echo $this->translate('client_partner_label'); ?>:</label>
            <div class="col-md-12">
                <p class="form-control-static nullifempty view"><?php echo $client->getpartnername(); ?></p>
                <?php if(($step == 'edit' && $section == 'assessment') || $step == 'new'){ ?>
                <div class="edit">
                    <input type="text" name="partnername" id="partnername" class="form-control" value="<?php echo $client->getpartnername(); ?>" />
                </div>
                <?php } ?>
            </div> 
        </div>
        <div class="col-md-6">
            <label class="col-md-12 control-label"><?php echo $this->translate('client_rshipyears_label'); ?>:</label>
            <div class="col-md-12">
                <p class="form-control-static nullifempty view"><?php echo $client->getyearsinrship(); ?></p>
                <?php if(($step == 'edit' && $section == 'assessment') || $step == 'new'){ ?>
                <div class="edit">
                    <input type="text" name="yearsinrship" id="yearsinrship" class="form-control width100" value="<?php echo $client->getyearsinrship(); ?>" />
                </div>
                <?php } ?>
            </div> 
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-12">
            <label class="col-md-12 control-label"><?php echo $this->translate('client_householdmembers_label'); ?>:</label>
            <div class="col-md-12">
                <p class="form-control-static nullifempty view">
                    <table class="table table-condensed table-bordered table-striped table-responsive viewtable" style="margin-bottom:10px;">
                        <thead>
                            <tr>
                                <th class="centeralign" style="width:15px;">#</th>
                                <th>Name of Person</th>
                                <th style="width:20%;">Age</th>
                                <th>Current Relationship</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php 
                                $familymembers = $client->getAssessmentDetails(2);												
                                $count_familymembers = $familymembers->count();
                            ?>
                            <?php if($count_familymembers == 0){ ?>
                                <tr>
                                    <td></td>
                                    <td>--</td>
                                    <td>--</td>
                                    <td>--</td>
                                </tr>
                            <?php } else { ?>
                                <?php 
                                    $counter = 1;
                                    foreach($familymembers as $member){
                                ?>
                                <tr>
                                    <td class="centeralign"><?php echo $counter; ?></td>
                                    <td><?php echo $member->getValue1(); ?></td>
                                    <td><?php echo $member->getValue2(); ?></td>
                                    <td><?php echo isArrayKeyAnEmptyString($member->getValue3(), $rships) ? '' : $rships[$member->getValue3()]; ?></td>
                                </tr>
                                <?php $counter++; } ?>
                            <?php } ?>
                        </tbody>
                    </table>
                </p>
                <?php if(($step == 'edit' && $section == 'assessment') || $step == 'new'){ ?>
                <div class="edit">
                    <table class="table table-condensed table-striped table-responsive viewtable" style="margin-bottom:10px;">
                        <thead>
                            <tr>
                                <th class="centeralign" style="width:15px;">#</th>
                                <th>Name of Person</th>
                                <th style="width:20%;">Age</th>
                                <th>Current Relationship</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php 
                                $counter = 1;
                                $nooflines = $count_familymembers;
                                $e = 0; $x = 0;
                                foreach($familymembers as $member){
                                     $class = "visible_row_family";
                            ?>
                                <tr class="<?php echo $class; ?> row_family_<?php echo $e; ?>" id="row_family_<?php echo $e; ?>">
                                    <td class="centeralign"><a href="javascript: doNothing();" title="<?php echo $this->translate("global_button_remove"); ?>" id="row_family_<?php echo $e; ?>" class="removeline btn btn-xs btn-default" rel="family">&times;</a>
                                    <input type="hidden" id="familydetails_id_<?php echo $e; ?>" class="form-control" name="familydetails[<?php echo md5($e); ?>][id]" value="<?php echo $member->getID(); ?>" /></td>
                                    <td><input type="text" class="form-control input-sm" name="familydetails[<?php echo md5($e); ?>][value1]" id="familydetails_value1_<?php echo $e; ?>" value="<?php echo $member->getValue1(); ?>" /></td>
                                    <td><input type="text" class="form-control input-sm" name="familydetails[<?php echo md5($e); ?>][value2]" id="familydetails_value2_<?php echo $e; ?>" value="<?php echo $member->getValue2(); ?>" /></td>
                                    <td><?php
											$dropdown = new Zend_Form_Element_Select('familydetails_value3_'.md5($e),
																array(
																	'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $rships, array('0'=>$this->translate("global_addvariable_label"))),
																	'view' => new Zend_View(),
																	'decorators' => array('ViewHelper'),
																	'class' => array('form-control','input-sm','configvariable','relationships'),
																	'lookupid' => 25,
																	'fieldid' => 'familydetails_value3_'.md5($e),
																	'fieldlabel' => 'Relationship Options',
																	'appendclass' => 'relationships'
																)
											);  
											$dropdown->setValue($member->getValue3()); 
											echo $dropdown->render();
										?>
                                    </td>
                                </tr>
                            <?php $e++; $x++; $counter++; } ?>
                            <?php 
                                $defaultlines = 3;
                                if($nooflines >= 3){
                                    $defaultlines = $nooflines + 1;
                                }
                                for($i = $e; $i<10; $i++){
                                    // debugMessage($i);
                                    $class = "visible_row_family";
									if($i >= $defaultlines){
										$class = "hidden_row_family";
									}
								
							?>
								<tr class="<?php echo $class; ?> row_family_<?php echo $i; ?>" id="row_family_<?php echo $i; ?>">
									<td class="centeralign"><a href="javascript: doNothing();" title="<?php echo $this->translate("global_button_remove"); ?>" id="row_family_<?php echo $i; ?>" class="removeline btn btn-xs btn-default" rel="family">&times;</a></td>
									<td><input type="text" class="form-control input-sm" name="familydetails[<?php echo md5($i); ?>][value1]" id="familydetails_value1_<?php echo $i; ?>" /></td>
									<td><input type="text" class="form-control input-sm" name="familydetails[<?php echo md5($i); ?>][value2]" id="familydetails_value2_<?php echo $i; ?>" /></td>
									<td>
                                    	<?php
											$dropdown = new Zend_Form_Element_Select('familydetails_value3_'.md5($i),
																array(
																	'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $rships, array('0'=>$this->translate("global_addvariable_label"))),
																	'view' => new Zend_View(),
																	'decorators' => array('ViewHelper'),
																	'class' => array('form-control','input-sm','configvariable','relationships'),
																	'lookupid' => 25,
																	'fieldid' => 'familydetails_value3_'.md5($i),
																	'fieldlabel' => 'Relationship Options',
																	'appendclass' => 'relationships'
																)
											);  
											$dropdown->setValue(''); 
											echo $dropdown->render();
											
											// debugMessage($datavalues);
										?>
								</tr>
							<?php $x++; } ?>
							<tr>
								<td></td>
								<td><a href="javascript: void(0)" title="Add another" class="addline btn btn-primary btn-xs pull-left" id="family">Add Row</a></td>
								<td colspan="4"></td>
							</tr>
						</tbody>
					</table>
				</div>
                <?php } ?>
			</div> 
		</div>
	</div>
</div>