<?php
	require_once APPLICATION_PATH.'/includes/header.php';
		
	$title = "New Client";
	$description = '';
	
	$this->headTitle($title.$browserappend);
?>
<script>
	$(document).ready(function() {
		$('.titlebreadcrumb').html('<?php echo 'Dashboard / '.$role; ?>');
		$('.titlelabel').html('<?php echo 'Dashboard'; ?>');
		$('.desclabel').html('<?php echo $description; ?>');
		$('.pageicon').html('<span class="glyphicon glyphicon-list-alt"></span>');
		
	});
</script>

<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
