<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$client = new Client();
    $client->populate(decode($request->id));
	$id = $client->getID();
	// debugMessage($client->toArray());
	
	$posturl = $this->baseUrl("client/create"); 
	$successmessage = $this->translate('profile_add_success');
	
	$tab = 'profile'; $request->setParam('tab', 'profile'); 
	$tabtitle = 'Profile';

	$section = $request->section;
	$step = 'new';
	if($tab == 'profile'){
		// dropdown data
		$maritalstatuses = getAllMaritalStatuses();
		$educationlevels = getEducationLevels();
		$races = getAllRaces();
		$programs = getPrograms();
		$funders = getFunders();
		$services = getServiceTypes();
		$disabilitycodes = getDisabilityDiagnosisCodes(''); $disabilitycodes_notaliased = getDisabilityDiagnosisCodes('', false);
		$causecodes = getDisabilityCauseCodes(); $causecodes_notaliased = getDisabilityCauseCodes('', false);
		$communicationtypes = getCommunicationLevels();
		$housingtypes = getHousingTypes();
		$transportmodes = getTransportationModes();
		$skills = getAllClientSkills();
		$states = getStates();
		$counties = getAllCounties();
		$ratetypes = getRateTypes();
		$incomesources = getAllIncomeSources();
		$rships = getAllRelationshipOptions();
	}
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$client->processPost($session->getVar(FORM_VALUES));
	}
	
	$title = 'New Client';
	$description = 'Complete the 5 Steps below to Setup a New Client. Fields marked with '.$this->translate("global_required_field_marker").' are mandatory.';	
	$this->headTitle($title.$browserappend);
?>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/jquery.stepy.js')); ?>"></script>
<script>
	$(document).ready(function() {
		$('.titlebreadcrumb').html('<?php echo $homedir.'Clients / New Client'; ?>');
		$('.titlelabel').html('<?php echo $title; ?>');
		$('.desclabel').html('<?php echo $description; ?>');
		$('.pageicon').html('<span class="glyphicon glyphicon-list-alt"></span>');
		
		var tab = '<?php echo $tab; ?>';
		
		$('.edit, .requiredmark').removeClass('hidden').show();
		$('.view, .update_trigger').addClass('hidden').hide();
		
		// form wizard
		/**/
		$('#indexform').stepy({
			block: true,
			validate: true,
			errorImage:	false,
			titleClick:	true,
			backLabel: '<span class="glyphicon glyphicon-arrow-left"></span> Back',
			nextLabel: 'Next <span class="glyphicon glyphicon-arrow-right"></span>',
			next: function(index) {
				
			},
			finish: function() {
				if ($("#indexform").valid()) {
					$.blockUI({ message: '<?php echo $blockcontent; ?>' }); 
				}
			}
		});
		
		$(".button-back").addClass('btn btn-default btn-lg');
		$(".button-next").addClass('btn btn-primary btn-lg'); 
		$(".finish").html('').prepend('<span class="glyphicon glyphicon-ok"></span> Finish').addClass('btn btn-success btn-lg');
		$(".step legend").hide();
		
		// validation 
		$("#indexform").validate({		
			<?php require APPLICATION_PATH."/views/scripts/client/validation.phtml"; ?>
		});
		
		// custom date picker options
		var dateofbirthOpts = datepickerOpts;
		var startfrom = '<?php echo date('Y'); ?>';
		dateofbirthOpts.yearRange = "-<?php echo date('Y')-1900; ?>:-0"; 
		dateofbirthOpts.minDate = "-<?php echo date('Y'); ?>Y";
		datepickerOpts.maxDate = new Date("Dec 31, "+startfrom);	
		$("#dateofbirth").datepicker(dateofbirthOpts);
		
		dateofbirthOpts.yearRange = "-<?php echo date('Y')-2010; ?>:-0"; 
		// datepickerOpts.maxDate = new Date();
		// $("#dateapproved, #referraldate, #assessmentdate, #startdate, #enddate, #invoicedate, #medicalstartdate, #activitydate, #dateavailable").datepicker(dateofbirthOpts);
		$(".datefield").datepicker(dateofbirthOpts);
		
		// add filename of selected file in background of input to indicate that a file has been selected.
		$("#resumefilename").change(function(){
			if(!isEmptyString($(this).val())){
				$("#beforesave_resume .fileinput-preview").html($(this).val());
			}
		});
		$("#coverletterfilename").change(function(){
			if(!isEmptyString($(this).val())){
				$("#beforesave_cover .fileinput-preview").html($(this).val());
			}
		});
		
		$(".computeamount").keyup(function(){
			var rate = parseFloat($("#rate").val());
			var hours = parseFloat($("#hours").val());
			// alert(rate); alert(hours);
			$("#amount_computed").html(rate*hours);
		});
		$(".computeamount").trigger("keyup");
		
		$(".chosen-container.chosen-container-single").css({'width':'100%'});
	});
	
</script>
<style>
#center {
	float:left;
}
</style>
<div class="row-fluid margin0">
    <?php if ($sessionhaserror) { ?>
        <div class="alert alert-danger"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
    <?php } ?>
    <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
        <div class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
    <?php } ?>
    <div id="tabs" class="clearfix" style="min-height:500px;">
        <?php // require APPLICATION_PATH."/views/scripts/client/leftcolumn.phtml"; ?>
        <div class="col-md-12 tab-content clearfix" id="center" style="width:100%;">
        	<h4 id="tabtitle"></h4>
        	<div id="profile">
                <form id="indexform" class="form-horizontal profile" role="form" action="<?php echo $posturl; ?>" method="post" enctype="multipart/form-data">
  					<input type="hidden" id="entityname" name="entityname" value="Client" />
                    <input type="hidden" id="id" name="id" value="" />
                    <input type="hidden" class="successurl" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" value="" />
                    <input type="hidden" class="failureurl" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" value="" />
                    <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $successmessage; ?>" />
                    <input type="hidden" id="status" name="status" value="1" />
					
                    <fieldset title="Bio Data" id="account">
                        <legend>Step 1</legend>
                        <?php require APPLICATION_PATH."/views/scripts/client/bio.phtml"; ?>
                    </fieldset>
                    <fieldset title="Referral Information">
                        <legend>Step 2</legend>
                        <?php require APPLICATION_PATH."/views/scripts/client/referral.phtml"; ?>
                    </fieldset>
                    <fieldset title="Intake Assessment">
                        <legend>Step 3</legend>
                        <fieldset class="fieldsetcontainer">
                            <legend>Intake Assessment</legend>
                            <div class="panel-body well-sm">
                                <div class="divider5"></div>
                                
                                <div class="panel-group" id="inneraccordion">
                                    <div class="panel panel-default" id="assess1">
                                        <div class="panel-heading">
                                            <h4 class="panel-title"><a class="accordion-toggle dark" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col1"> Resume and Attachments</a> </h4>
                                        </div>
                                        <div id="collapse_col1" class="panel-collapse collapse in">
                                            <?php require APPLICATION_PATH."/views/scripts/client/attachment.phtml"; ?>
                                        </div>
                                    </div>
                                    <?php // if(false){ ?>
                                    <div class="panel panel-default" id="assess2">
                                        <div class="panel-heading">
                                            <h4 class="panel-title"><a class="accordion-toggle dark" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col2"> Medical Information</a> </h4>
                                        </div>
                                        <div id="collapse_col2" class="panel-collapse collapse in">
                                            <div class="panel-body">
                                                <?php require APPLICATION_PATH."/views/scripts/client/medical.phtml"; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <?php // } ?>
                                    <div class="panel panel-default" id="assess3">
                                        <div class="panel-heading">
                                            <h4 class="panel-title"><a class="accordion-toggle dark collapsed" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col3"> Family and Living</a> </h4>
                                        </div>
                                        <div id="collapse_col3" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <?php require APPLICATION_PATH."/views/scripts/client/family.phtml"; ?> 
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <?php // if(false){ ?>
                                    <div class="panel panel-default" id="assess4">
                                        <div class="panel-heading">
                                            <h4 class="panel-title"><a class="accordion-toggle dark collapsed" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col4"> Employment Preferrences</a> </h4>
                                        </div>
                                        <div id="collapse_col4" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <?php require APPLICATION_PATH."/views/scripts/client/jobpreferance.phtml"; ?> 
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default" id="assess5">
                                        <div class="panel-heading">
                                            <h4 class="panel-title"><a class="accordion-toggle dark collapsed" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col5"> Employment History</a> </h4>
                                        </div>
                                        <div id="collapse_col5" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <?php require APPLICATION_PATH."/views/scripts/client/jobhistory.phtml"; ?>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default" id="assess6">
                                        <div class="panel-heading">
                                            <h4 class="panel-title"><a class="accordion-toggle dark collapsed" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col6"> Education Background</a> </h4>
                                        </div>
                                        <div id="collapse_col6" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <div class="panel-body well-sm">
                                                    <?php require APPLICATION_PATH."/views/scripts/client/education.phtml"; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default" id="assess7">
                                        <div class="panel-heading">
                                            <h4 class="panel-title"><a class="accordion-toggle dark collapsed" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col7"> References</a> </h4>
                                        </div>
                                        <div id="collapse_col7" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <div class="panel-body well-sm">
                                                    <?php require APPLICATION_PATH."/views/scripts/client/references.phtml"; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel panel-default" id="assess8">
                                        <div class="panel-heading">
                                            <h4 class="panel-title"><a class="accordion-toggle dark collapsed" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col8"> Legal Information</a> </h4>
                                        </div>
                                        <div id="collapse_col8" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <?php require APPLICATION_PATH."/views/scripts/client/legal.phtml"; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel panel-default" id="assess9">
                                        <div class="panel-heading">
                                            <h4 class="panel-title"><a class="accordion-toggle dark" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col9"> Military Service</a> </h4>
                                        </div>
                                        <div id="collapse_col9" class="panel-collapse collapse collapsed">
                                            <div class="panel-body">
                                                <?php require APPLICATION_PATH."/views/scripts/client/military.phtml"; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel panel-default" id="assess10">
                                        <div class="panel-heading">
                                            <h4 class="panel-title"><a class="accordion-toggle dark collapsed" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col10"> Cultural and Social Information</a> </h4>
                                        </div>
                                        <div id="collapse_col10" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <?php require APPLICATION_PATH."/views/scripts/client/social.phtml"; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel panel-default" id="assess11">
                                        <div class="panel-heading">
                                            <h4 class="panel-title"><a class="accordion-toggle dark collapsed" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col11"> Personal Health and Safety Assessment</a> </h4>
                                        </div>
                                        <div id="collapse_col11" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <div class="panel-body well-sm">
                                                    <?php require APPLICATION_PATH."/views/scripts/client/qnassessment.phtml"; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <?php // } ?>
                                </div>
                            </div>
                        </fieldset>
                    </fieldset>
                    <fieldset title="Emergency Information">
                        <legend>Step 4</legend>
                    	<fieldset class="fieldsetcontainer">
                            <legend>Emergency Information</legend>
                            <div class="panel-body well-sm">
                                <?php require APPLICATION_PATH."/views/scripts/client/emergency.phtml"; ?>
                            </div>
                        </fieldset>
                        <div class="divider10"></div>
                    </fieldset>
                    <fieldset title="Assign to User">
                        <legend>Step 5</legend>
                        <?php //if(false){ ?>
                    	<fieldset class="fieldsetcontainer">
                            <legend>Job Coach</legend>
                            <div class="panel-body well-sm">
                            	<div class="col-md-6"><small><em>Select the Coach assigned to this Client.</em></small></div>
                                <div class="divider10"></div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="col-sm-5 control-label"><?php echo $this->translate("client_userid_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                        <div class="col-sm-7">
                                        	<?php
												$allvalues = getUsers(2, '', 1);
												$dropdown = new Zend_Form_Element_Select('userid',
																	array(
																		'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues),
																		'view' => new Zend_View(),
																		'decorators' => array('ViewHelper'),
																		'class' => array('form-control','input-sm'),
																	)
												);  
												$dropdown->setValue(''); 
												echo $dropdown->render();
											?>
                                            <div id="userid_error"></div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                         <label class="col-sm-5 control-label"><?php echo $this->translate("client_assign_startdate_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                        <div class="col-sm-7">
                                            <input type="text" class="form-control input-sm datefield readonly width100" name="assignstartdate" id="assignstartdate" value="" /><div id="assignstartdate_error"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                </div>
                            </div>
                        </fieldset>
                        <?php //} ?>
                        <div class="divider10"></div>
                    </fieldset>
                    <button type="submit" class="btn btn-primary finish" id="complete"><i class="glyphicon glyphicon-arrow-right"></i> Complete</button>
                </form>
			</div> 
     	</div> 
    </div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
