<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$startdate = $request->startdate;
	$enddate = $request->enddate;
	if(!isEmptyString($startdate)){
		$startdate = changeDateFromPageToMySQLFormat($startdate);
		$allowclear = true;
	}
	$enddate = $request->getParam('enddate');
	if(!isEmptyString($enddate)){
		$enddate = changeDateFromPageToMySQLFormat($enddate);
		$allowclear = true;
	}
	
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("c.firstname","c.lastname","c.email","c.home","c.work","c.cell","c.ssn"));
	$paginate->setFilterColumns(array());
	$paginate->setItemCountPerPage("10");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE c.id <> '' ";
	$allowclear = false;
	
	if(!isEmptyString($startdate)){
		$where_query .= " AND (TO_DAYS(c.startdate) >= TO_DAYS('".$startdate."')) ";
	}
	if(!isEmptyString($enddate)){
		$where_query .= " AND (TO_DAYS(c.startdate) <= TO_DAYS('".$enddate."')) ";
	}
		
	if(!isEmptyString($request->letter)){
		$where_query .= " AND (c.`firstname` LIKE '".$request->letter."%' OR c.`lastname` LIKE '".$request->letter."%') ";
		$allowclear = true;
	}
	
	if(!isEmptyString($request->searchterm)){
		$allowclear = true;
	}
	
	$program = $request->programid;
	if(!isEmptyString($program)){
		$where_query .= " AND (c.programid = ".$program.") ";
	}
	
	$status = $request->status;
	if(!isEmptyString($status)){
		$where_query .= " AND (cs.status = ".$status.") ";
		$allowclear = true;
	}
	
	$order = trim($request->order);
	$order_query = " ";
	if(isEmptyString($order)){
		$order = 1;
	}
	if($order == 1){
		$order_query = " ORDER BY c.datecreated DESC ";
	}
	if($order == 2){
		$order_query = " ORDER BY c.datecreated ASC ";
	}
	if($order == 3){
		$order_query = " ORDER BY c.firstname ASC ";
	}
	if($order == 4){
		$order_query = " ORDER BY c.lastname ASC ";
	}
	
	$sortcolumn = $request->sortby;
	$sortorder = $request->sortorder;
	if(!isEmptyString($sortcolumn) && !isEmptyString($sortorder)){
		$order_query = " ORDER BY " . $sortcolumn. " " .$sortorder. " ";
	}
	// f.orgname as fundername, concat(u.firstname,' ',u.lastname) as supervisorname
	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT 
		c.id as cid, c.coachid as coachid, c.firstname, c.lastname, c.ssn, concat(c.firstname,' ',c.lastname) as client, concat(u.firstname,' ',u.lastname) as coach,
		c.home, c.cell, 
		c.profilephoto, c.gender,
		c.city, c.addressline1, c.addressline2, c.country, c.county, c.city, c.state, c.zipcode, 
		c.programid as programid, c.funderid,  
		c.startdate, c.status as currentstatus
	 FROM client c 
	 left join `voucher` as v on (c.initialvoucherid = v.id)
	 left join useraccount as u on (c.coachid = u.id)
	 ".$where_query." ".$paginate->getSearchAndFilterSQL()." GROUP BY c.id ".$order_query;
	
	// debugMessage($all_results_query); // exit;
	$paginate->setItemCountFromSQLQuery($all_results_query);
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false;
	
	$listurl = $this->baseUrl('client/list');
	$addurl = $this->baseUrl('client');
	$title = $this->translate("client_list_title");
	$listitems = "Clients";
		
	$title = "Clients";
	$moduleitem = "Client";
	$description = '';
	$icon = $this->baseUrl('images/icon_home.png');
	
	$programs = getPrograms(); // debugMessage($programs);
	$funders = getFunders();
	
	$this->headTitle($title.$browserappend);
?>
<script>
	$(document).ready(function() {
		$('.titlebreadcrumb').html('<?php echo $homedir.$title; ?>');
		$('.titlelabel').html('<?php echo $title; ?>');
		$('.desclabel').html('<?php echo $description; ?>');
		$('.pageicon').html('<span class="glyphicon glyphicon-list-alt"></span>');
		
		var dateofbirthOpts = datepickerOpts;
		var startfrom = '<?php echo date('Y'); ?>';
		dateofbirthOpts.yearRange = "-<?php echo date('Y')-2010; ?>:-0"; 
		dateofbirthOpts.minDate = "-<?php echo date('Y'); ?>Y";
		datepickerOpts.maxDate = new Date("Dec 31, "+startfrom);	
		$("#startdate, #enddate").datepicker(dateofbirthOpts);
		
	});
</script>
<div class="row margin0">
    <div class="col-md-12 padding0">
    <form class="form margin0 listform" action="<?php echo $this->baseUrl("client/listsearch"); ?>" method="get" id="listform">
		<?php if ($sessionhaserror) { ?>
            <div class="alert alert-danger"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
        <?php } ?>
        <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
            <div class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
        <?php } ?>
        <div class="row-fluid clearfix">
        	<div class="col-md-9 paddingleft0">
            	<ul class="listfilter">
					<?php if ($acl->checkPermission('Client', ACTION_CREATE)) { ?>
                        <li><a title="New <?php echo $moduleitem; ?>" class="btn btn-primary btn-sm blockanchor" href="<?php echo $addurl; ?>"><i class="glyphicon glyphicon-plus"></i> New <?php echo $moduleitem; ?></a></li>
                    <?php } ?>
                    <li>
                        <?php
                            $dropdown = new Zend_Form_Element_Select('programid',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => 'All Programs'), $programs),
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array("autofilter", "form-control", 'chosen-select', 'width150')
                                    )
                            );  
                            $dropdown->setValue($request->getParam('programid')); 
                            echo $dropdown->render();
                        ?>
                    </li>
                    <li>
                        <?php
                            $dropdown = new Zend_Form_Element_Select('status',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => 'All Statuses'), array('1'=>'Open', '0'=>'Closed')),
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array("autofilter", "form-control", 'chosen-select', 'width150')
                                    )
                            );  
                            $dropdown->setValue($request->getParam('status')); 
                            echo $dropdown->render();
                        ?>
                    </li>
                    <li>
						<?php
                            $allorders = array('1' => 'Latest First', '2'=>'Earliest First', '3'=>'Order By First Name','4'=>'Order By Last Name');
                            $ordersdropdown = new Zend_Form_Element_Select('order',
                                                array(
                                                    'multiOptions' => $allorders,
                                                    'view' => new Zend_View(),
                                                    'decorators' => array('ViewHelper'),
                                                   'class' => array("autofilter", "form-control", 'width150', 'chosen-select')
                                                )
                            );  
                            $ordersdropdown->setValue($request->getParam('order')); 
                            echo $ordersdropdown->render();
                        ?>
                    </li>
                </ul>
                <ul class="listfilter">
                    <li><input type="text" name="startdate" id="startdate" class="form-control input-sm datefield readonly width100" value="<?php echo $request->startdate; ?>" placeholder="From:" /></li>
                    <li><input name="enddate" id="enddate" type="text" class="form-control input-sm datefield readonly width100" placeholder="To:" value="<?php echo $request->enddate; ?>" /></li>
                    <li><button type="submit" class="btn btn-default btn-sm blockanchor"><i class="glyphicon glyphicon-filter"></i> Filter</button></li>
               	</ul>
            </div>
            <div class="col-md-3 padding0">
            	<div class="col-md-12 padding0"><input name="searchterm" id="searchterm" class="form-control form-search" value="<?php echo $request->searchterm; ?>" type="text" placeholder="Search..." /><button type="submit" class="btn btn-default blockanchor searchbtn"><i class="glyphicon glyphicon-search"></i></button></div>
            	<input type="hidden" name="letter" id="letter" value="<?php echo $request->getParam('letter'); ?>" />
                <?php if($allowclear){ ?>
                    <a href="<?php echo $listurl; ?>" title="Clear Search and Filters" class="reset close button btn resetlink blockanchor">&times;</a>
                <?php } ?>
            </div>
        </div>
        <?php echo $paginate->getAlphabetString(); ?>
		<?php if ($has_no_data) { ?>
            <div class="divider30"></div>
            <div style="clear:both;" class="alert alert-warning margin5"><?php echo $this->translate("global_list_noentries"); ?></div>
        <?php } else { ?>
        	<div class="row-fluid peoplelist clearfix">
            	<div class="divider10"></div>
            	<?php
					$counter = 1; 				  		
					foreach($result as $line){
						$id = $line['cid'];	
						$phone = $line['cell']; $phone2 = $line['home'];
						$addressline1 = $line['addressline1']; 
						$addressline1 = $line['addressline2'];
						
						$hasprofileimage = false;
						$real_path = BASE_PATH.DIRECTORY_SEPARATOR."uploads".DIRECTORY_SEPARATOR."clients".DIRECTORY_SEPARATOR."client_".$id.DIRECTORY_SEPARATOR."avatar".DIRECTORY_SEPARATOR."medium_".$line['profilephoto'];
						if(file_exists($real_path) && !isEmptyString($line['profilephoto'])){
							$hasprofileimage = true;
						}
						$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
						$photo_path = $baseUrl.'/uploads/default/default_medium_male.jpg';
						
						if($line['gender'] == 2){
							$photo_path = $baseUrl.'/uploads/default/default_thumbnail_female.jpg'; 
						}
						if($hasprofileimage){
							$photo_path = $baseUrl.'/uploads/clients/client_'.$id.'/avatar/medium_'.$line['profilephoto'];
						}
						
						$viewurl = $this->baseUrl('client/view/id/'.encode($id));
						$coachlink = '--';
						if(!isEmptyString($line['coachid'])){
							$coachlink = '<a href="'.$this->baseUrl('profile/view/id/'.encode($line['coachid'])).'">'.$line['coach'].'</a>';
						}
						
						$statustext = ''; $statusclass = 'bg-default';
						if($line['currentstatus'] == 0){
							$statusclass = 'bg-warning text-warning'; 
							$statustext = 'Closed';
						}
						if($line['currentstatus'] == 1){
							$statusclass = 'bg-success text-success'; 
							$statustext = 'Open';
						}
					?>
                    	 <div class="col-xs-12 col-sm-6 xpaddingleft0">
                            <div class="peoplewrapper">
                                <div class="thumb img-thumbnail">
                                	<a href="<?php echo $viewurl; ?>"><img class="imagecontainer" src="<?php echo $photo_path; ?>" /></a>
                                    <p class="centeralign <?php echo $statusclass; ?> margin0"><small><?php echo $statustext; ?></small></p>
                                </div>
                                <div class="peopleinfo">
                                    <h4><a href="<?php echo $viewurl; ?>"><?php echo $line['client']; ?></a></h4>
                                    <div class="row-fluid margin0">
                                    	<div class="col-md-7 padding0">
                                        	<ul>
                                                <li><span class="bolded">SSN:</span> <?php echo $line['ssn']; ?></li>
                                                <li><span class="bolded">Program:</span> <?php echo isArrayKeyAnEmptyString($line['programid'], $programs) ? '--' : $programs[$line['programid']]; ?></li> 
                                                <li><span class="bolded">Funder:</span> <?php echo isArrayKeyAnEmptyString($line['funderid'], $funders) ? '--' : snippet($funders[$line['funderid']], 50, '...'); ?></li>
                                                <li><span class="bolded">Coach:</span> <?php echo $coachlink; ?></li>
                                                <li><span class="bolded">Start Date:</span> <?php echo formatDateAndTime($line['startdate'], false); ?></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-5 padding0">
                                            <ul>
                                            	<li><span class="bolded">Contact</span></li>
                                                <li><?php echo $line['cell']; ?></li>
                                                <li><?php echo $line['addressline1']; ?></li>
                                                <li><?php echo $line['city'].' '.$line['state'].' '.$line['zipcode']; ?></li>
                                            </ul>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                   <?php } ?> 
            </div>
            <div class="row-fluid">
                <div class="table-footer">
                    <div class="col-md-6 padding0" style="margin-bottom:10px;">
                        <div class="table-actions">
                            <div class="row col-md-12 margin0 padding0 clearfix">
                                <div class="col-md-6 padding0 floatleft"><?php echo $paginate->getListCountDropDown(); ?></div>
                                <div class="col-md-6 paddingleft5 rightalign" style="margin-bottom:5px;"><?php echo sprintf($this->translate("global_list_counter"), $paginate->getItemCounterText()); ?></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 padding0">
                        <?php echo $paginate->getPaginationLinks(); ?>
                    </div>
                </div>
            </div>
        <?php } ?>
                                                                      
	</form>
</div>            
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
