<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("c.firstname","c.lastname","c.email","c.home","c.work","c.cell","c.ssn"));
	$paginate->setFilterColumns(array());
	$paginate->setItemCountPerPage("10");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE c.id <> '' ";
	$allowclear = false;
	
	if(!isEmptyString($request->letter)){
		$where_query .= " AND (c.`firstname` LIKE '".$request->letter."%' OR c.`lastname` LIKE '".$request->letter."%') ";
		$allowclear = true;
	}
	
	if(!isEmptyString($request->searchterm)){
		$allowclear = true;
	}
	
	$order = trim($request->order);
	$order_query = " ";
	if(isEmptyString($order)){
		$order = 1;
		$request->setParam('order', $order);
	}
	if($order == 1){
		$order_query = " ORDER BY c.datecreated DESC ";
	}
	if($order == 2){
		$order_query = " ORDER BY c.datecreated ASC ";
	}
	
	$sortcolumn = $request->sortby;
	$sortorder = $request->sortorder;
	if(!isEmptyString($sortcolumn) && !isEmptyString($sortorder)){
		$order_query = " ORDER BY " . $sortcolumn. " " .$sortorder. " ";
	}
	// f.orgname as fundername, concat(u.firstname,' ',u.lastname) as supervisorname
	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT 
		c.id as id, c.firstname, c.lastname, c.ssn,
		c.home, c.cell, 
		c.profilephoto, c.gender,
		c.city, c.addressline1, c.addressline2, c.country, c.county, c.city, c.state, c.zipcode, 
		c.program, cs.program as csprogram, cs.funderid,  
		cs.startdate, cs.status,
		cs.supervisorid as coachid
	 FROM client c 
	 left join `case` as cs on (c.id = cs.clientid)
	 ".$where_query." ".$paginate->getSearchAndFilterSQL()." GROUP BY c.id ".$order_query;
	
	// debugMessage($all_results_query); exit;
	$paginate->setItemCountFromSQLQuery($all_results_query);
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false;
	
	$listurl = $this->baseUrl('client/list');
	$addurl = $this->baseUrl('client');
	$title = $this->translate("client_list_title");
	$listitems = "Clients";
		
	$title = "Clients";
	$moduleitem = "Client";
	$description = 'ENT Consumers (description goes here)';
	$icon = $this->baseUrl('images/icon_home.png');
	
	$programs = getPrograms(); // debugMessage($programs);
	$funders = getFunders();
	
	$this->headTitle($title.$browserappend);
?>
<script>
	$(document).ready(function() {
		$('.titlebreadcrumb').html('<?php echo $homedir.$title; ?>');
		$('.titlelabel').html('<?php echo $title; ?>');
		$('.desclabel').html('<?php echo $description; ?>');
		$('.pageicon').html('<span class="glyphicon glyphicon-list-alt"></span>');
		
	});
</script>
<div class="row margin0">
    <div class="col-md-12 padding0">
    <form class="form margin0 listform" action="<?php echo $this->baseUrl("client/listsearch"); ?>" method="get" id="listform">
		<?php if ($sessionhaserror) { ?>
            <div class="alert alert-danger"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
        <?php } ?>
        <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
            <div class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
        <?php } ?>
        <div class="row-fluid clearfix">
        	<div class="col-md-9 paddingleft0">
            	<ul class="listfilter">
					<?php if ($acl->checkPermission('Client', ACTION_CREATE)) { ?>
                        <li><a href="<?php echo $addurl ?>" title="New <?php echo $moduleitem; ?>" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-plus"></i> New <?php echo $moduleitem; ?></a></li>
                    <?php } ?>
                    <li>
                        <?php
                            $dropdown = new Zend_Form_Element_Select('type',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => 'All Types'), array('0'=>'Tbd value 1', '1'=>'Tbd value 1')),
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array("autofilter", "form-control", 'chosen-select', 'width150')
                                    )
                            );  
                            $dropdown->setValue($request->getParam('type')); 
                            echo $dropdown->render();
                        ?>
                    </li>
                    <li>
                        <?php
                            $dropdown = new Zend_Form_Element_Select('status',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => 'All Status'), array('1'=>'Active', '0'=>'In-active')),
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array("autofilter", "form-control", 'chosen-select', 'width150')
                                    )
                            );  
                            $dropdown->setValue($request->getParam('status')); 
                            echo $dropdown->render();
                        ?>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 padding0">
            	<div class="col-md-12 padding0"><input name="searchterm" id="searchterm" class="form-control form-search" value="<?php echo $request->searchterm; ?>" type="text" placeholder="Search <?php echo $listitems; ?>..." /><span class="glyphicon glyphicon-search glyphicon-list-search"></span></div>
            	<input type="hidden" name="letter" id="letter" value="<?php echo $request->getParam('letter'); ?>" />
                <?php if($allowclear){ ?>
                    <a href="<?php echo $listurl; ?>" title="Clear Search and Filters" id="" class="reset removeline close button btn">&times;</a>
                <?php } ?>
            </div>
        </div>
        
        <div class="divider10"></div>
        <?php echo $paginate->getAlphabetString(); ?>
		<?php if ($has_no_data) { ?>
            <div class="divider30"></div>
            <div style="clear:both;" class="alert alert-info margin5"><?php echo $this->translate("client_list_norecords"); ?></div>
        <?php } else { ?>
        	<div class="row-fluid peoplelist clearfix">
            	<div class="divider10"></div>
            	<?php
					$counter = 1; 				  		
					foreach($result as $line){
						$id = $line['id'];	
						$phone = $line['cell']; $phone2 = $line['home'];
						$addressline1 = $line['addressline1']; 
						$addressline1 = $line['addressline2'];
						
						$hasprofileimage = false;
						$real_path = APPLICATION_PATH.DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."public".DIRECTORY_SEPARATOR."uploads".DIRECTORY_SEPARATOR."users".DIRECTORY_SEPARATOR."user_";
						$real_path = $real_path.$id.DIRECTORY_SEPARATOR."avatar".DIRECTORY_SEPARATOR."medium_".$line['profilephoto'];
						if(file_exists($real_path) && !isEmptyString($line['profilephoto'])){
							$hasprofileimage = true;
						}
						$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
						$photo_path = $baseUrl.'/uploads/default/default_medium_male.jpg';
						
						if($line['gender'] == 2){
							$photo_path = $baseUrl.'/uploads/default/default_thumbnail_female.jpg'; 
						}
						if($hasprofileimage){
							$photo_path = $baseUrl.'/uploads/users/client_'.$id.'/avatar/medium_'.$line['profilephoto'];
						}
						
						$viewurl = $this->baseUrl('client/view/id/'.encode($id));
						//$line['fundername'] = 'DVRS';
						$line['currentstatus'] = 'Active';
					?>
                    	 <div class="col-xs-12 col-sm-6 xpaddingleft0">
                            <div class="peoplewrapper">
                                <div class="thumb img-thumbnail"><a href="<?php echo $viewurl; ?>"><img class="imagecontainer" src="<?php echo $photo_path; ?>" /></a></div>
                                <div class="peopleinfo">
                                    <h4><a href="<?php echo $viewurl; ?>"><?php echo $line['firstname']." ".$line['lastname']; ?></a></h4>
                                    <div class="row-fluid margin0">
                                    	<div class="col-md-6 padding0">
                                        	<ul>
                                                <li><span class="bolded">SSN:</span> <?php echo $line['ssn']; ?></li>
                                                <li><span class="bolded">Funder:</span> <?php echo isArrayKeyAnEmptyString($line['funderid'], $funders) ? '--' : $funders[$line['funderid']]; ?></li>
                                                <li><span class="bolded">Program:</span> <?php echo isArrayKeyAnEmptyString($line['program'], $programs) ? '--' : $programs[$line['program']]; ?></li>                                                
                                                <li><span class="bolded">Supervisor:</span>--</li>
                                                <li><span class="bolded">Status:</span> <?php echo $line['currentstatus']; ?></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-6 padding0">
                                            <ul>
                                            	<li><span class="bolded">Contact</span></li>
                                                <li><?php echo $line['cell']; ?></li>
                                                <li><?php echo $line['addressline1']; ?></li>
                                                <li><?php echo $line['city'].' '.$line['state'].' '.$line['zipcode']; ?></li>
                                            </ul>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                   <?php } ?> 
            </div>
            <div class="row-fluid">
                <div class="table-footer">
                    <div class="col-md-6 padding0" style="margin-bottom:10px;">
                        <div class="table-actions">
                            <div class="row col-md-12 margin0 padding0 clearfix">
                                <div class="col-md-6 padding0 floatleft"><?php echo $paginate->getListCountDropDown(); ?></div>
                                <div class="col-md-6 paddingleft5 rightalign" style="margin-bottom:5px;"><?php echo sprintf($this->translate("global_list_counter"), $paginate->getItemCounterText()); ?></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 padding0">
                        <?php echo $paginate->getPaginationLinks(); ?>
                    </div>
                </div>
            </div>
        <?php } ?>
                                                                      
	</form>
</div>            
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
