<?php 
	$baseview = $this->baseUrl('client/view/id/'.encode($client->getID()).'/tab/profile');
	if(isEmptyString($request->section)){
		$request->setParam('section', 'bio');
		$section = 'bio';
	}
	if($section == 'exit'){
		$posturl = $this->baseUrl("client/terminate");
	}
	
	// dropdown data
	$maritalstatuses = getAllMaritalStatuses();
	$educationlevels = getEducationLevels();
	$races = getAllRaces();
	$languages = getAllLanguages();
	$programs = getPrograms();
	$funders = getFunders();
	$services = getServiceTypes();
	$disabilitycodes = getDisabilityDiagnosisCodes(''); $disabilitycodes_notaliased = getDisabilityDiagnosisCodes('', false);
	$causecodes = getDisabilityCauseCodes(); $causecodes_notaliased = getDisabilityCauseCodes('', false);
	$communicationtypes = getCommunicationLevels();
	$housingtypes = getHousingTypes();
	$transportmodes = getTransportationModes();
	$skills = getAllClientSkills();
	$states = getStates();
	$counties = getAllCounties();
	$ratetypes = getRateTypes();
	$incomesources = getAllIncomeSources();
	$rships = getAllRelationshipOptions();
	$therapytreatments = getAllTherapyTreatments();
	
	$dob = $client->getDateofBirth();
	$birthday = ''; $birthmonth = ''; $birthyear = ''; $dateofbirth = '';
	if(!isEmptyString($dob)){
		$dateofbirth = date('M d, Y', strtotime($dob)); 
		$birthday = date('d', strtotime($dob)); 
		$birthmonth = date('m', strtotime($dob)); 
		$birthyear = date('Y', strtotime($dob)); 
	}
	// debugMessage($birthday.' - '.$birthmonth.' - '.$birthyear.' - '.$dateofbirth);
?>
<?php if(isEmptyString($request->pgc)){ ?>
<script>
$(document).ready(function() {
	var section = '<?php echo $section; ?>';
	<?php if($step == 'edit'){ ?>
		$('#collapse_'+section+' .edit, #collapse_'+section+' .requiredmark, #collapse_'+section+' .save_trigger, #collapse_'+section+' .cancel_trigger').removeClass('hidden').show();
		$('#collapse_'+section+' .view, #collapse_'+section+' .update_trigger').addClass('hidden').hide();
		$('#collapse_'+section+' .edit .form-control').attr('readonly', false).attr('disabled', false);
		$('.panel-collapse .edit .form-control:not(#collapse_'+section+' .edit .form-control)').attr('readonly', true).attr('disabled', true);
		$('.panel-collapse .edit .disableoutsidesection:not(#collapse_'+section+' .edit .disableoutsidesection)').attr('readonly', true).attr('disabled', true);
		if(section != 'assessment'){
			$('#collapse_assessment .edit .form-control, #collapse_assessment .edit .disableoutsidesection').attr('disabled', true);
		}
	<?php } ?>
	
	<?php if($section != 'exit'){ ?>
		// validation 
		$("#form-profile").validate({		
			<?php require APPLICATION_PATH."/views/scripts/client/validation.phtml"; ?>
		});
	<?php } ?>
	
	$.validator.addMethod("validbirth", function(value, element, params) { 
		var day = $("#birthday").val();
		var month = $("#birthmonth").val();
		var year = value;
		if (!isEmptyString(day) && !isEmptyString(month) && !isEmptyString(year)) {
			return true; 
		}
		return false;        
	}, "Please select full Date of Birth");
		
	// maintain settings disable and readonly settings for dateofbirth, state, dateapproved
	$(".datefield, #state").attr('readonly', true);
	$(".chosen-container.chosen-container-single").css({'width':'100%'});
	
	// on trigger update, show update fields for a particular section. also cancel any other open fields for update in other sections
	$(".update_trigger").click(function(){
		$.blockUI({ message: '<?php echo $blockcontent; ?>' }); 
	});
	
	// save changes
	$(".save_trigger").click(function(e){
		e.preventDefault();
		var section = $(this).attr('section');
		$("#successurl").val(base64_encode('<?php echo $this->baseUrl('client/view/id/'.encode($client->getID()).'/tab/'.$tab.'/section/'); ?>'+section));
		$("#failureurl").val(base64_encode('<?php echo $this->baseUrl('client/view/id/'.encode($client->getID()).'/tab/'.$tab.'/step/edit/section/'); ?>'+section));
		if ($("#form-profile").valid()) {
			$.blockUI({ message: '<?php echo $blockcontent; ?>' }); 
			$("#form-profile").submit();
		}
	});
	
	// show or hide containers for resume and cover documents 
	<?php if($client->hasResume()){ ?>
		$("#aftersave_resume").addClass('show').removeClass('hidden');
		$("#beforesave_resume").addClass('hidden').removeClass('show');
	<?php } ?>
	<?php if($client->hasCoverletter()){ ?>
		$("#aftersave_cover").addClass('show').removeClass('hidden');
		$("#beforesave_cover").addClass('hidden').removeClass('show');
	<?php } ?>
	
	// add filename of selected file in background of input to indicate that a file has been selected.
	$("#resumefilename").change(function(){
		if(!isEmptyString($(this).val())){
			$("#beforesave_resume .fileinput-preview").html($(this).val());
			$("#missingresume").html('').remove();
		}
	});
	$("#coverletterfilename").change(function(){
		if(!isEmptyString($(this).val())){
			$("#beforesave_cover .fileinput-preview").html($(this).val());
		}
	});
	
	$(".reupload").click(function(e){
		e.preventDefault();
		var type = $(this).attr('rel');
		var message = '<label class="small centeralign blocked">Note that Re-Uploading this file while delete and replace the existing one. <br /><br /> Click <b>OK</b> to continue or <b>Cancel</b> to ignore</label>';
		bootbox.confirm(message, function(confirmed) {
			if(confirmed){
				// remove the file via ajax
				$(this).hide();
				$("#loading_"+type).removeClass('hidden');
				
				$.get("<?php echo $this->baseUrl('client/removeupload/id/'.$client->getID().'/'); ?>type/"+type, 
				   {                        
					cachebuster: new Date().getTime()},                            
					function(data){                        
						// alert(data);      
						$("#beforesave_"+type+"").addClass('show').removeClass('hidden');                  
						$("#aftersave_"+type+", #reupload_"+type+", #loading_"+type).addClass('hidden').removeClass('show');
					}
				);
			} else {
				bootbox.hideAll();
				return false;
			}
		});
	});
	
}); 
</script>
<?php } ?>	
<form id="form-profile" class="form-horizontal profile" role="form" action="<?php echo $posturl; ?>" method="post" enctype="multipart/form-data">
    <input type="hidden" id="entityname" name="entityname" value="Client" />
    <input type="hidden" id="id" name="id" value="<?php echo encode($client->getID()); ?>" />
    <input type="hidden" class="successurl" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" value="" />
    <input type="hidden" class="failureurl" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" value="" />
    <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $successmessage; ?>" />
    <input type="hidden" id="nosuccessid" name="nosuccessid" value="1" />
    <input type="hidden" id="status" name="status" value="<?php echo $client->getStatus(); ?>" />
    <?php if($step == 'view' && isEmptyString($request->pgc)){ ?>
    	<a title="Print" href="<?php echo stripURL($this->viewurl).'/print/1/pgc/true'; ?>" class="btn btn-default btn-sm" style="position:absolute; right:15px; top:5px;" target="_blank"><i class="glyphicon glyphicon-print"></i> Print</a>
    <?php } ?>
    <?php if($step == 'view' && !isEmptyString($request->pgc)){ ?>
    	<h3 style="margin-top:10px; font-size:20px;">Profile Report - <?php echo $client->getName(); ?></h3>
    <?php } ?>
    <div class="panel-group" id="accordion">
        <div class="panel panel-primary clearfix" id="bio">
            <div class="panel-heading">
                <h4 class="panel-title"><a class="accordion-toggle bolded <?php echo $section == 'bio' ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#accordion" href="#collapse_bio">Bio Data</a> </h4>
            </div>
            <div id="collapse_bio" class="panel-collapse collapse <?php echo $section == 'bio' || !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
                <div class="panel-body">
                	<div class="row-fluid margin0 hideonprint">
                        <div class="col-md-12 padding0 pull-right rightalign">
                            <p class="margin0 lineblocked">
                                <a href="<?php echo stripURL($baseview).'/section/bio/step/edit'; ?>" class="btn btn-xs <?php echo !$client->isActive() ? 'btn-alert alert-dialog' : 'btn-primary update_trigger'; ?>" section="bio" message="This Account is closed and updates are disabled."><i class="glyphicon glyphicon-pencil"></i> Update</a>
                            </p>
                            <p class="margin0 lineblocked">
                                <button type="submit" class="btn btn-success btn-sm button-submit save_trigger" section="bio" name="save"><i class="glyphicon glyphicon-ok"></i> Save Changes</button>
                            </p>
                            <p class="margin0 lineblocked">
                                <a class="cancel cancel_trigger" section="bio"><?php echo $this->translate('global_button_cancel'); ?></a>
                            </p>
                        </div>
                    </div>
                    <?php require APPLICATION_PATH."/views/scripts/client/bio.phtml"; ?>
                </div>
            </div>
        </div>
        <div class="panel panel-primary clearfix blocked" id="referral">
            <div class="panel-heading">
                <h4 class="panel-title"> <a class="accordion-toggle bolded <?php echo $section == 'referral' || !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#accordion" href="#collapse_referral">Referral Information</a> </h4>
            </div>
            <div id="collapse_referral" class="panel-collapse collapse <?php echo $section == 'referral' || !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
                <div class="panel-body">
                	<div class="row-fluid margin0 hideonprint">
                        <div class="col-md-12 padding0 pull-right rightalign">
                            <p class="margin0 lineblocked">
                                <a href="<?php echo stripURL($baseview).'/section/referral/step/edit'; ?>" class="btn btn-xs <?php echo !$client->isActive() ? 'btn-alert alert-dialog' : 'btn-primary update_trigger'; ?>" section="referral" message="This Account is closed and updates are disabled." ><i class="glyphicon glyphicon-pencil"></i> Update</a>
                            </p>
                            <p class="margin0 lineblocked">
                                <button type="submit" class="btn btn-success btn-sm button-submit save_trigger" section="referral" name="save"><i class="glyphicon glyphicon-ok"></i> Save Changes</button>
                            </p>
                            <p class="margin0 lineblocked">
                                <a class="gonowhere cancel cancel_trigger" section="bio"><?php echo $this->translate('global_button_cancel'); ?></a>
                            </p>
                        </div>
                    </div>
                    <?php require APPLICATION_PATH."/views/scripts/client/referral.phtml"; ?>
                </div>
            </div>
        </div>
        <div class="panel panel-primary" id="assessment">
            <div class="panel-heading">
                <h4 class="panel-title"> <a class="accordion-toggle bolded <?php echo $section == 'assessment' || !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#accordion" href="#collapse_assessment">Intake Assessment</a> </h4>
            </div>
            <div id="collapse_assessment" class="panel-collapse collapse <?php echo $section == 'assessment' || !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
                <div class="panel-body" style="padding-left:8px; padding-right:8px;">
                    <div class="row-fluid margin0 hideonprint">
                        <div class="col-md-12 padding0 pull-right rightalign">
                            <p class="margin0 lineblocked" style="padding-right:0; margin-right:0;">
                                <a href="<?php echo stripURL($baseview).'/section/assessment/step/edit'; ?>" class="btn btn-xs <?php echo !$client->isActive() ? 'btn-alert alert-dialog' : 'btn-primary update_trigger'; ?>" section="assessment" message="This Account is closed and updates are disabled." ><i class="glyphicon glyphicon-pencil"></i> Update</a>
                            </p>
                            <p class="margin0 lineblocked">
                                <button type="submit" class="btn btn-success btn-xs button-submit save_trigger" section="assessment" name="save"><i class="glyphicon glyphicon-ok"></i> Save Changes</button>
                            </p>
                            <p class="margin0 lineblocked">
                                <a class="gonowhere cancel cancel_trigger" section="assessment"><?php echo $this->translate('global_button_cancel'); ?></a>
                            </p>
                        </div>
                    </div>
                    <div class="divider5"></div>
                    
                    <div class="panel-group" id="inneraccordion">
                        <div class="panel panel-default" id="assess1">
                            <div class="panel-heading">
                                <h4 class="panel-title"><a class="accordion-toggle dark" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col1"> Resume and Attachments</a> </h4>
                            </div>
                            <div id="collapse_col1" class="panel-collapse collapse in">
                            	<?php require APPLICATION_PATH."/views/scripts/client/attachment.phtml"; ?>
                           	</div>
                      	</div>
                        <div class="panel panel-default" id="assess2">
                            <div class="panel-heading">
                                <h4 class="panel-title"><a class="accordion-toggle dark" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col2"> Medical Information</a> </h4>
                            </div>
                            <div id="collapse_col2" class="panel-collapse collapse in">
				                <div class="panel-body">
                                	<?php require APPLICATION_PATH."/views/scripts/client/medical.phtml"; ?>
                                </div>
                           	</div>
                      	</div>
                        <div class="panel panel-default" id="assess3">
                            <div class="panel-heading">
                                <h4 class="panel-title"><a class="accordion-toggle dark <?php echo !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col3"> Family and Living</a> </h4>
                            </div>
                            <div id="collapse_col3" class="panel-collapse collapse <?php echo !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
				                <div class="panel-body">
                                	<?php require APPLICATION_PATH."/views/scripts/client/family.phtml"; ?> 
                                </div>
                           	</div>
                      	</div>
                        
                        <div class="panel panel-default" id="assess4">
                            <div class="panel-heading">
                                <h4 class="panel-title"><a class="accordion-toggle dark <?php echo !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col4"> Employment Preferrences</a> </h4>
                            </div>
                            <div id="collapse_col4" class="panel-collapse collapse <?php echo !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
				                <div class="panel-body">
                                    <?php require APPLICATION_PATH."/views/scripts/client/jobpreferance.phtml"; ?> 
                                </div>
                           	</div>
                      	</div>
                        
                        <div class="panel panel-default" id="assess5">
                            <div class="panel-heading">
                                <h4 class="panel-title"><a class="accordion-toggle dark <?php echo !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col5"> Employment History</a> </h4>
                            </div>
                            <div id="collapse_col5" class="panel-collapse collapse <?php echo !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
				                <div class="panel-body">
                                	<?php require APPLICATION_PATH."/views/scripts/client/jobhistory.phtml"; ?>
                                </div>
                           	</div>
                      	</div>
                        
                        <div class="panel panel-default" id="assess6">
                            <div class="panel-heading">
                                <h4 class="panel-title"><a class="accordion-toggle dark <?php echo !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col6"> Education Background</a> </h4>
                            </div>
                            <div id="collapse_col6" class="panel-collapse collapse <?php echo !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
				                <div class="panel-body">
                              		<div class="panel-body well-sm">
                                    	<?php require APPLICATION_PATH."/views/scripts/client/education.phtml"; ?>
                                    </div>
                                </div>
                           	</div>
                      	</div>
                        <div class="panel panel-default" id="assess7">
                            <div class="panel-heading">
                                <h4 class="panel-title"><a class="accordion-toggle dark <?php echo !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col7"> References</a> </h4>
                            </div>
                            <div id="collapse_col7" class="panel-collapse collapse <?php echo !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
				                <div class="panel-body">
                             		<div class="panel-body well-sm">
                                    	<?php require APPLICATION_PATH."/views/scripts/client/references.phtml"; ?>
                                    </div>
                                </div>
                           	</div>
                      	</div>
                        <div class="panel panel-default" id="assess8">
                            <div class="panel-heading">
                                <h4 class="panel-title"><a class="accordion-toggle dark <?php echo !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col8"> Legal Information</a> </h4>
                            </div>
                            <div id="collapse_col8" class="panel-collapse collapse <?php echo !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
				                <div class="panel-body">
                                    <?php require APPLICATION_PATH."/views/scripts/client/legal.phtml"; ?>
                                </div>
                           	</div>
                      	</div>
                        <div class="panel panel-default" id="assess9">
                            <div class="panel-heading">
                                <h4 class="panel-title"><a class="accordion-toggle dark <?php echo !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col9"> Military Service</a> </h4>
                            </div>
                            <div id="collapse_col9" class="panel-collapse collapse <?php echo !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
				                <div class="panel-body">
                                	<?php require APPLICATION_PATH."/views/scripts/client/military.phtml"; ?>
                                </div>
                           	</div>
                      	</div>
                        
                        <div class="panel panel-default" id="assess10">
                            <div class="panel-heading">
                                <h4 class="panel-title"><a class="accordion-toggle dark <?php echo !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col10"> Cultural and Social Information</a> </h4>
                            </div>
                            <div id="collapse_col10" class="panel-collapse collapse <?php echo !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
				                <div class="panel-body">
                                	<?php require APPLICATION_PATH."/views/scripts/client/social.phtml"; ?>
                                </div>
                           	</div>
                      	</div>
                        
                        <div class="panel panel-default" id="assess11">
                            <div class="panel-heading">
                                <h4 class="panel-title"><a class="accordion-toggle dark <?php echo !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#inneraccordion" href="#collapse_col11"> Personal Health and Safety Assessment</a> </h4>
                            </div>
                            <div id="collapse_col11" class="panel-collapse collapse <?php echo !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
				                <div class="panel-body">
                                	<div class="panel-body well-sm">
                                    	<?php require APPLICATION_PATH."/views/scripts/client/qnassessment.phtml"; ?>
                                    </div>
                                </div>
                           	</div>
                      	</div>
                       
                    </div>
              	</div>
          	</div>
        </div>
        <div class="panel panel-primary" id="emergency">
            <div class="panel-heading">
                <h4 class="panel-title"><a class="accordion-toggle bolded <?php echo $section == 'emergency' || !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#accordion" href="#collapse_emergency">Emergency Information </a> </h4>
            </div>
            <div id="collapse_emergency" class="panel-collapse collapse <?php echo $section == 'emergency' || !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
            	<div class="panel-body">
                    <div class="row-fluid margin0 hideonprint">
                        <div class="col-md-12 padding0 pull-right rightalign">
                            <p class="margin0 lineblocked">
                                <a href="<?php echo stripURL($baseview).'/section/emergency/step/edit'; ?>" class="btn btn-xs <?php echo !$client->isActive() ? 'btn-alert alert-dialog' : 'btn-primary update_trigger'; ?>" section="emergency" message="This Account is closed and updates are disabled." ><i class="glyphicon glyphicon-pencil"></i> Update</a>
                            </p>
                            <p class="margin0 lineblocked">
                                <button type="submit" class="btn btn-success btn-sm button-submit save_trigger" section="emergency" name="save"><i class="glyphicon glyphicon-ok"></i> Save Changes</button>
                            </p>
                            <p class="margin0 lineblocked">
                                <a class="gonowhere cancel cancel_trigger" section="bio"><?php echo $this->translate('global_button_cancel'); ?></a>
                            </p>
                        </div>
                    </div>
                	<?php require APPLICATION_PATH."/views/scripts/client/emergency.phtml"; ?>
             	</div>
            </div>
        </div>
        <div class="panel panel-primary" id="assign">
            <div class="panel-heading">
                <h4 class="panel-title"><a class="accordion-toggle bolded <?php echo $section == 'assign' || !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#accordion" href="#collapse_assign">Assignment History</a> </h4>
            </div>
            <div id="collapse_assign" class="panel-collapse collapse <?php echo $section == 'assign' || !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
                <div class="panel-body">
					<?php require APPLICATION_PATH."/views/scripts/client/assignment.phtml"; ?>
                </div>
            </div>
        </div>
        <div class="panel panel-primary" id="exit">
            <div class="panel-heading">
                <h4 class="panel-title"><a class="accordion-toggle bolded <?php echo $section == 'exit' || !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#accordion" href="#collapse_exit">Exit Summary</a> </h4>
            </div>
            <div id="collapse_exit" class="panel-collapse collapse <?php echo $section == 'exit' || !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
                <div class="panel-body">
					<?php require APPLICATION_PATH."/views/scripts/client/exit.phtml"; ?>
                </div>
            </div>
        </div>
        <?php if(isEmptyString($request->pgc)){ ?>  
        <div class="panel panel-primary" id="status">
            <div class="panel-heading">
                <h4 class="panel-title"><a class="accordion-toggle bolded <?php echo $section == 'status' || !isEmptyString($request->pgc) ? '' : 'collapsed' ; ?>" data-toggle="collapse" data-parent="#accordion" href="#collapse_status">Account Information</a> </h4>
            </div>
            <div id="collapse_status" class="panel-collapse collapse <?php echo $section == 'status' || !isEmptyString($request->pgc) ? 'in' : '' ; ?>">
                <div class="panel-body">
                	<?php require APPLICATION_PATH."/views/scripts/client/account.phtml"; ?>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>                  
</form>