<div class="col-md-12">
    <div class="form-group">
        <label class="col-md-12 control-label"><?php echo $this->translate('client_references_label'); ?>:</label>
        <div class="col-md-12">
            <p class="form-control-static nullifempty view">
                <table class="table table-condensed table-striped table-responsive viewtable" style="margin-bottom:10px;">
                    <thead>
                        <tr>
                            <th class="centeralign" style="width:15px;">#</th>
                            <th>Name</th>
                            <th style="width:20%;">Work Relationship</th>
                            <th style="width:25%;">Email</th>
                            <th style="width:25%;">Phone</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php 
                            $references = $client->getAssessmentDetails(5); // debugMessage($assigments->toArray());													
                            $count_references = $references->count();
                        ?>
                        <?php if($count_references == 0){ ?>
                            <tr>
                                <td></td>
                                <td>--</td>
                                <td>--</td>
                                <td>--</td>
                                <td>--</td>
                            </tr>
                        <?php } else { ?>
                            <?php 
                                $counter = 1;
                                foreach($references as $reference){
                            ?>
                            <tr>
                                <td class="centeralign"><?php echo $counter; ?></td>
                                <td><?php echo $reference->getValue1(); ?></td>
                                <td><?php echo $reference->getValue2(); ?></td>
                                <td><?php echo $reference->getValue3(); ?></td>
                                <td><?php echo $reference->getValue4(); ?></td>
                            </tr>
                            <?php $counter++; } ?>
                        <?php } ?>
                    </tbody>
                </table>
            </p>
            <?php if(($step == 'edit' && $section == 'assessment') || $step == 'new'){ ?>
            <div class="edit">
                <table class="table table-condensed table-striped table-responsive viewtable" style="margin-bottom:10px;">
                    <thead>
                        <tr>
                            <th class="centeralign" style="width:15px;">#</th>
                            <th>Name</th>
                            <th style="width:20%;">Work Relationship</th>
                            <th style="width:25%;">Email</th>
                            <th style="width:25%;">Phone</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php 
                            $counter = 1;
                            $nooflines = $count_references;
                            $e = 0; $x = 0;
                             foreach($references as $reference){
                                 $class = "visible_row_ref";
                        ?>
                        <tr class="<?php echo $class; ?> row_ref_<?php echo $e; ?>" id="row_ref_<?php echo $e; ?>">
                            <td class="centeralign"><a href="javascript: doNothing();" title="<?php echo $this->translate("global_button_remove"); ?>" id="row_ref_<?php echo $e; ?>" class="removeline btn btn-xs btn-default" rel="ref">&times;</a>
                                <input type="hidden" id="references_id_<?php echo $e; ?>" class="form-control" name="references[<?php echo md5($e); ?>][id]" value="<?php echo $reference->getID(); ?>" />
                            </td>
                            <td><input type="text" class="form-control input-sm" name="references[<?php echo md5($e); ?>][value1]" id="references_value1_<?php echo $e; ?>" value="<?php echo $reference->getValue1(); ?>" /></td>
                            <td><input type="text" class="form-control input-sm" name="references[<?php echo md5($e); ?>][value2]" id="references_value2_<?php echo $e; ?>" value="<?php echo $reference->getValue2(); ?>" /></td>
                            <td><input type="text" class="form-control input-sm" name="references[<?php echo md5($e); ?>][value3]" id="references_value3_<?php echo $e; ?>" value="<?php echo $reference->getValue3(); ?>" /></td>
                            <td><input type="text" class="form-control input-sm" name="references[<?php echo md5($e); ?>][value4]" id="references_value4_<?php echo $e; ?>" value="<?php echo $reference->getValue4(); ?>" /></td>
                        </tr>
                        <?php $e++; $x++; $counter++; } ?>
                        <?php 
                            $defaultlines = 3;
                            if($nooflines >= 3){
                                $defaultlines = $nooflines + 1;
                            }
                            for($i = $e; $i<10; $i++){
                                // debugMessage($i);
                                $class = "visible_row_ref";
                                if($i >= $defaultlines){
                                    $class = "hidden_row_ref";
                                }
                            
                        ?>
                            <tr class="<?php echo $class; ?> row_ref_<?php echo $i; ?>" id="row_ref_<?php echo $i; ?>">
                                <td class="centeralign"><a href="javascript: doNothing();" title="<?php echo $this->translate("global_button_remove"); ?>" id="row_ref_<?php echo $i; ?>" class="removeline btn btn-xs btn-default" rel="ref">&times;</a>
                                </td>
                                <td><input type="text" class="form-control input-sm" name="references[<?php echo md5($i); ?>][value1]" id="references_value1_<?php echo $i; ?>" value="" /></td>
                                <td><input type="text" class="form-control input-sm" name="references[<?php echo md5($i); ?>][value2]" id="references_value2_<?php echo $i; ?>" value="" /></td>
                                <td><input type="text" class="form-control input-sm" name="references[<?php echo md5($i); ?>][value3]" id="references_value3_<?php echo $i; ?>" value="" /></td>
                                <td><input type="text" class="form-control input-sm" name="references[<?php echo md5($i); ?>][value4]" id="references_value4_<?php echo $i; ?>" value="" /></td>
                            </tr>
                        <?php $x++; } ?>
                        <!--<tr>
                            <td></td>
                            <td colspan="4"><a href="javascript: void(0)" title="Add another" class="addline btn btn-primary btn-xs pull-left" id="ref">Add Row</a></td>
                        </tr>-->
                    </tbody>
                </table>
            </div>
            <?php } ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-6 padding0">
            <label class="col-md-12 control-label"><?php echo $this->translate('client_cancontactreferences_label'); ?></label>
            <div class="col-md-12">
                <p class="form-control-static nullifempty view"><?php echo $client->getcancontactreferences_text(); ?></p>
                <?php if(($step == 'edit' && $section == 'assessment') || $step == 'new'){ ?>
                <div class="edit">
                    <label class="radio-inline">
                      <input type="radio" id="cancontactreferences_1" name="cancontactreferences" class="radiobutton disableoutsidesection" value="1" <?php echo $client->getcancontactreferences() == 1 && !isEmptyString($client->getcancontactreferences()) ? 'checked data-waschecked="true"' : ''; ?>>Yes
                    </label>
                    <label class="radio-inline">
                      <input type="radio" id="cancontactreferences_0" name="cancontactreferences" class="radiobutton disableoutsidesection" value="0" <?php echo $client->getcancontactreferences() == 0 && !isEmptyString($client->getcancontactreferences()) ? 'checked data-waschecked="true"' : ''; ?>>No
                    </label>
                    <input type="hidden" name="cancontactreferences_old" id="cancontactreferences_old" value="<?php echo $client->getcancontactreferences(); ?>" />
                </div>
                <?php } ?>
            </div>
        </div>
        <div class="col-md-6 padding0">
            <label class="col-md-12 control-label"><?php echo $this->translate('client_whynotcontact_label'); ?>:</label>
            <div class="col-md-12">
                <p class="form-control-static nullifempty view"><?php echo $client->getwhynotcontact(); ?></p>
                <?php if(($step == 'edit' && $section == 'assessment') || $step == 'new'){ ?>
                <div class="edit">
                    <textarea class="form-control expanding" id="whynotcontact" name="whynotcontact"><?php echo $client->getwhynotcontact(); ?></textarea>
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>