<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$client = new Client();
    $client->populate(decode($request->id));
	$id = $client->getID();
	// debugMessage($client->getMediumPicturePath());
	
	$posturl = $this->baseUrl("client/edit"); 
	$successmessage = $this->translate('profile_update_success');
	$listurl = $this->baseUrl('client/list');
	
	$tab = $request->tab;
	$tabtitle = 'Profile';
	if(isEmptyString($request->tab)){
		$request->setParam('tab', 'profile'); 
		$tab = 'profile';
	}

	$section = $request->section;
	$step = $request->step;
	if(isEmptyString($request->step)){
		$request->setParam('step', 'view');
		$step = 'view';
	}
	
	$title = $client->getName();
	$description = 'Profile Details';	
	$this->headTitle($title.$browserappend);/**/
?>
<script>

$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.'Clients / '.$client->getName(); ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="glyphicon glyphicon-list-alt"></span>');
	
	var tab = '<?php echo $tab; ?>';
	$("#tabtitle").html($("#tab_"+tab+" a."+tab).html());
	
	// hide edit controls by default
	$('.edit, .requiredmark, .save_trigger, .cancel_trigger').addClass('hidden');
	
});
</script>
<?php if(false){ ?>
<?php } ?>
<?php //if(false){ ?>
<div class="row-fluid margin0 view">
    <div class="col-md-12 padding0">
    	<div class="headerbox">
            <table class="table border0 nohover margin0">                       
                <tr>		                    
                    <td class="padding2">
                        <?php if ($acl->checkPermission('Client', ACTION_LIST)) { ?>	
                            <a class="btn btn-default btn-sm" href="<?php echo $this->baseUrl('client/list'); ?>"><i class="glyphicon glyphicon-list"></i> Clients</a>
                        <?php } ?>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <?php if ($sessionhaserror) { ?>
        <div class="alert alert-danger"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
    <?php } ?>
    <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
        <div class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
    <?php } ?>
    <div id="tabs">
        <?php require APPLICATION_PATH."/views/scripts/client/leftcolumn.phtml"; ?>
        <div class="col-md-9 tab-content makerelative padding0 clearfix" id="center">
        	<div id="profile">
            	<?php if($tab == 'profile'){ ?>
                	<h4 class="hideonprint">Profile</h4>
                    <?php require APPLICATION_PATH."/views/scripts/client/profile.phtml"; ?>
				<?php } ?>
			</div> 
            <div id="employment">
            	<?php if($tab == 'employment'){ ?>
                	<h4 class="hideonprint">Employment</h4>
                	<?php require APPLICATION_PATH."/views/scripts/client/employment.phtml"; ?>
                <?php } ?>
			</div>
            <div id="voucher">
				<?php if($request->tab == 'voucher'){ ?>
                	<h4 class="hideonprint">Vouchers</h4>
					<?php require APPLICATION_PATH."/views/scripts/client/voucher.phtml"; ?>
                <?php } ?>
			</div>
            <div id="activity">
				<?php if($request->tab == 'activity'){ ?>
                	<h4 class="hideonprint">Interventions</h4>
                	<?php require APPLICATION_PATH."/views/scripts/client/activity.phtml"; ?>
                <?php } ?>
			</div>
            <div id="finance">
                <?php if($request->tab == 'finance'){ ?>
                	
                	<?php require APPLICATION_PATH."/views/scripts/client/finance.phtml"; ?>
                <?php } ?>
			</div>
            <div id="report">
                <?php if($request->tab == 'report'){ ?>
                	<h4 class="hideonprint">Reports</h4>
                	<?php require APPLICATION_PATH."/views/scripts/report/dashboard.phtml"; ?>
                <?php } ?>
			</div>
     	</div> 
    </div>
</div> 
<?php //} ?>   
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
