 <?php
 	$voucher = new Voucher();
 	$baseview = $this->baseUrl('client/view/id/'.encode($client->getID()).'/tab/voucher');
	if($step == 'view'){
		$vouchers = $client->getClientVouchers(); // debugMessage($vouchers->toArray());
		$voucher_count = $vouchers->count();
	}
	if(!isEmptyString($request->vid)){
		$voucher_count = '';
		$voucher->populate(decode($request->vid)); // debugMessage($voucher->toArray());
	}
	if($step == 'new' ){
		$voucher_count = '';
		$voucher->setServiceTypeID($client->getServiceTypeID());
		$voucher->setType(1);
		$voucher->setClientID($client->getID());
	}
	
	$isfollowalong = false;
	if(!isEmptyString($request->faid) || $voucher->isFollowAlong()){
		$isfollowalong = true;
		$favoucher = new Voucher();
		$favoucher->populate(decode($request->faid));
		// debugMessage($favoucher->toArray());
		if($step == 'new'){
			$voucher->setStatus('2');
			$voucher->setFaVoucherNo($favoucher->getfaprefix());
			$voucher->setType(2);
			$voucher->setParentID($favoucher->getID());
			$voucher->setRate($favoucher->getRate());
		}
	}
	
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$formvalues = $session->getVar(FORM_VALUES);
		$voucher->processPost($formvalues);
	}
	
	$services = getServiceTypes(); $services_noalias = getServiceTypes('', false);
	$faservices = getFAServiceTypes(); $faservices_noalias = getFAServiceTypes('', false);
	$programs = getPrograms();
	$funders = getFunders();
	$voucherstatuses = getVoucherStatuses();
?>
<script>
$(document).ready(function() {
	/*var dateofbirthOpts = datepickerOpts;
	dateofbirthOpts.yearRange = "-<?php //echo date('Y')-2010; ?>:-0"; 
	var startfrom = '<?php //echo date('Y'); ?>';
	datepickerOpts.maxDate = new Date("Dec 31, "+startfrom);
	$(".datefield").datepicker(dateofbirthOpts);*/
	
	<?php if($step == 'edit' || $step == 'new'){ ?>
		$('.edit, .requiredmark, .save_trigger, .cancel_trigger').removeClass('hidden');
		$('.form-control-static.view, .update_trigger').addClass('hidden');
		
		$(".save_trigger, .save").click(function(e){
			e.preventDefault();
			var status = $("#status").val();
			if ($("#form-voucher").valid()) {
				$.blockUI({ message: '<?php echo $blockcontent; ?>' }); 
				$("#form-voucher").submit();
			}
		});
		
		$("#servicetypeid").change(function(e){
			var value = $(this).val();
			if(value == 3 || value == 5){
				enableContainerByID('intensive');
				$("#type").attr('checked', true);
			} else {
				disableContainerByID('intensive');
				$("#type").attr('checked', false);
			}
		});
		$("#servicetypeid").trigger('change');
		
		$(".computeamount").keyup(function(){
			var rate = $("#rate").val();
			var hours = $("#hours").val();
			// alert(rate); alert(hours);
			if(!isEmptyString(rate) && !isEmptyString(hours)){
				$("#amount_computed").html((parseFloat(rate)*parseFloat(hours)).toFixed(2));
			} else {
				$("#amount_computed").html('0.00');
			}
		});
		$(".computeamount").trigger("keyup");
	<?php } ?>
	
	<?php if($request->print == 1 || $request->pdf == 1){ ?>
		$("body").addClass('print');
		$("body.print #headercontainer, body.print #sidebar, body.print .breadcrumbs, body.print .pageheader, body.print #tabs #left, body.print .hideonprint").html('').remove();
		$("body.print .showonprint").show().removeClass('hidden');
		$('body.print div.controls, body.print .nullifempty').each(function() {
			var html = $(this).html();
			if(isEmptyString(html)){
				$(this).html('');
			}
		});
	<?php } ?>
}); 
</script>	        
<form id="form-voucher" class="form-horizontal voucher" role="form" action="<?php echo $this->baseUrl("voucher/create"); ?>" method="post">
	<div class="showonprint hidden">
        <div class="divider15"></div>
        <span id="reportactions">			
            <div id="print_page_action_buttons">
                <a title="Close Window" onClick="window.close()" class="btn btn-default btn-xs"><i class="glyphicon glyphicon-remove"></i> Close</a>
                <?php if($request->print == '1'){ ?>
                    <a title="Print" onClick="window.print()" class="btn btn-primary btn-xs print" ><i class="glyphicon glyphicon-print"></i> Print</a>&nbsp;
                <?php } ?>
                <?php if($request->pdf == '1'){ ?>
                    <a class="btn btn-primary btn-xs exportpdf blockanchor" href="<?php echo rtrim($this->viewurl,'/').'/generate/1'; ?>"><i class="glyphicon glyphicon-save"></i> Print to PDF</a>&nbsp;
                <?php } ?>
            </div>
        </span>
        <div class="divider15"></div>
    </div>
    <?php
			$invoiceid = $voucher->getInvoiceForVoucher()->getID();
			 if(!isEmptyString($invoiceid)){ ?>
			<a href="<?php echo $this->baseUrl('client/view/id/'.encode($client->getID()).'/tab/finance/section/invoice/step/view/invid/'.encode($invoiceid)); ?>" class="btn btn-default xpull-right hideonprint"><i class="glyphicon glyphicon-list"></i> View Invoice</a> &nbsp;
		<?php } ?>
    <div class="btn-group pull-right hideonprint" style="margin-top:-10px;">
        
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
            Voucher Actions <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <?php if($step == 'view'){ ?>
				<?php if($acl->checkPermission('Voucher', ACTION_CREATE) && isEmptyString($request->vid)){ ?>	
                    <li><a href="<?php echo $baseview.'/step/new'; ?>" title="New Voucher"><i class="glyphicon glyphicon-plus"></i> New Voucher</a></li>
                <?php } ?>
                <?php if($acl->checkPermission('Voucher', ACTION_EDIT) && !isEmptyString($request->vid)){ ?>	
                	<li><a class="<?php echo !$client->isActive() ? 'btn-alert alert-dialog' : 'update_trigger'; ?>" message="This Account is closed and updates are disabled." href="<?php echo $baseview.'/step/edit/vid/'.encode($voucher->getID()); ?>" title="Update"><i class="glyphicon glyphicon-pencil"></i> Update Voucher</a></li>
                <?php } ?>
                <?php if(!isEmptyString($request->vid)){ ?>
                    <?php if($acl->checkPermission('Voucher', ACTION_CREATE)){ ?>	
                        <li><a href="<?php echo $baseview.'/step/new/faid/'.$request->vid; ?>"><i class="glyphicon glyphicon-arrow-right"></i> Request F/A</a></li>
                    <?php } ?>    
                <?php } ?>
                <?php if($acl->checkPermission('Activity', ACTION_CREATE) && !isEmptyString($request->vid)){ ?>	
                    <li><a href="<?php echo $this->baseUrl('client/view/id/'.encode($client->getID()).'/tab/activity/step/new/vid/'.encode($voucher->getID())); ?>" title="New Intervention"><i class="glyphicon glyphicon-plus"></i> Log New Intervention</a></li>
                    <li><a href="<?php echo $this->baseUrl('client/view/id/'.encode($client->getID()).'/tab/activity/step/view/voucherid/'.$voucher->getID()); ?>" title=" Intervention History"><i class="glyphicon glyphicon-list"></i> Intervention History</a></li>
                    <li><a title="Print" href="<?php echo rtrim($this->viewurl, "/").'/print/1'; ?>" target="_blank"><i class="glyphicon glyphicon-print"></i> Print Voucher</a></li>
                <?php } ?>
            <?php } ?>
            <?php if($acl->checkPermission('Voucher', ACTION_DELETE) && !isEmptyString($request->vid)){ ?>
				<?php 
                    $isdeletable = true;
                    $message = '';
                    if($client->getInitialVoucherID() == $voucher->getID()){
                        $isdeletable = false;
                        $message = 'The Initial Service Voucher cannot be deleted. Only updates are allowed!';
                    }
                    if($voucher->hasActivities()){
                        $isdeletable = false;
                        $message = 'This Voucher has Intervention Activities and delete is disabled!';
                    }
                ?>
                <li><a class="gonowhere <?php echo !$isdeletable ? 'alert-dialog' : 'confirm-dialog'; ?>" title="Delete" message="<?php echo $message; ?> " action="<?php echo $this->baseUrl('voucher/delete/id/'.encode($voucher->getID())."/entityname/Voucher/successurl/".encode($baseview)); ?>"><i class="glyphicon glyphicon-remove"></i> Delete Voucher</a></li>
            <?php } ?>
            <?php if(($step == 'view' && !isEmptyString($request->vid)) || $step == 'new'){ ?>
	            <li><a href="<?php echo $baseview.'/step/view'; ?>" title="All Vouchers"><i class="glyphicon glyphicon-list"></i> Return to Voucher History</a></li>
            <?php } ?>  
        </ul>
    </div>
    <?php if($step == 'edit' || $step == 'new'){ ?>
        <input type="hidden" id="entityname" name="entityname" value="Voucher" />
        <input type="hidden" id="id" name="id" value="<?php echo encode($voucher->getID()); ?>" />
        <input type="hidden" id="clientid" name="clientid" value="<?php echo $client->getID(); ?>" />
        <input type="hidden" class="successurl" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($baseview); ?>" />
        <input type="hidden" class="failureurl" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($this->viewurl); ?>" />
        <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $successmessage; ?>" />
        <input type="hidden" id="nosuccessid" name="nosuccessid" value="1" />
        <input type="hidden" name="parentid" id="parentid" value="<?php echo $voucher->getParentID(); ?>" />
    <?php } ?>
    <div class="panel-body padding0">
    	<div class="divider10"></div>
		<?php if($step == 'new'){ ?>
            <h5 class="inline margin0 bolded"><?php echo !isEmptyString($request->faid) ? 'Request Follow Along Voucher' : 'Enter new Voucher'; ?></h5>
        <?php } ?>
        <?php if($step == 'edit'){ ?>
            <h5 class="inline margin0 bolded">Update Voucher</h5>
        <?php } ?>
        <div class="row-fluid margin0">
            <div class="col-md-12 padding0 pull-right rightalign">
                <?php if($step == 'edit' || $step == 'new'){ ?>
                    <p class="margin0 lineblocked">
                        <button type="submit" class="btn btn-success btn-sm button-submit save_trigger save" name="save"><i class="glyphicon glyphicon-ok"></i> <?php echo $step == 'new' ? $this->translate('global_button_save') : $this->translate('global_button_save_changes'); ?></button>
                    </p>
                    <p class="margin0 lineblocked">
                        <a class="btn btn-default btn-sm cancel cancel_trigger"><i class="glyphicon glyphicon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                    </p>
                <?php } ?>
            </div>
        </div>
       	<?php if($voucher_count == 0 && $step == 'view' && isEmptyString($request->vid)){ ?>
        	<div class="divider15"></div>
            <div style="clear:both;" class="alert alert-warning margin5">There are currently no vouchers for <strong><?php echo $client->getName(); ?></strong></div>
        <?php } ?>
       
		<?php if($voucher_count > 0 && $step == 'view' && isEmptyString($request->vid)) { ?>
            <div class="pagedescription">Viewing details for <strong><?php echo $voucher_count == 1 ? '1 Voucher' : $voucher_count.' Vouchers'; ?></strong></div>
        <?php } ?>
       	<?php if(!isEmptyString($request->vid) || $step == 'edit' || $step == 'new'){ ?>
        
        <script>
			$(document).ready(function() {
				// validation 
				$("#form-voucher").validate({		
					// define the validation rules one field at a time
					rules: {
						funderid: "required",
						servicetypeid: "required",
						hours: {
							required: true
						},
						rate: {
							required: true
						},
						<?php if(!$isfollowalong){ ?>
							voucherno: "required",
						<?php } ?>
						favoucherno: "required",
						faprefix: {
							required: "#type:checked"
						},	
						<?php if(!$isfollowalong){ ?>			
							dateapproved: "required",
						<?php } ?>
						<?php if($isfollowalong){ ?>			
							enddate: "required",
						<?php } ?>
						startdate: "required",
						status: "required"
					}, 
					// the messages for each of the fields being validated
					messages: {		
						funderid: "<?php echo $this->translate("voucher_funderid_error"); ?>",
						servicetypeid: "<?php echo $this->translate("voucher_servicetypeid_error"); ?>",
						hours: {
							required: "<?php echo $this->translate("voucher_hours_error"); ?>"
						},
						rate: {
							required: "<?php echo $this->translate("voucher_voucherrate_error"); ?>"
						},
						<?php if(!$isfollowalong){ ?>
							voucherno: "<?php echo $this->translate("voucher_voucherno_error"); ?>",
						<?php } ?>
						favoucherno: "<?php echo $this->translate("voucher_favoucherno_error"); ?>",
						faprefix: {
							required: "<?php echo $this->translate("voucher_faprefix_error"); ?>"
						},
						<?php if(!$isfollowalong){ ?>					
						dateapproved: "<?php echo $this->translate("voucher_dateapproved_error"); ?>",
						<?php } ?>
						startdate: "<?php echo $this->translate("voucher_startdate_error"); ?>",
						fastartdate: "<?php echo $this->translate("voucher_startdate_error"); ?>",
						<?php if($isfollowalong){ ?>			
							enddate: "<?php echo $this->translate("voucher_enddate_error"); ?>",
						<?php } ?>
						status: "<?php echo $this->translate("voucher_status_error"); ?>"
					},
					// custom error positions
					errorPlacement: function(error, element) {
						switch(element.attr("name")){					
							default:
								if(element.hasClass("useid_error")){
									error.appendTo("#"+element.attr("id")+"_error");
								} else {
									error.appendTo("#"+element.attr("name")+"_error");
								}
								break;
						}			
					}
				});
			}); 
			</script>
            <fieldset class="fieldsetcontainer">
                <legend>Voucher Details</legend>
                <div class="panel-body well-sm makerelative">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("voucher_servicetypeid_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-md-8">
                            	<?php 
									$servicetype = isArrayKeyAnEmptyString($voucher->getServiceTypeID(), $services) ? '': $services[$voucher->getServiceTypeID()];
									if($voucher->getType() == 2 && !isEmptyString($voucher->getParentID())){
										$isfollowalong = true;
										$servicetype = isArrayKeyAnEmptyString($voucher->getServiceTypeID(), $faservices) ? '': $faservices[$voucher->getServiceTypeID()];
									}
								?>
                                <p class="form-control-static nullifempty view"><?php echo $servicetype; ?></p>
                                <div class="edit">
                                    <?php
										$types = $services;
										if($isfollowalong){
											$types = $faservices; 
										}
                                        $dropdown = new Zend_Form_Element_Select('servicetypeid',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $types),
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('form-control','input-sm','width150')
                                                            )
                                        );  
                                        $dropdown->setValue($voucher->getServiceTypeID()); 
                                        echo $dropdown->render();
                                    ?>
                                    <div id="servicetypeid_error"></div>
                                </div>
                            </div>
                        </div>
                        <?php if($isfollowalong){ ?>
                        	<div class="form-group">
                                <label class="col-md-4 control-label"><?php echo $this->translate("voucher_favoucherno_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                <div class="col-md-8">
                                    <p class="form-control-static nullifempty view"><?php echo $voucher->getfavoucherno(); ?></p>
                                    <div class="edit">
                                        <input type="text" class="form-control input-sm width125" id="favoucherno" name="favoucherno" value="<?php echo $voucher->getfavoucherno(); ?>" />
                                        <div id="favoucherno_error"></div>
                                    </div>
                                </div>
                            </div>
                     	<?php } ?>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("voucher_voucherno_label"); ?>: 
                                <?php if(!$isfollowalong){ ?>    
                                	<?php echo $this->translate("global_required_field_marker"); ?>
                                <?php } ?>
                            <?php if($step == 'new'){ ?>
                                <span class="pagedescription blocked">After Approval</span>
                            <?php } ?>
                            </label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo $voucher->getvoucherno(); ?></p>
                                <div class="edit">
                                    <input type="text" class="form-control input-sm width125" id="voucherno" name="voucherno" value="<?php echo $voucher->getvoucherno(); ?>" />
                                    <div id="voucherno_error"></div>
                                </div>
                            </div>
                        </div>
                        
                        <?php if(!$isfollowalong){ ?>
                            <div class="form-group" id="intensive">
                                <label class="col-md-4 control-label">
                                	<?php if($step != 'view'){ ?>
                                    	<div class="divider30"></div>
									<?php } ?>
									<?php echo $this->translate("voucher_faprefix_label"); ?>:
                                    <?php if(!isEmptyString($voucher->getfaprefix())){ ?>
                                    	<div class="divider5"></div>
                                        <label class="pagedescription">For Intensive Vouchers only</label>
                                    <?php } ?>
                                </label>
                                <div class="col-md-8">
                                    <p class="form-control-static nullifempty view"><?php echo $voucher->getfaprefix(); ?></p>
                                    <div class="edit">
                                        <label class="checkbox-inline" style="margin-bottom:5px;"><input type="checkbox" name="type" id="type" value="<?php echo $voucher->getType(); ?>" <?php echo isEmptyString($voucher->getfaprefix()) ? '': 'checked'; ?> /> This Voucher is Intensive</label>
                                        <input type="text" class="form-control input-sm width125" id="faprefix" name="faprefix" value="<?php echo $voucher->getfaprefix(); ?>" />
                                        <div id="faprefix_error"></div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                        <div class="form-group">
                            <label class="col-md-4 control-label">
                            	<?php if(!$isfollowalong){ ?>
									<?php echo $this->translate("voucher_units_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?>
                                <?php } else { ?>
                                	<?php echo $this->translate("voucher_faunits_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?>
                                <?php } ?>
                            </label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo $voucher->getHours(); ?></p> 
                                <div class="edit">
                                    <input type="text" class="form-control input-sm width100 isdecimal computeamount" id="hours" name="hours" value="<?php echo $voucher->getHours(); ?>" />
                                    <input type="hidden" class="form-control" name="hours_old" id="hours_old" value="<?php echo $voucher->getHours(); ?>" />
                                    <div id="hours_error"></div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("voucher_voucherrate_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo isEmptyString($voucher->getRate()) ? '' : $config->country->currencysymbol.$voucher->getRate().'/Hr'; ?></p> 
                                <div class="edit">
                                    <input type="text" class="form-control input-sm width100 isdecimal computeamount" id="rate" name="rate" value="<?php echo $voucher->getRate(); ?>" />
                                    <input type="hidden" class="form-control" name="rate_old" id="rate_old" value="<?php echo $voucher->getRate(); ?>" />
                                    <div id="rate_error"></div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("voucher_voucheramount_label"); ?> <?php echo '<small>($)</small>'; ?>:</label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo $voucher->getHours() * $voucher->getRate(); ?></p>
                                <div class="edit">
                                    <span id="amount_computed"><?php echo $voucher->getHours() * $voucher->getRate(); ?></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                    	<div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("voucher_status_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($voucher->getStatus(), $voucherstatuses) ? '' : $voucherstatuses[$voucher->getStatus()]; ?></p>
                                <div class="edit">
                                    <?php
										$dropdown = new Zend_Form_Element_Select('status',
															array(
																'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $voucherstatuses),
																'view' => new Zend_View(),
																'decorators' => array('ViewHelper'),
																'class' => array('form-control','input-sm','width150')
															)
										);  
										$dropdown->setValue($voucher->getStatus()); 
										echo $dropdown->render();
									?><div id="status_error"></div>
                                </div>      
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("voucher_dateapproved_label"); ?>: 
								<?php if(!$isfollowalong){ ?>	
                                    <?php echo $this->translate("global_required_field_marker"); ?>
                                <?php } ?>
                            </label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo changeMySQLDateToPageFormat($voucher->getDateApproved()); ?></p>
                                <div class="edit">
                                    <input type="text" class="form-control input-sm datefield readonly width100" name="dateapproved" id="dateapproved" value="<?php echo changeMySQLDateToPageFormat($voucher->getDateApproved()); ?>" />
                                    <div id="dateapproved_error"></div>
                                </div>      
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label">
                            	<?php if(!$isfollowalong){ ?>	
                                    <?php echo $this->translate("voucher_startdate_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?>
                                <?php } else { ?>
									<?php echo $this->translate("voucher_fastartdate_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?>
                                <?php } ?>
                            </label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo changeMySQLDateToPageFormat($voucher->getstartdate()); ?></p>
                                <div class="edit">
                                    <input type="text" class="form-control input-sm datefield readonly width100" name="startdate" id="startdate" value="<?php echo changeMySQLDateToPageFormat($voucher->getstartdate()); ?>" />
                                    <div id="startdate_error"></div>
                                </div>      
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><?php echo $this->translate("voucher_days_label"); ?>:</label>
                            <div class="col-md-8">
                                <p class="form-control-static nullifempty view"><?php echo $voucher->getDays(); ?></p> 
                                <div class="edit">
                                    <input type="text" class="form-control input-sm width100 isdecimal" id="days" name="days" value="<?php echo $voucher->getdays(); ?>" />
                                    <input type="hidden" class="form-control" name="days_old" id="days_old" value="<?php echo $voucher->getdays(); ?>" />
                                    <div id="days_error"></div>
                                </div>
                            </div>
                        </div>
                        <?php if(!$isfollowalong && false){ ?>		
                            <div class="form-group">
                                <label class="col-md-4 control-label"><?php echo $this->translate("voucher_invoicedate_label"); ?>:</label>
                                <div class="col-md-8">
                                    <p class="form-control-static nullifempty view"><?php echo changeMySQLDateToPageFormat($voucher->getinvoicedate()); ?></p>
                                    <div class="edit">
                                        <input type="text" class="form-control input-sm datefield readonly width100" name="invoicedate" id="invoicedate" value="<?php echo changeMySQLDateToPageFormat($voucher->getinvoicedate()); ?>" />
                                        <div id="invoicedate_error"></div>
                                    </div>      
                                </div>
                            </div>
                       	<?php } ?>
                        <?php if($isfollowalong){ ?>		
                            <div class="form-group">
                                <label class="col-md-4 control-label"><?php echo $this->translate("voucher_enddate_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                <div class="col-md-8">
                                    <p class="form-control-static nullifempty view"><?php echo changeMySQLDateToPageFormat($voucher->getenddate()); ?></p>
                                    <div class="edit">
                                        <input type="text" class="form-control input-sm datefield readonly width100" name="enddate" id="enddate" value="<?php echo changeMySQLDateToPageFormat($voucher->getenddate()); ?>" />
                                        <div id="enddate_error"></div>
                                    </div>      
                                </div>
                            </div>
                       	<?php } ?>
                    </div>
                </div>
            </fieldset>
            <?php if($step == 'view'){ ?>       
                <fieldset class="fieldsetcontainer">
                    <legend>Intervention Summary</legend>
                    <div class="panel-body well-sm makerelative">
                        <div class="col-md-9">
                            <div class="form-group">
                                <label class="col-md-4 control-label">Hours Utilised To-date:</label>
                                <div class="col-md-8">
                                    <p class="form-control-static nullifempty view"><?php echo $voucher->getHoursUsed(); ?></p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label">Hours Available:</label>
                                <div class="col-md-8">
                                    <p class="form-control-static nullifempty view"><?php echo $voucher->getHoursRemaining(); ?></p>
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <label class="col-md-4 control-label">Executed By:</label>
                                <div class="col-md-8">
                                    <p class="form-control-static nullifempty view">
									<?php 
										$history = $voucher->getClient()->getCurrentAssignedCoach();
										if($history){
											echo '<a href="'.$this->baseUrl('profile/view/id/'.encode($history->getUserID())).'">'.$history->getUser()->getName().'</a>';
										}
									?>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <fieldset class="fieldsetcontainer">
                    <legend>Latest Intervention Details</legend>
                    <?php $activity = $voucher->getLatestActivity(); ?>
                    <div class="panel-body well-sm makerelative">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-md-12 control-label"><?php echo $this->translate("activity_progressofintervention_label"); ?>:</label>
                                <div class="col-md-12">
                                    <p class="form-control-static nullifempty view"><?php echo $activity->getprogressofintervention(); ?></p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12 control-label"><?php echo $this->translate("activity_expectedperformance_label"); ?>:</label>
                                <div class="col-md-12">
                                    <p class="form-control-static nullifempty view"><?php echo $activity->getexpectedperformance(); ?></p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12 control-label"><?php echo $this->translate("activity_actualperformance_label"); ?>:</label>
                                <div class="col-md-12">
                                    <p class="form-control-static nullifempty view"><?php echo $activity->getactualperformance(); ?></p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12 control-label"><?php echo $this->translate("activity_interventionplan_label"); ?>:</label>
                                <div class="col-md-12">
                                    <p class="form-control-static nullifempty view"><?php echo $activity->getinterventionplan(); ?></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
            <?php } ?>  
        <?php } ?>
        <?php if(isEmptyString($request->vid) && $step == 'view') { ?>
            <div class="divider5"></div>
            <div class="col-md-12 padding0">
            	<div class="listcontainer">
                    <table class="table list table-striped table-responsive viewtable" style="max-width:800px;">
                        <thead>
                            <tr>
                                <th class="centeralign" style="width:15px;">#</th>
                                <th class="nowrapping">Voucher ID# <img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:15px; height:2px;" /></th>
                                <th class="nowrapping">Service Type <img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:35px; height:2px;" /></th>
                                <th class="nowrapping">Funder <img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:25px; height:2px;" /></th>
                                <th class="nowrapping">Status <img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:75px; height:2px;" /></th>
                                <th class="nowrapping">Date Approved <img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:10px; height:2px;" /></th>
                                <th class="nowrapping">Start Date <img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:20px; height:2px;" /></th>
                                <th class="nowrapping">Hrs Approved</th>
                                <th class="nowrapping">Rate ($/Hr)<img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:20px; height:2px;" /></th>
                            </tr>
                        </thead>
                        <tbody>
                           <?php 
                                $counter = 1;
                                foreach($vouchers as $voucher){ 
									$isfollowalong = false;
									$servicetype = isArrayKeyAnEmptyString($voucher->getServiceTypeID(), $services_noalias) ? '': $services_noalias[$voucher->getServiceTypeID()];
									if($voucher->getType() == 2 && !isEmptyString($voucher->getParentID())){
										$isfollowalong = true;
										$servicetype = isArrayKeyAnEmptyString($voucher->getServiceTypeID(), $faservices_noalias) ? '': $faservices_noalias[$voucher->getServiceTypeID()];
									}
                            ?>
                                <tr>
                                    <td class="centeralign"><?php echo $counter; ?></td>
                                    <td>
                                    	<?php if($isfollowalong){ ?>
                                    		<a href="<?php echo $baseview.'/step/view/vid/'.encode($voucher->getID()); ?>"><?php echo $voucher->getfavoucherno(); ?></a>
                                       	<?php } else { ?>
                                        	<a href="<?php echo $baseview.'/step/view/vid/'.encode($voucher->getID()); ?>"><?php echo $voucher->getvoucherno(); ?></a>
                                        <?php } ?>
                                    </td>
                                    <td><?php echo $servicetype; ?></td>
                                    <td><?php echo isArrayKeyAnEmptyString($voucher->getClient()->getFunderID(), $funders) ? '': $funders[$voucher->getClient()->getFunderID()]; ?></td>
                                    <td><?php echo isArrayKeyAnEmptyString($voucher->getStatus(), $voucherstatuses) ? '' : $voucherstatuses[$voucher->getStatus()]; ?></td>
                                    <td><?php echo formatDateAndTime($voucher->getDateApproved(), false); ?></td>
                                    <td><?php echo formatDateAndTime($voucher->getStartDate(), false); ?></td>
                                    <td class="centeralign"><?php echo $voucher->gethours(); ?></td>
                                    <td><?php echo $voucher->getRate(); ?></td>
                                </tr>
                            <?php $counter++; } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        <?php } ?>
        	
    </div>
</form>