<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$user = new UserAccount(); 

	$id = decode($request->id);
	if(isEmptyString($id)){
		$id = $userid;
	}
	$user->populate($id);
	// debugMessage($user->toArray());
	$posturl = "";
	
	$tab = $request->tab;
	if(isEmptyString($tab)){
		$tab = 'profile';
		if($request->detect == '1'){
			$posturl = $this->baseUrl("profile/processgps");
		}
	}
	if($tab == 'settings'){
		$crops = $user->getUserCrops();
		$count_crops = $crops->count();
		
		$markets = $user->getUserMarkets();
		$count_markets = $markets->count();
		
		$fuelstations = $user->getUserFuelStations();
		$count_fuelstations = $fuelstations->count();
		
		$districts = $user->getUserDistricts();
		$count_districts = $districts->count();
		
		$categories = $user->getUserForumCategories();
		$count_categories = $categories->count();
	}
	
	$isme = true;
	if($user->getID() != $userid){
		$isme = false;
	}
	
	$viewurl = $this->baseUrl('profile/view/id/'.encode($user->getID()));
	$indexurl = $this->baseUrl('profile/index/id/'.encode($user->getID()));
	$listurl = $this->baseUrl('profile/list');
	$listitems = $this->translate("profile_list_items");
	$title = $user->getName();
	$this->headTitle($title); 
?>
<?php if($tab == 'profile' && loadMaps()){ ?>
	<script src="<?php echo getGoogleMapsUrl(); ?>" type="text/javascript"></script>
	<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('plugins/gmaps/gmaps.min.js')); ?>"></script>
    <script src="<?php echo $this->baseUrl('plugins/gmaps/geoPosition.js'); ?>"></script>
<?php } ?>
<script>
$(document).ready(function() {
	// breadcrumb config
	$("#levelone_icon").addClass('icon-user-md');
	$("#levelone_link").attr('href', '<?php echo $listurl; ?>').html('<?php echo $listitems; ?>');
	$("#leveltwo_link").html('Profile Details');
	
	$("ul.nav.nav-tabs li a").click(function(){
		var url = $(this).attr('goto');
		var id = $(this).attr('theid');
		if(!isEmptyString(url) && url != 'undefined'){
			$(".tab-content #"+id).html("<a id='loading' class='xhidden' style='text-align:center; display:block; margin-top:75px;'><span style='display:block; margin-bottom:15px; font-weight:bold;'>Loading...</span><img style='margin-left:-10px;' src='<?php echo $this->baseUrl('images/ui-anim_basic_16x16.gif'); ?>' /></a>").css({'display':'block'});
			window.location.href = url;
		}
	}); 
	
	$("#confirmphone").click(function(){
		var code = $("#code").val();
		var id = $(this).attr('userid');
		var ref = $(this).attr('ref');
		
		var validcode = true;
		var clength = code.length;
		if(isEmptyString(code) || (!isEmptyString(code) && clength < 6)) {
			$("div#code_phone_error").html('<div class="alert alert-danger">Please enter 6 digit code</div>');
			validcode = false;
		}
		// check that email is provided
		if(validcode) {
			$("div#code_phone_error").html('');
			var url = '<?php echo $this->baseUrl("profile/changephone"); ?>/id/'+id+'/actkey/'+code+'/ref/'+ref;
			// alert(url);
			window.location.href = url;
		}
	});
	
	<?php if($tab == 'profile' && $user->hasGPSCoordinates() && isEmptyString($request->detect) && loadMaps()){ ?>
		var gpslat = '<?php echo $user->getgpslat(); ?>';
		var gpslng = '<?php echo $user->getgpslng(); ?>';
		var title = "<?php echo $isme ? 'My Location' : $user->getFirstName()."'s Location "; ?>";
		var map = new GMaps({
			div: '#map_canvas',
			lat: gpslat,
			lng: gpslng,
			scrollwheel: false,
			mapTypeControl: false,
			scaleControl: true,
			mapTypeId: google.maps.MapTypeId.ROADMAP, // google map type
			zoom: 8
		});
		map.addMarker({
			lat: gpslat,
			lng: gpslng,
			title: "<?php echo $isme ? 'My Location' : $user->getFirstName()."'s Location "; ?>",
			infoWindow: {
				content: '<span><b>'+title+'</b><br /> Lat: '+gpslat+'<br />Lng: '+gpslng+'</span>'
			}
		});
		
	<?php } ?>
	<?php if($tab == 'profile' && $user->hasGPSCoordinates() && !isEmptyString($request->detect) && loadMaps()){ ?>
		initialiseMap();
		initialise();
		
	<?php } ?>
	
}); 
</script>
<script type="text/javascript">
	// initialise the google map
	function initialiseMap(){
		var myOptions = {
			  zoom: 14,
			  mapTypeControl: true,
			  mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
			  navigationControl: true,
			  navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
			  mapTypeId: google.maps.MapTypeId.ROADMAP      
			}        
		map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
	}
	function initialise() {
		if(geoPosition.init()){
			document.getElementById('current').innerHTML="Receiving location... please wait...";
			geoPosition.getCurrentPosition(
				showPosition,
				function(){
					document.getElementById('current').innerHTML="Couldn't get location"
				},
				{maximumAge:60000, timeout:10000, enableHighAccuracy:true}
			);
		} else {
			document.getElementById('current').innerHTML="Your Browser is not supported for this function";
		}
	}

	function showPosition(p){
		var latitude = parseFloat(p.coords.latitude);
		latitude = latitude.toFixed(6);
		
		var longitude = parseFloat(p.coords.longitude);
		longitude = longitude.toFixed(6);
		
		$("#lat").val(latitude);
		$("#lng").val(longitude);
		if(!isEmptyString(latitude) && !isEmptyString(longitude)){
			$("#hasgps").val(latitude+','+longitude);
		}
		document.getElementById('current').innerHTML=" Latitude = "+latitude+ " <br />Longitude = "+longitude;
		var pos=new google.maps.LatLng(latitude, longitude);
		map.setCenter(pos);
		map.setZoom(18);

		var infowindow = new google.maps.InfoWindow({
			content: "<strong>Your Location</strong>"
		});

		var marker = new google.maps.Marker({
			position: pos,
			map: map,
			title:"You are here"
		});

		google.maps.event.addListener(marker, 'click', function() {
		  infowindow.open(map,marker);
		});
	}             
</script> 

<!--=== Page Header ===-->
<div class="page-header">
    <div class="page-title">
        <h3><?php echo $title; ?></h3>
        <span>Profile details</span>
    </div>
</div>
<!--=== Page Content ===-->
    <div class="form-actions fluid" id="topactions">
        <div class="row">
            <div class="col-md-12">
                <div class="xcol-md-offset-2 xcol-md-10 floatright">
                    <?php if ($acl->checkPermission('User Account', ACTION_DELETE) && $tab == 'settings' && !$user->isUserActive() && !$isme) { ?>
                        <a class="btn btn-sm btn-danger deleteline gonowhere" action="<?php echo $this->baseUrl('profile/delete/id/'.encode($user->getID())."/entityname/UserAccount/successurl/".encode($listurl)); ?>" message="<?php echo $this->translate('global_delete_confirm_message'); ?>"><i class="icon-trash"></i> Delete</a> 
                    <?php } ?>
                    <?php if ($acl->checkPermission('User Account', ACTION_DELETE) && $tab == 'settings' && $user->isDeactivated() && !$isme) { ?>
                        <a class="btn btn-sm btn-warning confirm-dialog deactivate" action="<?php echo $this->baseUrl("profile/updatestatus/id/".encode($user->getID())."/status/1/successmessage/profile_reactivate_success/successurl/".encode($this->viewurl)); ?>" message="<?php echo $this->translate('useraccount_profile_reactivate_confirmation'); ?>" ><i class="icon-remove"></i> Reactivate</a> 
                    <?php } ?>
                    <?php if ($acl->checkPermission('User Account', ACTION_DELETE) && $tab == 'settings' && $user->isUserActive() && !$isme) { ?>
                        <a class="btn btn-sm btn-warning confirm-dialog deactivate" action="<?php echo $this->baseUrl("profile/updatestatus/id/".encode($user->getID())."/status/2/successmessage/profile_deactivate_success/successurl/".encode($this->viewurl)); ?>" message="<?php echo $this->translate('useraccount_profile_deactivate_confirmation'); ?>" ><i class="icon-remove"></i> Deactivate</a> 
                    <?php } ?>
                    <?php if ($acl->checkPermission('User Account', ACTION_LIST)) { ?>
                    	<a class="btn btn-sm btn-default" href="<?php echo $listurl; ?>"><i class="icon-user"></i> More Profiles</a>&nbsp;
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
<?php if ($sessionhaserror) { ?>
    <div class="alert alert-danger fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
<?php } ?>
<?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
    <div class="alert alert-success fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
<?php } ?>
<?php if (!isEmptyString($session->getVar('invitesuccess'))) { ?>
    <div class="alert alert-success fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar('invitesuccess'); ?></div>
<?php } ?>
<?php if (!isEmptyString($session->getVar('custommessage'))) { ?>
    <div class="alert alert-success fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar('custommessage'); ?></div>
<?php } ?>
<?php if (!isEmptyString($session->getVar('custommessage1'))) { ?>
    <div class="alert alert-success fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar('custommessage1'); ?></div>
<?php } ?>
<?php if (!isEmptyString($session->getVar('custommessage5'))) { ?>
    <div class="alert alert-warning fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar('custommessage5'); ?></div>
<?php } ?>
<?php if(!isEmptyString($user->hasPendingActivation()) && $acl->checkPermission('User Account', ACTION_CREATE)) { ?>
    <div class="alert alert-warning fade in">Activation pending from user</div>
<?php } ?>
<?php if($acl->checkPermission('User Account', ACTION_DELETE) && $user->isDeactivated()) { ?>
    <div class="alert alert-warning fade in">User profile was de-activated</div>
<?php } ?>
<form class="form-horizontal clearfix" id="viewform" action="<?php echo $posturl; ?>" method="post">
<div class="row margin0">
    <div class="col-md-12">
        <!-- Tabs-->
        <div class="tabbable tabbable-custom tabbable-full-width">
            <ul class="nav nav-tabs">
                <?php if ($acl->checkPermission('User Account', ACTION_VIEW)) { ?>
                	<li class="<?php echo $tab == 'profile' ? 'active gonowhere' : ''; ?>"><a href="#overview" goto="<?php echo $this->baseUrl('profile/view/id/'.encode($user->getID())); ?>" theid="overview" data-toggle="tab">Overview</a></li>
                <?php } ?>
                <?php if ($acl->checkPermission('User Account', ACTION_EDIT) && ($isme || !isPublicUser())) { ?>
                	<li><a href="#updateaccount" theid="updateaccount" goto="<?php echo $this->baseUrl('profile/index/id/'.encode($user->getID())); ?>" data-toggle="tab">Update Profile</a></li>
                <?php } ?>
                <?php if($tab == 'settings' && !isPublicUser()){ ?>
                	<li class="<?php echo $tab == 'settings' ? 'active gonowhere' : ''; ?>"><a>Settings</a></li>
                <?php } ?>
                <?php if($tab == 'subscription' && !isPublicUser()){ ?>
                	<li class="<?php echo $tab == 'subscription' ? 'active gonowhere' : ''; ?>"><a>Subscription</a></li>
                <?php } ?>
                <?php if($tab == 'payments' && $user->isSubscriber() && !isPublicUser()){ ?>
                	<li class="<?php echo $tab == 'payments' ? 'active gonowhere' : ''; ?>"><a>Payments</a></li>
                <?php } ?>
            </ul>
            <div class="tab-content row" style="border-bottom:2px dashed #666; padding-bottom:0;">
            	<?php if ($acl->checkPermission('User Account', ACTION_VIEW)) { ?>
                    <div class="tab-pane active" id="overview">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="list-group">
                                    <li class="list-group-item no-padding" style="padding-left:15%; padding-right:15%;">
                                    	<div class="divider5"></div>
                                    	<?php if($isme || isAdmin()){ ?>
                                        	<a href="<?php echo $this->baseUrl('profile/index/id/'.encode($user->getID()).'/tab/picture'); ?>" class="editpic imagecontainer" title="Update Profile Photo"><img id="profileimage" class="imagecontainer" src="<?php echo $user->getMediumPicturePath(); ?>" style="width:100%;" /><pre id="uploadlink" class=""><i class="icon-pencil"></i> Upload Photo</pre></a>
                                        <?php } else { ?>
                                            <img id="profileimage" class="imagecontainer" src="<?php echo $user->getMediumPicturePath(); ?>" style="width:100%;" />
                                            <div class="divider10"></div>
                                        <?php } ?>
                                    </li>
                                    <a class="list-group-item <?php echo $tab == 'profile' ? 'gonowhere active' : ''; ?>" href="<?php echo $this->baseUrl('profile/view/id/'.encode($user->getID())); ?>">Profile</a>
                                    <?php if($isme || !isPublicUser()){ ?>
                                    <a class="list-group-item <?php echo $tab == 'subscription' ? 'gonowhere active' : ''; ?>" href="<?php echo $this->baseUrl('profile/view/id/'.encode($user->getID()).'/tab/subscription'); ?>">Subscription</a>
                                    <?php } ?>
                                    <?php if(($isme || !isPublicUser()) && $user->isSubscriber()){ ?>
                                    	<a class="list-group-item <?php echo $tab == 'payments' ? 'gonowhere active' : ''; ?>" href="<?php echo $this->baseUrl('profile/view/id/'.encode($user->getID()).'/tab/payments'); ?>">Payments</a>
                                    <?php } ?>
                                    <?php if(($isme || !isPublicUser())){ ?>
                                    	<a class="list-group-item <?php echo $tab == 'settings' ? 'gonowhere active' : ''; ?>" href="<?php echo $this->baseUrl('profile/view/id/'.encode($user->getID()).'/tab/settings'); ?>">Settings & Preferrences</a>
                                    <?php } ?>
                                </div>
                                <?php if($tab == 'settings' && ($isme || !isPublicUser())){ ?>
                                	<div class="row">
                                        <div class="widget-header" style="margin-left:15px;">
                                            <h4><i class="icon-reorder"></i> Login Settings</h4>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="col-md-12 leftalignlabel">
                                        	<div class="form-group"> 
                                            	<label class="col-md-12 control-label"><?php echo $this->translate('profile_email_label'); ?>:</label>
                                                <div class="col-md-12 nullifempty"><?php echo $user->getEmail(); ?></div>
                                            </div>
                                            <?php if(!isEmptyString($user->getEmail2()) && !isEmptyString($user->getActivationKey())){ ?>
                                            	<div class="divider20"></div>
                                                <div class="form-group"> 
                                                    <label class="col-md-12 control-label">New Email Requested:</label>
                                                    <div class="col-md-12 nullifempty"><?php echo $user->getEmail2(); ?>
                                                        <div class="alert alert-warning fade in">Pending activation</div>
                                                    </div>
                                                </div>
                                            <?php } ?>
                                            <div class="divider20"></div>
                                            <div class="form-group"> 
                                            	<label class="col-md-12 control-label"><?php echo $this->translate('profile_username_label'); ?>:</label>
                                                <div class="col-md-12 nullifempty"><?php echo $user->getUsername(); ?></div>
                                            </div>
                                            <div class="divider20"></div>
											<div class="form-group"> 
                                            	<label class="col-md-12 control-label"><?php echo $this->translate('profile_phone_label'); ?>:</label>
                                                <div class="col-md-12 nullifempty"><?php echo $user->getFormattedPhone(); ?></div>
                                            </div>
                                            <?php if(!isEmptyString($user->getPhone2()) && !isEmptyString($user->getphone2_actKey())){ ?>
                                            	<div class="divider20"></div>
                                            	<div class="form-group"> 
                                                    <label class="col-md-12 control-label">New Phone Requested:</label>
                                                    <div class="col-md-12 nullifempty"><?php echo getShortPhone($user->getPhone2()); ?>
                                                    	<div class="divider5"></div>
                                                        <span class="blocked" style="padding-top:5px; margin-bottom:0; padding-bottom:0;">
                                                            <input type="text" name="code" id="code" placeholder="enter 6 digit code" title="Confirm Phone" value="" maxlength="6" style="width:125px; padding:3px;" class="form-control padding3" />
                                                            <a class="btn btn-sm btn-primary gonowhere" id="confirmphone" userid="<?php echo encode($user->getID()); ?>" ref="<?php echo encode($user->getPhone2()); ?>" title="Confirm Phone"><i class="icon-envelope icon-white"></i> Confirm</a>
                                                            <div id="code_phone_error" style="margin-top:2px;"></div>
                                                        </span>
                                                        <div class="divider5"></div>
                                                        <div class="alert alert-warning fade in">Pending activation</div>
                                                    </div>
                                                </div>
                                            <?php } ?>
                                            <?php if ($acl->checkPermission('User Account', ACTION_CREATE) && !isPublicUser()) { ?>
                                                <div class="divider20"></div>
                                                <div class="form-group"> 
                                                    <label class="col-md-12 control-label">Account Status:</label>
                                                    <div class="col-md-12 nullifempty"><?php echo getUserStatus($user->getIsActive()); ?></div>
                                                </div>
                                            <?php } ?>
                                            <?php if (!$user->isDeactivated()) { ?>    
                                                <div class="divider20"></div>
                                                <div class="form-group"> 
                                                    <label class="col-md-12 control-label"><?php echo $this->translate('useraccount_password_label'); ?>:</label>
                                                    <div class="col-md-12 nullifempty">
                                                        <?php if($isme){ ?>
                                                            <a class="changepassword btn btn-info btn-sm" id="changepassword" rel="Change Password" href="<?php echo $this->baseUrl('profile/index/id/'.encode($user->getID())); ?>">Change Password</a>
                                                        <?php } ?>
                                                        <?php if ($acl->checkPermission('User Account', ACTION_CREATE) || isAdmin()) { ?>
                                                            <a class="confirm-dialog btn btn-info btn-sm" id="resetpassword" action="<?php echo $this->baseUrl('profile/resetpassword/id/'.encode($user->getID())); ?>" message="Are you sure you want to reset <?php echo $user->getName() ?>'s Password?">Reset Password</a>
                                                        <?php } ?>
                                                    </div>
                                                </div>
                                            <?php } ?>
                                            <div class="divider20"></div>
                                        </div>
                                   	</div>
                                <?php } ?>    
                            </div>
                            <div class="col-md-9 form-horizontal xpadding0">
                            	<?php if($tab == 'profile'){ ?>
                                    <div class="row profile-info">
                                        <div class="col-md-6 leftalignlabel" style="xpadding-right:0;">
                                            <div class="form-group clearfix">
                                                <label class="col-md-4 control-label"><?php echo $this->translate("profile_firstname_label"); ?>:</label>
                                                <div class="col-md-8 nullifempty"><?php echo $user->getFirstName(); ?></div>
                                            </div>
                                            <div class="divider5"></div>
                                            <div class="form-group clearfix">
                                                <label class="col-md-4 control-label"><?php echo $this->translate("profile_lastname_label"); ?>:</label>
                                                <div class="col-md-8 nullifempty"><?php echo $user->getLastName(); ?></div>
                                            </div>
                                            <?php if(!isEmptyString($user->getOtherName())){ ?>
                                                <div class="divider5"></div>
                                                <div class="form-group clearfix">
                                                    <label class="col-md-4 control-label"><?php echo $this->translate("profile_othernames_label"); ?>:</label>
                                                    <div class="col-md-8 nullifempty"><?php echo $user->getOtherName(); ?></div>
                                                </div>
                                            <?php } ?>
                                            <div class="divider5"></div>
                                            <div class="form-group clearfix">
                                                <label class="col-md-4 control-label"><?php echo $this->translate("profile_username_label"); ?>:</label>
                                                <div class="col-md-8 nullifempty"><?php echo $user->getUsername(); ?></div>
                                            </div>
                                            <div class="divider5"></div>
                                            <div class="form-group clearfix">
                                                <label class="col-md-4 control-label">Type:</label>
                                                <div class="col-md-8 nullifempty"><?php echo $user->getUserTypeText(); ?></div>
                                            </div>
                                            <?php if($user->isAMIA()){ ?>
                                            	<div class="divider5"></div>
                                                <div class="form-group clearfix">
                                                    <label class="col-md-4 control-label"><?php echo $this->translate("profile_market_label"); ?>:</label>
                                                    <div class="col-md-8"><a href="<?php echo $this->baseUrl('pricesource/view/id/'.encode($user->getMarketID())); ?>"><?php echo $user->getMarket()->getName(); ?></a>
                                                    </div>
                                                </div>
                                            <?php } ?>
                                            <?php if($user->isOrganisation()){ ?>
                                            	<div class="divider5"></div>
                                                <div class="form-group clearfix">
                                                    <label class="col-md-4 control-label"><?php echo $this->translate("profile_organisation_label"); ?>:</label>
                                                    <div class="col-md-8 nullifempty"><?php echo $user->getOrganisation()->getName(); ?></div>
                                                </div>
                                                <div class="divider5"></div>
                                            <?php } ?>
                                            <div class="divider5"></div>
                                            <div class="form-group clearfix">
                                                <label class="col-md-4 control-label"><?php echo $this->translate("profile_gender_label"); ?>:</label>
                                                <div class="col-md-8 nullifempty"><?php echo $user->getGenderText(); ?></div>
                                            </div>
                                            <?php if(!isEmptyString($user->getDateofBirth())){ ?>
                                            	<?php if(!isPublicUser() || $isme || ($user->getShowBirth() == 1 && isPublicUser())){ ?>
                                                    <div class="divider5"></div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-4 control-label"><?php echo $this->translate("profile_dateofbirth_label"); ?>:</label>
                                                        <div class="col-md-8 nullifempty"><?php echo changeMySQLDateToPageFormat($user->getDateofBirth()); ?></div>
                                                    </div>
                                               	<?php } ?>
                                            <?php } ?>
                                            <?php if(!isPublicUser() || isAMIA() || $isme || ($user->getShowPhone() == 1 && isPublicUser())){ ?>
                                                <div class="divider5"></div>
                                                <div class="form-group clearfix">
                                                    <label class="col-md-4 control-label"><?php echo $this->translate("profile_phone_label"); ?>:</label>
                                                    <div class="col-md-8 nullifempty"><?php echo $user->getFormattedPhone(); ?></div>
                                                </div>
                                            <?php } ?>
                                            <?php if(!isEmptyString($user->getPhone2()) && !isEmptyString($user->getphone2_actKey()) && !isPublicUser()){ ?>
                                            	<div class="divider5"></div>
                                                <div class="form-group clearfix">
                                                    <label class="col-md-4 control-label">New Phone Requested:</label>
                                                    <div class="col-md-8 nullifempty"><?php echo getShortPhone($user->getPhone2()); ?>
                                                    	<div class="divider5"></div>
                                                        <span class="blocked" style="padding-top:5px; margin-bottom:0; padding-bottom:0;">
                                                            <input type="text" name="code" id="code" placeholder="enter 6 digit code" title="Confirm Phone" value="" maxlength="6" style="width:125px; padding:3px;" class="form-control padding3" />
                                                            <a class="btn btn-sm btn-primary gonowhere" id="confirmphone" userid="<?php echo encode($user->getID()); ?>" ref="<?php echo encode($user->getPhone2()); ?>" title="Confirm Phone"><i class="icon-envelope icon-white"></i> Confirm</a>
                                                            <div id="code_phone_error" style="margin-top:2px;"></div>
                                                        </span>
                                                        <div class="divider5"></div>
                                                        <div class="alert alert-warning fade in">Pending activation</div>
                                                    </div>
                                                </div>
                                            <?php } ?>
                                            <?php if(!isPublicUser() || isAMIA() || $isme || ($user->getShowEmail() == 1 && isPublicUser())){ ?>
                                                <div class="divider5"></div>
                                                <div class="form-group clearfix">
                                                    <label class="col-md-4 control-label"><?php echo $this->translate("profile_email_label"); ?>:</label>
                                                    <div class="col-md-8 nullifempty"><?php echo $user->getEmail(); ?></div>
                                                </div>
                                            <?php } ?>
                                            <?php if(!isEmptyString($user->getEmail2()) && !isEmptyString($user->getActivationKey()) && !isPublicUser()){ ?>
                                            	<div class="divider5"></div>
                                                <div class="form-group clearfix">
                                                    <label class="col-md-4 control-label">New Email Requested:</label>
                                                    <div class="col-md-8 nullifempty"><?php echo $user->getEmail2(); ?>
                                                        <div class="alert alert-warning fade in">Pending activation</div>
                                                    </div>
                                                </div>
                                            <?php } ?>
                                            <div class="divider5"></div>
                                            <div class="form-group clearfix">
                                                <label class="col-md-4 control-label">Sector:</label>
                                                <div class="col-md-8 nullifempty"><?php echo getSectorAreas($user->getSector(), true); ?></div>
                                            </div>
                                        </div>
                                        <?php if(!isPublicUser() || isAMIA() || $isme || ($user->getShowBio() == 1 && isPublicUser())){ ?>
                                            <div class="col-md-6" style="margin-top:-10px;">
                                                <div class="widget">
                                                    <div class="widget-header">
                                                        <h4><i class="icon-reorder"></i> Biography</h4>
                                                    </div>
                                                    <div class="widget-content padding5">
                                                        <?php echo nl2br($user->getBiography()); ?>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                <?php if($tab == 'subscription' && ($isme || !isPublicUser())){ ?>
                                	<div class="row profile-info">
                                        <div class="widget-header" style="margin-left:15px;">
                                            <h4><i class="icon-reorder"></i> Current Subscription</h4>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="col-md-12 leftalignlabel">
                                            <div class="form-group clearfix">
                                                <label class="col-md-3 control-label">Account Type:</label>
                                                <div class="col-md-9 nullifempty"><?php echo $user->getUserTypeText(); ?></div>
                                            </div>
                                            <div class="divider5"></div>
                                            <div class="form-group clearfix">
                                                <label class="col-md-3 control-label">Date Joined:</label>
                                                <div class="col-md-9 nullifempty"><?php echo formatDateAndTime($user->getDateCreated(), false); ?></div>
                                            </div>
                                            <div class="divider5"></div>
                                            <div class="form-group clearfix">
                                                <label class="col-md-3 control-label">Activation Date:</label>
                                                <div class="col-md-9 nullifempty"><?php echo formatDateAndTime($user->getActivationDate(), false); ?></div>
                                            </div>
                                            <div class="divider5"></div>
                                            <div class="form-group clearfix">
                                                <label class="col-md-3 control-label">Subscription Start Date:</label>
                                                <div class="col-md-9 nullifempty"><?php echo formatDateAndTime($user->getActivationDate(), false); ?></div>
                                            </div>
                                            <div class="divider5"></div>
                                            <div class="form-group clearfix">
                                                <label class="col-md-3 control-label">Subscription End Date:</label>
                                                <div class="col-md-9 nullifempty"><?php echo formatDateAndTime(getLastDayOfMonth(12, 2014), false); ?></div>
                                            </div>
                                            <div class="divider5"></div>
										</div>
									</div>
                                    <div class="row profile-info">
                                        <div class="widget-header" style="margin-left:15px;">
                                            <h4><i class="icon-reorder"></i> Subscription History</h4>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="col-md-12 leftalignlabel">
                                        	<div class="alert alert-info fade in">No records available</div>
                                        </div>
                                    </div>                                                                                    
                                <?php } ?>
                                <?php if($tab == 'payments' && ($isme || !isPublicUser()) && $user->isSubscriber()){ ?>
                                	<div class="row profile-info">
                                        <div class="widget-header" style="margin-left:15px;">
                                            <h4><i class="icon-reorder"></i> Payment History</h4>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="col-md-12 leftalignlabel">
                                        	<div class="alert alert-info fade in">No payments received from this account</div>
                                        </div>
                                    </div>
                                <?php } ?> 
                                <?php if($tab == 'settings' && ($isme || !isPublicUser())){ ?>
                                	<div class="row">
                                        <div class="widget-header" style="margin-left:15px;">
                                            <h4><i class="icon-reorder"></i> Profile Preferences</h4>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="col-md-12 leftalignlabel">
                                        	<div class="form-group">
                                                <label class="col-md-12 control-label"><?php echo $isme == true ? $this->translate('profile_my_preffered_crops') : $this->translate('profile_preffered_crops'); ?>: <span class="labeldescription"><?php echo $count_crops == 0 ? 'None' : $count_crops; ?> currently profiled</span></label>
                                                <div class="col-md-12 nullifempty">
													<?php if($count_crops > 0){ ?>
                                                        <ul class="nav nav-tabs">
                                                            <?php foreach($crops as $setting){ ?>
                                                                <li style="margin-right:20px; margin-bottom:5px; float:left; width:160px;">
                                                                    <label style="color:#55A411; margin:5px 0; font-weight:bold;"><?php echo $setting->getCommodity()->getName(); ?></label>
                                                                    <img class="imagecontainer profileinfo" style="width:100%; height:120px;" src="<?php echo $setting->getCommodity()->getImagePath(); ?>" />
                                                                </li>
                                                            <?php } ?>
                                                        </ul>
                                                    <?php } ?>                                                    
                                                </div>
                                            </div>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="col-md-12 leftalignlabel">
                                        	<div class="form-group clearfix">
                                                <label class="col-md-12 control-label"><?php echo $isme == true ? $this->translate('profile_my_preffered_markets') : $this->translate('profile_preffered_markets'); ?>: <span class="labeldescription"><?php echo $count_markets == 0 ? 'None' : $count_markets; ?> currently profiled</span></label>
                                                <div class="col-md-12 nullifempty">
                                                	<?php if($count_markets > 0){ ?>
                                                    	<ul class="nav">
															<?php foreach($markets as $setting){ ?>
                                                                <li style="width:250px; display:inline-block; float:left; "><a href="<?php echo $this->baseUrl('pricesource/view/id/'.encode($setting->getID())); ?>"><?php echo $setting->getMarket()->getName(); ?></a></li>
                                                            <?php } ?>
                                                        </ul>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="col-md-12 leftalignlabel">
                                        	<div class="form-group clearfix">
                                                <label class="col-md-12 control-label"><?php echo $isme == true ? $this->translate('profile_my_preffered_fuelstations') : $this->translate('profile_preffered_fuelstations'); ?>: <span class="labeldescription"><?php echo $count_fuelstations == 0 ? 'None' : $count_fuelstations; ?> currently profiled</span></label>
                                                <div class="col-md-12 nullifempty">
                                                	<?php if($count_fuelstations > 0){ ?>
                                                    	<ul class="nav">
															<?php foreach($fuelstations as $setting){ ?>
                                                                <li style="width:250px; display:block;"><a href="<?php echo $this->baseUrl('pricesource/view/id/'.encode($setting->getID())); ?>"><?php echo $setting->getMarket()->getName(); ?></a></li>
                                                            <?php } ?>
                                                        </ul>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="col-md-12 leftalignlabel">
                                        	<div class="form-group clearfix">
                                                <label class="col-md-12 control-label"><?php echo $isme == true ? $this->translate('profile_my_preffered_districts') : $this->translate('profile_preffered_districts'); ?>: <span class="labeldescription"><?php echo $count_districts == 0 ? 'None' : $count_districts; ?> currently profiled</span></label>
                                                <div class="col-md-12 nullifempty">
                                                	<?php if($count_districts > 0){ ?>
                                                    	<ul class="nav">
															<?php foreach($districts as $setting){ ?>
                                                                <li style="width:250px; display:block;"><a href="<?php echo $this->baseUrl('location/view/id/'.$setting->getDistrict()->getName()); ?>"><?php echo $setting->getDistrict()->getName(); ?></a></li>
                                                            <?php } ?>
                                                        </ul>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="col-md-12 leftalignlabel">
                                        	<div class="form-group clearfix">
                                                <label class="col-md-12 control-label"><?php echo $isme == true ? $this->translate('profile_my_preffered_categories') : $this->translate('profile_preffered_categories'); ?>: <span class="labeldescription"><?php echo $count_categories == 0 ? 'None' : $count_categories; ?> currently profiled</span></label>
                                                <div class="col-md-12 nullifempty">
                                                	<?php if($count_categories > 0){ ?>
                                                    	<ul class="nav">
															<?php foreach($categories as $setting){ ?>
                                                                <li><a class="gonowhere" href="<?php //echo $this->baseUrl('forum/view/categoryid/'.encode($setting->getID())); ?>"><?php echo $setting->getCategory()->getName(); ?></a></li>
                                                            <?php } ?>
                                                        </ul>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="divider30"></div>
                                    <div class="row leftalignlabels" style="padding-left:30px;">
                                    	<div class="widget-header">
                                            <h4><i class="icon-reorder"></i> Email Notification Preferences</h4>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="form-group">
                                            <div class="col-md-12 padding0"><img src="<?php echo $user->getemailmeonpost() == 0 ? $this->baseUrl('images/tick_undone.png') : $this->baseUrl('images/tick_done.png'); ?>" /> &nbsp;<label class="control-label"><?php echo $this->translate('profile_emailmeonpost_label'); ?></label></div>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="form-group">
                                            <div class="col-md-12 padding0"><img src="<?php echo $user->getemailmeoncomment() == 0 ? $this->baseUrl('images/tick_undone.png') : $this->baseUrl('images/tick_done.png'); ?>" /> &nbsp;<label class="control-label"><?php echo $this->translate('profile_emailmeoncomment_label'); ?></label></div>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="form-group">
                                            <div class="col-md-12 padding0"><img src="<?php echo $user->getemailmeonmessage() == 0 ? $this->baseUrl('images/tick_undone.png') : $this->baseUrl('images/tick_done.png'); ?>" /> &nbsp;<label class="control-label"><?php echo $this->translate('profile_emailmeonmessage_label'); ?></label></div>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="form-group">
                                            <div class="col-md-12 padding0"><img src="<?php echo $user->getemailmeonallcrops() == 0 ? $this->baseUrl('images/tick_undone.png') : $this->baseUrl('images/tick_done.png'); ?>" /> &nbsp;<label class="control-label"><?php echo $this->translate('profile_emailmeonallcrops_label'); ?></label></div>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="form-group">
                                            <div class="col-md-12 padding0"><img src="<?php echo $user->getemailmeonallmarkets() == 0 ? $this->baseUrl('images/tick_undone.png') : $this->baseUrl('images/tick_done.png'); ?>" /> &nbsp;<label class="control-label"><?php echo $this->translate('profile_emailmeonallmarkets_label'); ?></label></div>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="form-group">
                                            <div class="col-md-12 padding0"><img src="<?php echo $user->getemailmeonalldistricts() == 0 ? $this->baseUrl('images/tick_undone.png') : $this->baseUrl('images/tick_done.png'); ?>" /> &nbsp;<label class="control-label"><?php echo $this->translate('profile_emailmeonalldistricts_label'); ?></label></div>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="form-group ">
                                            <div class="col-md-12 padding0"><img src="<?php echo $user->getemailmeforreport() == 0 ? $this->baseUrl('images/tick_undone.png') : $this->baseUrl('images/tick_done.png'); ?>" /> &nbsp;<label class="control-label"><?php echo $this->translate('profile_emailmeforreport_label'); ?></label></div>
                                        </div>
                                        <div class="divider15"></div>
                                        <div class="form-group">
                                            <div class="col-md-12 padding0"><img src="<?php echo $user->getemailmeonnews() == 0 ? $this->baseUrl('images/tick_undone.png') : $this->baseUrl('images/tick_done.png'); ?>" /> &nbsp;<label class="control-label"><?php echo $this->translate('profile_emailmeonnews_label'); ?></label></div>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                       	<?php if($tab == 'profile' && (!isPublicUser() || $isme || isAMIA() || ($user->getShowLocation() == 1 && isPublicUser()))){ ?>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="widget">
                                        <div class="widget-header">
                                            <h4><i class="icon-reorder"></i> Location</h4>
                                        </div>
                                        <div class="widget-content form-horizontal">
                                            <div class="row">
                                                <div class="col-md-8">
                                               		<div class="well clearfix makerelative" style="min-height:300px; height:auto; background-color:#fcfcfc; padding-bottom:10px;">
														<?php if(isEmptyString($request->detect)){ ?>
                                                        	<?php if($isme || !isPublicUser()){ ?>
                                                                <a class="btn btn-xs btn-info makeabsolute" style="top:-25px; left:0;" href="<?php echo $this->baseUrl('profile/view/id/'.encode($user->getID()).'/detect/1'); ?>"><?php echo $user->hasGPSCoordinates() ? 'Update Position' : 'Locate Position'; ?></a>
                                                            <?php } ?>
                                                                <div id="map_canvas" class="gmaps"></div>
                                                        <?php } else { ?>
                                                                <div id="current" class="xbolded">Initializing... Please wait... </div>
                                                                <div class="divider10"></div>	
                                                                <a href="<?php echo $this->referer; ?>" class="btn btn-sm"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                                                                <a href="<?php echo $this->baseUrl('profile/view/id/'.encode($user->getID()).'/detect/1'); ?>" class="btn btn-sm btn-inverse"><i class="icon-refresh"></i> Reload</a>
                                                                <button type="submit" class="btn btn-sm btn-success hide" id="saveposition"><i class="icon-ok icon-white"></i> <?php echo $this->translate('global_button_save')." Position"; ?></button>
                                                                <div class="form-group">
                                                                    <div id="hasgps_error"></div>
                                                                </div>
                                                                <div id="map_canvas" class="span12" style="height:400px; width:100%; margin-left:0;"></div>
                                                                <div class="divider20"></div>	
                                                                <input type="hidden" name="entityname" value="UserAccount" />
                                                                <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" />
                                                                <input type="hidden" id="hasgps" name="hasgps" value="" />
                                                                <input type="hidden" id="lat" name="lat" value="" />
                                                                <input type="hidden" id="lng" name="lng" value="" />
                                                                <input type="hidden" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl('profile/view/id/'.encode($user->getID()))); ?>" />
                                                                <input type="hidden" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($this->baseUrl('profile/view/id/'.encode($user->getID()).'/detect/1')); ?>" />
                                                                <input type="hidden" name="<?php echo SUCCESS_MESSAGE; ?>" value="global_save_success" />
                                                        <?php } ?>
                                                    </div>
                                                </div>
                                                <div class="col-md-4 leftalignlabel">
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_country_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $user->getCountryName(); ?></div>
                                                    </div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_district_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $user->getDistrict()->getName(); ?></div>
                                                    </div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_county_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $user->getCounty()->getName(); ?></div>
                                                    </div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_subcounty_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $user->getSubcounty()->getName(); ?></div>
                                                    </div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_parish_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $user->getParish()->getName(); ?></div>
                                                    </div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_village_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $user->getVillage()->getName(); ?></div>
                                                    </div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_address_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $user->getAddress(); ?></div>
                                                    </div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label">GPS:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $user->getGPSLat().', '.$user->getGPSLng(); ?></div>
                                                    </div>
                                                </div>
                                            </div>                                        
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>                          
                    </div>
                <?php } ?>
                <?php if ($acl->checkPermission('User Account', ACTION_EDIT) && ($isme || !isPublicUser())) { ?>
                    <div class="tab-pane" id="updateaccount">
                        
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
</form>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
