<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$lookuptype = new LookupType();
	
	$listurl = $this->baseUrl('config/categories');
	$title = "System Categories";
	$listitems = "Categories";
	$description = 'Application categorization categories';
	$lookupid = $request->type;
	$nextindex = ''; $columnheading = 'Values';
	
	if(!isEmptyString($lookupid)){
		$lookuptype->populate($lookupid);
		$nextindex = $lookuptype->getNextInsertIndex();
		$columnheading = $lookuptype->getDisplayName();
		$description = $lookuptype->getDescription(); 
	}
	// debugMessage($nextindex);
	
	$subcat = '';
	if(!isEmptyString($request->parentid)){
		$category = new Category();
		$category->populate($request->parentid);
		$subcat = ' - '.$category->getName();
		$columnheading = $subcat;
	}
	
	
	$this->headTitle($title.$browserappend);
	$showsearch = true;
	
?>
<script>
$(document).ready(function(){
	// breadcrumb config
	$("#levelone_icon").addClass('icon-settings');
	$("#levelone_link").attr('href', '').html('System');
	$("#leveltwo_link").attr('href', '<?php echo $listurl; ?>').html('Categories');
	
	$(".updatevalue").click(function(){
		var rowid = $(this).attr('rowid');
		$("#html_"+rowid).css({'display':'block'});
		$("#text_"+rowid).css({'display':'none'});
		$("tr#lookup_"+rowid).removeClass('editable');
	});
	$(".cancel_edit").click(function(){
		var rowid = $(this).attr('rowid');
		$("#html_"+rowid).css({'display':'none'});
		$("#text_"+rowid).css({'display':'block'});
		$("tr#lookup_"+rowid).addClass('editable');
	});
	
	// adding new items
	$("#save, .save").click(function(){
		// alert('adding new');
		var id = '';
		var lookupid = $(this).attr('theid');
		var value = $("#newvalue").val();
		var index = '<?php echo $nextindex; ?>';
		if(isEmptyString(value)) {
			$("div#add_error").html('<div class="alert alert-error">Please enter value</div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
			return false;
		} else {
			$(this).hide();
			$("#wait_0").show();
			var url = '<?php echo $this->baseUrl("config/processcategories"); ?>/id/'+id+'/lookupid/'+lookupid+'/value/'+value+'/index/'+index;
			// alert(url);
			window.location.href = url;
		}
	});
	// updating item
	$(".update").click(function(){
		// alert('adding new');
		var id = $(this).attr('theid');
		var lookupid = '<?php echo $lookuptype->getID(); ?>';
		var value = $("#newvalue_"+id).val();
		var index = $(this).attr('index');
		if(isEmptyString(value)) {
			$("div#add_error").html('<div class="alert alert-error">Please enter value</div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
			return false;
		} else {
			$(this).hide(); $('#cancel_'+id).hide();
			$("#wait_"+id).show();
			var url = '<?php echo $this->baseUrl("config/processcategories"); ?>/id/'+id+'/lookupid/'+lookupid+'/value/'+value+'/index/'+index;
			if(lookupid == '19'){
				var url = '<?php echo $this->baseUrl("config/processcategories/type/1"); ?>/id/'+id+'/lookupid/'+lookupid+'/value/'+value;
				var parentid = "<?php echo $request->parentid; ?>";
				if(!isEmptyString(parentid)){
					var url = '<?php echo $this->baseUrl("config/processcategories/type/2"); ?>/id/'+id+'/lookupid/'+lookupid+'/value/'+value+'/parentid/'+parentid;
				}
			}
			window.location.href = url;
		}
	});
	
	$(".filtertyppe").click(function(){
		var imageurl = '<?php echo $this->baseUrl('images/farmisloader.gif'); ?>';
		$("#contents").html("<a id='loading' class='xhidden' style='text-align:center; display:block; margin-top:75px;'><span style='display:block; margin-bottom:15px; font-weight:bold;'>Loading...</span><img style='margin-left:-10px;' src='<?php echo $this->baseUrl('images/farmisloader.gif'); ?>' /></a>").css({'display':'block'});
	});
	
});
</script>
<!--=== Page Header ===-->
<div class="page-header makerelative">
    <div class="page-title">
        <h3><?php echo $title; ?></h3>
        <span><?php echo $description; ?></span>
    </div>
    
</div>
<?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
    <div class="alert alert-success clear"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
<?php } ?>
<?php if($sessionhaserror) { ?>
    <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
<?php } ?>
    
<!--=== Responsive DataTable ===-->
<div class="row">					
	<div class="col-md-4">
		<div class="widget box">
			<div class="widget-header">
				<h4><i class="icon-reorder"></i> Category Type</h4>
			</div>
			<div class="widget-content">
				<div style="height:460px; overflow:scroll;">
                    <ul class="nav nav-tabs nav-stacked margin5 globalconfig">
                    	<ul class="nav nav-tabs nav-stacked margin5 listnavigation">
                        	<?php 
								$lists = getAllists();
								//debugMessage($lists);
							?>
							<?php foreach($lists as $key => $value){ ?>
								<li class="filtertyppe <?php echo $value['id'] == $lookupid ? 'active': ''; ?>"><a style="font-weight:normal; font-size:15px;" href="<?php echo $this->baseUrl('config/categories/type/'.$value['id']); ?>"><?php echo $value['name']; ?></a></li>
							<?php } ?>
                        </ul>
                    </ul>
                </div>
			</div> 
		</div>
	</div>
	<div class="col-md-8">
    	<?php
			
		?>
		<div class="widget box">
			<div class="widget-header">
				<h4><i class="icon-reorder"></i> <?php echo $columnheading; ?></h4>
			</div>
			<div class="widget-content">
				<div style="width:100%; border:1px solid #bababa; height:auto; min-height:460px; overflow:scroll; position:relative;">
					<?php if(isEmptyString($lookuptype->getID())){ ?>
                    	<div class="divider20"></div>
                        <div class="alert alert-info clear padding10 margin10">Select a Type to show values</div>
                    <?php } else { ?>
                    	<table class="table table-hover table-bordered commodities" style="margin:5px; width:98%;">
                        	<thead>
                                <tr>
                                    <td style="width:20px;" class="centeralign">#</td>
                                    <td>Display Value</td>
                                    <td style="width:90px;">System Value</td>
                                </tr>
                            </thead>
                            <?php if(!isEmptyString($request->type)){ ?>
                                <tbody id="global">
                                    <?php 
                                        $itemvalues = $lookuptype->getAllDataValues();
                                        // debugMessage($itemvalues);
                                        $x = 1;
                                        foreach($itemvalues as $value){
                                    ?>
                                    <tr id="lookup_<?php echo $value['id']; ?>" class="editable">
                                        <td class="centeralign"><?php echo $x; ?></td>
                                        <td>
                                            <div style="position:relative;">
                                                <span class="display" id="text_<?php echo $value['id']; ?>"><?php echo $value['lookupvaluedescription']; ?></span>
                                                <span class="edit" id="html_<?php echo $value['id']; ?>">
                                                    <input type="text" name="newvalue_<?php echo $value['id']; ?>" id="newvalue_<?php echo $value['id']; ?>" class="" style="width:65%; padding:4px;" value="<?php echo $value['lookupvaluedescription']; ?>" />
                                                    <label class="pull-right">
                                                        <a href="javascript:void(0)" id="save_<?php echo $value['id']; ?>" theid="<?php echo $value['id']; ?>" index="<?php echo $value['lookuptypevalue']; ?>" class="btn btn-success btn-xs lineblocked padding5 update" title="Update Item" ><i class="icon-ok icon-white"></i> Save</a>&nbsp;
                                                        <a href="javascript:void(0)" style="font-size:10px;" class="cancel_edit" id="cancel_<?php echo $value['id']; ?>" rowid="<?php echo $value['id']; ?>">Cancel</a>
                                                        <label class="hidden margin0 padding0" id="wait_<?php echo $value['id']; ?>" style="position:absolute; right:0; top:0;">
                                                            <span class="pagedescription">wait...</span>
                                                            <img style="margin-left:0; width:26px;" src="<?php echo $this->baseUrl('images/farmisloader.gif'); ?>" />
                                                        </label>
                                                    </label>
                                                    <div id="add_error_<?php echo $value['id']; ?>" class="margin0" style=""></div>
                                                </span>
                                                
                                                <div class="buttons" id="buttons_<?php echo $value['id']; ?>" style="position:absolute; right:0; top:-3px;">
													<?php if($lookuptype->updatesAllowed()){ ?>
                                                        <a href="javascript:void(0)" id="updatevalue_<?php echo $value['id']; ?>" rowid="<?php echo $value['id']; ?>" class="updatevalue btn btn-info btn-sm" title="Update Value"><i class="icon-pencil"></i></a>
                                                    <?php } ?>    
                                                    <?php if($lookuptype->addNoDeleteAllowed()){ 
														$classname = "LookupTypeValue";
														$deleteline = $value['id'];
														if($lookuptype->getName() == 'FORUM_CATEGORIES'){
															$classname = "Category";
															$deleteline = $value['lineid'];
														}
													?>
                                                        <a id="deletevalue_<?php echo $value['id']; ?>" rowid="<?php echo $value['id']; ?>" class="deletevalue btn btn-sm deleteline removeline gonowhere" title="Delete Value" action="<?php echo $this->baseUrl('config/delete/id/'.$deleteline."/entityname/".$classname."/successurl/".encode($this->baseUrl('config/categories/type/'.$request->type))); ?>"><i class="icon-remove"></i></a>
                                                    <?php } else { ?>
                                                    	<a class="gonowhere alert-dialog" title="Delete disabled" message="<div class='alert alert-danger'>Delete on this resource is disabled. Contact super Admin</div>">--</a>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="centeralign"><?php echo $value['lookuptypevalue']; ?></td>
                                    </tr>
                                    <?php $x++;} ?>
                                    <?php if($lookuptype->updatesAllowed() && !isEmptyString($lookuptype->getID())){ ?>
                                        <tr>
                                            <td class="centeralign"><?php echo $x; ?></td>
                                            <td>
                                                <div style="position:relative;">
                                                    <input type="text" name="newvalue" id="newvalue" class="" style="width:70%; padding:4px;" />&nbsp;
                                                    <label class="pull-right">
                                                        <a href="javascript:void(0)" id="save" theid="<?php echo $lookuptype->getID(); ?>" class="btn btn-success lineblocked padding5" title="Save New Item" ><i class="icon-ok icon-white"></i> Add</a>
                                                        <label class="margin0 padding0 hidden" id="wait_0" style="position:absolute; right:0; top:0;">
                                                            <span class="pagedescription">wait...</span>
                                                            <img style="margin-left:0; width:26px;" src="<?php echo $this->baseUrl('images/farmisloader.gif'); ?>" />
                                                        </label>
                                                    </label>
                                                    <div id="add_error" class="margin0" style=""></div>
                                                </div>
                                            </td>
                                            <td class="centeralign"><?php echo $x; ?></td>
                                        </tr>
                                    <?php } ?>
                                </tbody>
                            <?php } ?>    
                            </table>
                            <?php if(!$lookuptype->updatesAllowed()){ ?>
                                <div class="alert alert-info" style="margin:10px;">Updates to this variable are currently disabled. <br />Contact Super Admin</div>
                            <?php } ?>
                        </table>
                    <?php } ?>                    
                </div>
			</div>
		</div>
	</div>
</div>  
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>